// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Data.Configurations
{
    public partial class DistribEscritContadorConfiguration : IEntityTypeConfiguration<DistribEscritContador>
    {
        public void Configure(EntityTypeBuilder<DistribEscritContador> entity)
        {
            entity.HasKey(e => e.CodParamDistribEscrit)
                .HasName("PK_DISTRIB_ESCRIT_CONTADOR_COD");

            entity.ToTable("DISTRIB_ESCRIT_CONTADOR");

            entity.Property(e => e.CodParamDistribEscrit)
                .HasPrecision(15)
                .HasColumnName("COD_PARAM_DISTRIB_ESCRIT");

            entity.Property(e => e.Contador)
                .HasPrecision(10)
                .HasColumnName("CONTADOR");

            entity.HasOne(d => d.CodParamDistribEscritNavigation)
                .WithOne(p => p.DistribEscritContador)
                .HasForeignKey<DistribEscritContador>(d => d.CodParamDistribEscrit)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PARAM_DISTRIB_ESCRIT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DistribEscritContador> entity);
    }
}
