// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Data.Configurations
{
    public partial class TipoProcessoConfiguration : IEntityTypeConfiguration<TipoProcesso>
    {
        public void Configure(EntityTypeBuilder<TipoProcesso> entity)
        {
            entity.HasKey(e => e.CodTipoProcesso);

            entity.ToTable("TIPO_PROCESSO");

            entity.Property(e => e.CodTipoProcesso)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_PROCESSO");

            entity.Property(e => e.DscTipoProcesso)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_TIPO_PROCESSO");

            entity.Property(e => e.IndDistribuicaoEscritorio)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_DISTRIBUICAO_ESCRITORIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoProcesso> entity);
    }
}
