// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Data.Configurations
{
    public partial class ContratoDiretoriaConfiguration : IEntityTypeConfiguration<ContratoDiretoria>
    {
        public void Configure(EntityTypeBuilder<ContratoDiretoria> entity)
        {
            entity.HasKey(e => e.CodContratoDiretoria)
                .HasName("PK_COD_CONTRATO_DIRETORIA");

            entity.ToTable("CONTRATO_DIRETORIA");

            entity.Property(e => e.CodContratoDiretoria)
                .HasPrecision(10)
                .HasColumnName("COD_CONTRATO_DIRETORIA");

            entity.Property(e => e.DscContratoDiretoria)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_CONTRATO_DIRETORIA");

            entity.Property(e => e.IndDiretoriaPadraoContrato)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_DIRETORIA_PADRAO_CONTRATO")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContratoDiretoria> entity);
    }
}
