// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Data.Configurations
{
    public partial class ContratoEscritorioEstadoConfiguration : IEntityTypeConfiguration<ContratoEscritorioEstado>
    {
        public void Configure(EntityTypeBuilder<ContratoEscritorioEstado> entity)
        {
            entity.HasKey(e => e.CodContratoEscritorioEstado)
                .HasName("PK_CONT_ESCR_EST");

            entity.ToTable("CONTRATO_ESCRITORIO_ESTADO");

            entity.Property(e => e.CodContratoEscritorioEstado)
                .HasPrecision(10)
                .HasColumnName("COD_CONTRATO_ESCRITORIO_ESTADO");

            entity.Property(e => e.CodContratoEscritorio)
                .HasPrecision(10)
                .HasColumnName("COD_CONTRATO_ESCRITORIO");

            entity.Property(e => e.CodEstado)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("COD_ESTADO");

            entity.Property(e => e.CodProfissional)
                .HasPrecision(6)
                .HasColumnName("COD_PROFISSIONAL");

            entity.HasOne(d => d.CodContratoEscritorioNavigation)
                .WithMany(p => p.ContratoEscritorioEstado)
                .HasForeignKey(d => d.CodContratoEscritorio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_COD_CONTRATO_ESCRITORIO");

            entity.HasOne(d => d.CodEstadoNavigation)
                .WithMany(p => p.ContratoEscritorioEstado)
                .HasForeignKey(d => d.CodEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CE_COD_ESTADO");

            entity.HasOne(d => d.CodProfissionalNavigation)
                .WithMany(p => p.ContratoEscritorioEstado)
                .HasForeignKey(d => d.CodProfissional)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_COD_PROFISSIONAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContratoEscritorioEstado> entity);
    }
}
