// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ControleDeAcessoContext.Entities
{
    public partial class AcaMenu
    {
        public AcaMenu()
        {
            CodModuloNavigation = new HashSet<ModuloSisjur>();
            Menu = new HashSet<Menu>();
        }

        public string CodAplicacao { get; set; }
        public string CodMenu { get; set; }
        public string DescricaoMenu { get; set; }
        public string TipoMenu { get; set; }
        public string BitmapMenu { get; set; }
        public string IndRestrito { get; set; }
        public byte? CodModulo { get; set; }
        public string DscCaminhoMenuTela { get; set; }

        public virtual ICollection<ModuloSisjur> CodModuloNavigation { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}