// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ControleDeAcessoContext.Entities
{
    public partial class VPermissoesAcessoWeb
    {
        public string CodAplicacao { get; set; }
        public string CodJanela { get; set; }
        public string CodMenu { get; set; }
        public string CodUsuario { get; set; }
    }
}