// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AgendaAudienciaContext.Entities
{
    public partial class Preposto
    {
        public Preposto()
        {
            AudienciaProcessoCodPrepostoAcompNavigation = new HashSet<AudienciaProcesso>();
            AudienciaProcessoCodPrepostoNavigation = new HashSet<AudienciaProcesso>();
            ReclamadaPrepostoAudiencia = new HashSet<ReclamadaPrepostoAudiencia>();
        }

        public int CodPreposto { get; set; }
        public string NomPreposto { get; set; }
        public string NaoUsarCodEstado { get; set; }
        public string IndPrepostoCivel { get; set; }
        public string IndPrepostoTrabalhista { get; set; }
        public string IndPrepostoJuizado { get; set; }
        public string IndPrepostoAtivo { get; set; }
        public string CodUsuario { get; set; }
        public string IndCivelEstrategico { get; set; }
        public string IndProcon { get; set; }
        public string IndPex { get; set; }
        public string IndEscritorio { get; set; }
        public string Matricula { get; set; }

        public virtual AcaUsuario CodUsuarioNavigation { get; set; }
        public virtual Estado NaoUsarCodEstadoNavigation { get; set; }
        public virtual ICollection<AudienciaProcesso> AudienciaProcessoCodPrepostoAcompNavigation { get; set; }
        public virtual ICollection<AudienciaProcesso> AudienciaProcessoCodPrepostoNavigation { get; set; }
        public virtual ICollection<ReclamadaPrepostoAudiencia> ReclamadaPrepostoAudiencia { get; set; }
    }
}