// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AgendaAudienciaContext.Entities
{
    public partial class VAgendaTrabalhista
    {
        public int CodProcesso { get; set; }
        public DateTime? DateAudiencia { get; set; }
        public DateTime? HorarioAudiencia { get; set; }
        public short SeqAudiencia { get; set; }
        public string TipoAudiencia { get; set; }
        public short CodTipoAudiencia { get; set; }
        public string NumeroProcesso { get; set; }
        public string ClassificacaoHierarquica { get; set; }
        public string ProcessoAtivo { get; set; }
        public string EscritorioProcesso { get; set; }
        public string Estado { get; set; }
        public string Comarca { get; set; }
        public short? CodVara { get; set; }
        public short? CodTipoVara { get; set; }
        public string TipoVara { get; set; }
        public string UsuarioUltAteracao { get; set; }
        public DateTime? DataUltAtualizacao { get; set; }
        public string ClassificacaoProcesso { get; set; }
        public string Estrategico { get; set; }
        public int EmpresaAgrupadora { get; set; }
        public int CodParte { get; set; }
        public int? CodModalidadeAudiencia { get; set; }
        public int? CodLocalidadeAudiencia { get; set; }
        public string DescModalidade { get; set; }
        public string ModalidadeAtivo { get; set; }
        public string DescLocalidade { get; set; }
        public string LocalidadeAtivo { get; set; }
        public string? Link { get; set; }
    }
}