// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Data.Configurations;
using Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Entities;
using System;
using System.Collections.Generic;
#nullable disable

namespace Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Data
{
    public partial class ResultadoNegociacaoDbContext : DbContext
    {
        public ResultadoNegociacaoDbContext(DbContextOptions<ResultadoNegociacaoDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LogResultadoNegociacao> LogResultadoNegociacao { get; set; }
        public virtual DbSet<ResultadoCttMtv> ResultadoCttMtv { get; set; }
        public virtual DbSet<ResultadoNegociacao> ResultadoNegociacao { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("JUR");

        modelBuilder.ApplyConfiguration(new Configurations.LogResultadoNegociacaoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ResultadoCttMtvConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ResultadoNegociacaoConfiguration());
            modelBuilder.HasSequence("ABASPR_SEQ_01");

            modelBuilder.HasSequence("ACAAREAAT_SEQ_01");

            modelBuilder.HasSequence("ACAHISTAPRAC_SEQ_01");

            modelBuilder.HasSequence("ACAOU_SEQ_01");

            modelBuilder.HasSequence("ACASW_SEQ_01");

            modelBuilder.HasSequence("ADOCP_SEQ_01");

            modelBuilder.HasSequence("ADVOGADO_ESCRITORIO_SEQ_01");

            modelBuilder.HasSequence("AE_SEQ_01");

            modelBuilder.HasSequence("AEDPR_SEQ_01");

            modelBuilder.HasSequence("AFAP_SEQ_01");

            modelBuilder.HasSequence("AFAPU_SEQ_01");

            modelBuilder.HasSequence("AFGER_SEQ_01");

            modelBuilder.HasSequence("AGDRVC_SEQ_01");

            modelBuilder.HasSequence("AGEC_SEQ_01");

            modelBuilder.HasSequence("AGECP_SEQ_01");

            modelBuilder.HasSequence("AGEND_APURACAO_OUTLIERS_SEQ_01");

            modelBuilder.HasSequence("AGEND_CALC_REL_PAG_ESC_SEQ");

            modelBuilder.HasSequence("AGEND_CALC_VEP_SEQ");

            modelBuilder.HasSequence("AGEND_EXEC_CARGA_COMPR_PAG_SEQ");

            modelBuilder.HasSequence("AGEND_EXEC_CARGA_DOC_FGV_SEQ");

            modelBuilder.HasSequence("AGEND_EXEC_LANC_MASSA_SEQ_01");

            modelBuilder.HasSequence("AGEND_EXEC_MIGR_PED_SAP_SEQ");

            modelBuilder.HasSequence("AGEND_EXEC_REL_CRITERIO_SEQ_01");

            modelBuilder.HasSequence("AGEND_EXEC_REL_RECORR_SEQ_01");

            modelBuilder.HasSequence("AGEND_EXEC_RELATORIOS_SEQ_01");

            modelBuilder.HasSequence("AGEND_FECH_ATM_JEC_SEQ");

            modelBuilder.HasSequence("AGEND_REL_USR_PERF_SEQ");

            modelBuilder.HasSequence("AGEND_SALDO_GARANTIA_SEQ_01");

            modelBuilder.HasSequence("AGENDAMENTO_CARGA_SEQ_01");

            modelBuilder.HasSequence("AGFE_SEQ_01");

            modelBuilder.HasSequence("AGFECHCONT_SEQ_01");

            modelBuilder.HasSequence("AGRC_SEQ_01");

            modelBuilder.HasSequence("AGRCP_SEQ_01");

            modelBuilder.HasSequence("AGREL_SEQ_01");

            modelBuilder.HasSequence("AGRP_SEQ_01");

            modelBuilder.HasSequence("AIUPG_SEQ_01");

            modelBuilder.HasSequence("ALPRCO_SEQ_01");

            modelBuilder.HasSequence("ALTERACAO_BLOCO_WEB_SEQ");

            modelBuilder.HasSequence("ALTERACAO_PROC_BLOCO_SEQ_01");

            modelBuilder.HasSequence("AMCC_SEQ_01");

            modelBuilder.HasSequence("AMJEC_SEQ_01");

            modelBuilder.HasSequence("AMP_SEQ_01");

            modelBuilder.HasSequence("AMT_SEQ");

            modelBuilder.HasSequence("ANDAM_PROC_SERV_PROC_SEQ_01");

            modelBuilder.HasSequence("ANDLP_SEQ_01");

            modelBuilder.HasSequence("APCON_SEQ_01");

            modelBuilder.HasSequence("APDOC_SEQ_01");

            modelBuilder.HasSequence("APDOC_SEQ_02");

            modelBuilder.HasSequence("APDOC_SEQ_03");

            modelBuilder.HasSequence("APESS_SEQ_01");

            modelBuilder.HasSequence("APGE_SEQ_01");

            modelBuilder.HasSequence("APRIORIFILA_SEQ_01");

            modelBuilder.HasSequence("APRS_SEQ_01");

            modelBuilder.HasSequence("APRSCOL_SEQ_01");

            modelBuilder.HasSequence("APRSDATA_SEQ_01");

            modelBuilder.HasSequence("APRSESC_SEQ_01");

            modelBuilder.HasSequence("APRSHIST_SEQ_01");

            modelBuilder.HasSequence("APRSMOD_SEQ_01");

            modelBuilder.HasSequence("APRSREL_SEQ_01");

            modelBuilder.HasSequence("APRSSTA_SEQ_01");

            modelBuilder.HasSequence("APRSTL_SEQ_01");

            modelBuilder.HasSequence("APRSU_SEQ_01");

            modelBuilder.HasSequence("APU_SEQ_01");

            modelBuilder.HasSequence("ARENV_SEQ_01");

            modelBuilder.HasSequence("ASOPR_SEQ_01");

            modelBuilder.HasSequence("ATRIBUTO_SERV_PREST_AUX_SEQ_01");

            modelBuilder.HasSequence("ATRIBUTO_TP_SERV_PREST_SEQ_01");

            modelBuilder.HasSequence("ATRTS_SEQ_01");

            modelBuilder.HasSequence("BASE_CC_WEB_SEQ");

            modelBuilder.HasSequence("BASE_CE_WEB_SEQ");

            modelBuilder.HasSequence("BASE_FECHAM_JEC_COMPL_SEQ_01");

            modelBuilder.HasSequence("BBCOM_SEQ_01");

            modelBuilder.HasSequence("BBMOD_SEQ_01");

            modelBuilder.HasSequence("BBNAT_SEQ_01");

            modelBuilder.HasSequence("BBORG_SEQ_01");

            modelBuilder.HasSequence("BBRPA_SEQ_01");

            modelBuilder.HasSequence("BBSTP_SEQ_01");

            modelBuilder.HasSequence("BBSTR_SEQ_01");

            modelBuilder.HasSequence("BBTRI_SEQ_01");

            modelBuilder.HasSequence("BO_SEQ_01");

            modelBuilder.HasSequence("BPEN_SEQ_01");

            modelBuilder.HasSequence("CAE_SEQ_01");

            modelBuilder.HasSequence("CAMARA_SEQ_01");

            modelBuilder.HasSequence("CARGA_CREDOR_OCORRENCIA_SEQ_01");

            modelBuilder.HasSequence("CARGA_CREDOR_SEQ_01");

            modelBuilder.HasSequence("CATDEV_SEQ_01");

            modelBuilder.HasSequence("CATEGORIA_PAG_SERV_SEQ_01");

            modelBuilder.HasSequence("CATEV_SEQ_01");

            modelBuilder.HasSequence("CBO_SEQ_01");

            modelBuilder.HasSequence("CCGER_SEQ_01");

            modelBuilder.HasSequence("CDNUT_SEQ_01");

            modelBuilder.HasSequence("CFTG_SEQ_01");

            modelBuilder.HasSequence("CFTRIBGER_SEQ_01");

            modelBuilder.HasSequence("CFTRIBGERAT_SEQ_01");

            modelBuilder.HasSequence("CGGAT_SEQ_01");

            modelBuilder.HasSequence("CJGAT_SEQ_01");

            modelBuilder.HasSequence("CJGER_SEQ_01");

            modelBuilder.HasSequence("CJPGE_SEQ_01");

            modelBuilder.HasSequence("CJUI_SEQ_01");

            modelBuilder.HasSequence("CLASSAUTOR_SEQ_01");

            modelBuilder.HasSequence("CLCR_SEQ_01");

            modelBuilder.HasSequence("CLIRE_SEQ_01");

            modelBuilder.HasSequence("CLOG_SEQ_01");

            modelBuilder.HasSequence("CLOGI_SEQ_01");

            modelBuilder.HasSequence("CMFM_SEQ_01");

            modelBuilder.HasSequence("COCR_SEQ_01");

            modelBuilder.HasSequence("COLPSERV_SEQ_01");

            modelBuilder.HasSequence("CONPRO_SEQ_01");

            modelBuilder.HasSequence("CONTRATO_ATUACAO_SEQ");

            modelBuilder.HasSequence("CONTRATO_DIRETORIA_SEQ");

            modelBuilder.HasSequence("CONTRATO_ESCRITORIO_ESTADO_SEQ");

            modelBuilder.HasSequence("CONTRATO_ESCRITORIO_SEQ");

            modelBuilder.HasSequence("CONTROLE_REMUNERACAO_PROC_SEQ");

            modelBuilder.HasSequence("CONVERGE_SERV_PRESTADO_SEQ_01");

            modelBuilder.HasSequence("CPCAD_SEQ_01");

            modelBuilder.HasSequence("CREDOR_COMPROMISSO_SEQ_01");

            modelBuilder.HasSequence("CREDOR_SEQ_01");

            modelBuilder.HasSequence("CRIT_SALDO_GARANTIA_SEQ_01");

            modelBuilder.HasSequence("CTG_TRAB_AGRUP_OUT_SEQ");

            modelBuilder.HasSequence("CTG_TRAB_AGRUP_PROC_OUT_SEQ");

            modelBuilder.HasSequence("CTGAT_SEQ_01");

            modelBuilder.HasSequence("DAUPR_SEQ_01");

            modelBuilder.HasSequence("DDD_UF_REGIAO_SEQ_01");

            modelBuilder.HasSequence("DDPAG_SEQ_01");

            modelBuilder.HasSequence("DE_PARA_STATUS_APP_ID");

            modelBuilder.HasSequence("DE_PARA_STATUS_NEG_APP_ID");

            modelBuilder.HasSequence("DENC_SEQ_01");

            modelBuilder.HasSequence("DETALHAMENTO_APURACAO_SEQ_01");

            modelBuilder.HasSequence("DIFP_SEQ_01");

            modelBuilder.HasSequence("DIRBB_SEQ_01");

            modelBuilder.HasSequence("DIRETORIO_SEQ_01");

            modelBuilder.HasSequence("DIRFPR_SEQ_01");

            modelBuilder.HasSequence("DLANPR_SEQ_01");

            modelBuilder.HasSequence("DMLOGEXT_SEQ_01");

            modelBuilder.HasSequence("DMLOGEXT_SEQ_02");

            modelBuilder.HasSequence("DNUT_SEQ_01");

            modelBuilder.HasSequence("DOATR_SEQ_01");

            modelBuilder.HasSequence("DOCDIR_SEQ_01");

            modelBuilder.HasSequence("DOCPR_SEQ_01");

            modelBuilder.HasSequence("DOCUMENTO_COMP_PROCESSO_SEQ_01");

            modelBuilder.HasSequence("DQLANPR_SEQ_01");

            modelBuilder.HasSequence("EADV_SEQ_01");

            modelBuilder.HasSequence("EC_SEQ_01");

            modelBuilder.HasSequence("ECO_SEQ_01");

            modelBuilder.HasSequence("EMAIL_SEQ_01");

            modelBuilder.HasSequence("EMP_CENT_AGEN_FECH_AUTO_SEQ_01");

            modelBuilder.HasSequence("EMP_CENT_GAR_AGEN_FECH_AUT_SEQ");

            modelBuilder.HasSequence("EQUIPEAREA_SEQ_01");

            modelBuilder.HasSequence("ES_GERAMATRICULA_F2500");

            modelBuilder.HasSequence("ES_INCONSISTENCIAS_F2500_F250");

            modelBuilder.HasSequence("ES_TABELA_INCONSISTENCIAS_SEQ");

            modelBuilder.HasSequence("ES_TABELA_PROCESSADOS_SEQ");

            modelBuilder.HasSequence("EVENTO_TIPO_PROCESSO_SEQ_01");

            modelBuilder.HasSequence("EVENTO_TP_PROC_TP_SERV_SEQ_01");

            modelBuilder.HasSequence("EVGAR_SEQ_01");

            modelBuilder.HasSequence("EXP_SEQ_01");

            modelBuilder.HasSequence("EXPORTACAO_PRE_POS_RJ_SEQ");

            modelBuilder.HasSequence("EXTQUANT_SEQ_01");

            modelBuilder.HasSequence("FASEPRO_SEQ_01");

            modelBuilder.HasSequence("FCCM_SEQ_01");

            modelBuilder.HasSequence("FCCMB_SEQ_01");

            modelBuilder.HasSequence("FCCMBP_SEQ_01");

            modelBuilder.HasSequence("FCGED_SEQ_01");

            modelBuilder.HasSequence("FCHM_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_ATM_JEC_SEQ");

            modelBuilder.HasSequence("FECHAMENTO_BASE_MOV_JEC_SEQ");

            modelBuilder.HasSequence("FECHAMENTO_OUT_AUDIT_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_BASE_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_DADO_PED_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_ESTOQUE_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_EXP_PERD_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_GRUP_EMP_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_PER_PERD_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_PRO_FORA_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_PROC_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUT_PROVISAO_SEQ_01");

            modelBuilder.HasSequence("FECHAMENTO_OUTLIERS_SEQ_01");

            modelBuilder.HasSequence("FIEL_SEQ_01");

            modelBuilder.HasSequence("FILAAGUARDRET_SEQ_01");

            modelBuilder.HasSequence("FILACAD_SEQ_01");

            modelBuilder.HasSequence("FILAINTGED_SEQ_01");

            modelBuilder.HasSequence("FILASERV_SEQ_01");

            modelBuilder.HasSequence("FPM_SEQ_01");

            modelBuilder.HasSequence("FPMA_SEQ_01");

            modelBuilder.HasSequence("FPMB_SEQ_01");

            modelBuilder.HasSequence("FPMP_SEQ_01");

            modelBuilder.HasSequence("FPMV_SEQ_01");

            modelBuilder.HasSequence("FPTR_SEQ_01");

            modelBuilder.HasSequence("FTGER_SEQ_01");

            modelBuilder.HasSequence("FTGPR_SEQ_01");

            modelBuilder.HasSequence("FTRATSERV_SEQ_01");

            modelBuilder.HasSequence("FVI_SEQ_01");

            modelBuilder.HasSequence("GED_SEQ_01");

            modelBuilder.HasSequence("GEROF_SEQ_01");

            modelBuilder.HasSequence("GFIPPR_SEQ_01");

            modelBuilder.HasSequence("GPROCON_SEQ_01");

            modelBuilder.HasSequence("GRPCG_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMP_CONT_SAP_PART_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMP_CONTABIL_SAP_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMP_DIN_PARTE_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMPRESA_DINAMICO_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMPRESAS_OUT_PART_SEQ_01");

            modelBuilder.HasSequence("GRUPO_EMPRESAS_OUTLIERS_SEQ_01");

            modelBuilder.HasSequence("GRUPO_ESTADO_ESTADO_SEQ_01");

            modelBuilder.HasSequence("GRUPO_ESTADO_SEQ_01");

            modelBuilder.HasSequence("GSERV_SEQ_01");

            modelBuilder.HasSequence("HEMGA_SEQ_01");

            modelBuilder.HasSequence("HIAE_SEQ_01");

            modelBuilder.HasSequence("HIEP_SEQ_01");

            modelBuilder.HasSequence("HISTAGFECCONT_SEQ_01");

            modelBuilder.HasSequence("HISTMIGDP_SEQ_01");

            modelBuilder.HasSequence("HON_CARGA_PAGAMENTO_ITEM_SEQ");

            modelBuilder.HasSequence("HON_CARGA_PAGAMENTO_SEQ");

            modelBuilder.HasSequence("HON_EMP_CENTRALIZADORA_SEQ_01");

            modelBuilder.HasSequence("HON_FAT_FIL_SEQUENCE_01");

            modelBuilder.HasSequence("HON_FATURAMENTO_SEQ");

            modelBuilder.HasSequence("HON_FILIAL_SEQ_01");

            modelBuilder.HasSequence("HON_FORNECEDOR_EMAIL_SEQ");

            modelBuilder.HasSequence("HON_FORNECEDOR_SEQ");

            modelBuilder.HasSequence("HON_MODELO_EMAIL_ARQ_SEQ_01");

            modelBuilder.HasSequence("HON_MODELO_EMAIL_SEQ");

            modelBuilder.HasSequence("HON_PARAMETRO_HONORARIO_SEQ");

            modelBuilder.HasSequence("HON_PLANILHA_PADRAO_SEQ");

            modelBuilder.HasSequence("HON_RECEBEDOR_SEQ");

            modelBuilder.HasSequence("IADIN_SEQ_01");

            modelBuilder.HasSequence("ID_CREDOR_SEQ_01");

            modelBuilder.HasSequence("ID_SEQUENCE");

            modelBuilder.HasSequence("IDENTIFIC_DOC_PROCESSO_SEQ_01");

            modelBuilder.HasSequence("IFDP_SEQ_01");

            modelBuilder.HasSequence("IFEE_SEQ_01");

            modelBuilder.HasSequence("IFPPO_SEQ_01");

            modelBuilder.HasSequence("IFPPR_SEQ_01");

            modelBuilder.HasSequence("IFPRS_SEQ_01");

            modelBuilder.HasSequence("IFPSM_SEQ_01");

            modelBuilder.HasSequence("IFPTR_SEQ_01");

            modelBuilder.HasSequence("IHOU_SEQ_01");

            modelBuilder.HasSequence("IMPHISTUSU_SEQ_01");

            modelBuilder.HasSequence("IMPSITUSU_SEQ_01");

            modelBuilder.HasSequence("IPENP_SEQ_01");

            modelBuilder.HasSequence("IPNP_SEQ_01");

            modelBuilder.HasSequence("LCENT_SEQ_01");

            modelBuilder.HasSequence("LOG_AGEND_EXEC_REL_ROT_SEQ_01");

            modelBuilder.HasSequence("LOG_CLASSE_PLANO_COMP_SEQ_01");

            modelBuilder.HasSequence("LOG_COMP_PROC_ADV_SEQ_01");

            modelBuilder.HasSequence("LOG_COMP_PROC_AUT_SEQ_01");

            modelBuilder.HasSequence("LOG_COMP_PROC_CRED_SEQ_01");

            modelBuilder.HasSequence("LOG_COMP_PROC_PARCELA_SEQ_01");

            modelBuilder.HasSequence("LOG_COMPROMISSO_PROC_SEQ_01");

            modelBuilder.HasSequence("LOG_CREDOR_COMPROMISSO_SEQ_01");

            modelBuilder.HasSequence("LOG_CREDOR_SEQ_01");

            modelBuilder.HasSequence("LOG_EXEC_FECH_OUTLIERS_SEQ_01");

            modelBuilder.HasSequence("LOG_EXEC_RET_SAP_LOTE_SEQ_01");

            modelBuilder.HasSequence("LOG_EXECUCAO_LOTE_SEQ_01");

            modelBuilder.HasSequence("LOG_MOT_SUSP_CANC_PARC_SEQ_01");

            modelBuilder.HasSequence("LOG_PERC_ATUAL_MONET_SEQ_01");

            modelBuilder.HasSequence("LOG_PLANO_COMPROMISSO_SEQ_01");

            modelBuilder.HasSequence("LOG_USUARIO_AGENDAMENTO_SEQ");

            modelBuilder.HasSequence("LOTE_IMP_LANCAMENTO_SEQ_01");

            modelBuilder.HasSequence("LOTE_IMPORT_LANC_LINHA_SEQ_01");

            modelBuilder.HasSequence("LOTE_PAG_LINHA_SEQ_01");

            modelBuilder.HasSequence("LOTE_PAGAMENTO_SEQ_01");

            modelBuilder.HasSequence("LOTE_SEQ_01");

            modelBuilder.HasSequence("MEDCC_SEQ_01");

            modelBuilder.HasSequence("MEDCE_SEQ_01");

            modelBuilder.HasSequence("MENU_SEQ");

            modelBuilder.HasSequence("MIGCPROC_SEQ_01");

            modelBuilder.HasSequence("MIGJPROC_SEQ_01");

            modelBuilder.HasSequence("MIGRACAO_PROCESSO_WEB_SEQ");

            modelBuilder.HasSequence("MIGRPROC_SEQ_01");

            modelBuilder.HasSequence("MNCP_SEQ_01");

            modelBuilder.HasSequence("MOB_AUT_USUARIO_SEQ_01");

            modelBuilder.HasSequence("MOB_CONTROLE_NONCE_SEQ_01");

            modelBuilder.HasSequence("MOTAE_SEQ_01");

            modelBuilder.HasSequence("MOTDEV_SEQ_01");

            modelBuilder.HasSequence("MOTFIN_SEQ_01");

            modelBuilder.HasSequence("MOTIVO_APURACAO_SEQ_01");

            modelBuilder.HasSequence("MOTIVO_SUSP_CANC_PARC_SEQ_01");

            modelBuilder.HasSequence("MPPROC_SEQ_01");

            modelBuilder.HasSequence("MRSE_SEQ_01");

            modelBuilder.HasSequence("MTFM_SEQ_01");

            modelBuilder.HasSequence("MVGAR_SEQ_01");

            modelBuilder.HasSequence("NATDE_SEQ_01");

            modelBuilder.HasSequence("NCTRAB_SEQ_01");

            modelBuilder.HasSequence("NOFER_SEQ_01");

            modelBuilder.HasSequence("NOTIFICACAO_SEQ_01");

            modelBuilder.HasSequence("NOTIFICAO_USUARIO_SEQ_01");

            modelBuilder.HasSequence("NTPRO_SEQ_01");

            modelBuilder.HasSequence("OBCR_SEQ_01");

            modelBuilder.HasSequence("OFENSOR_MULTA_SEQ_01");

            modelBuilder.HasSequence("OPDOM_SEQ_01");

            modelBuilder.HasSequence("PAR_SEQ_01");

            modelBuilder.HasSequence("PART_SEQ_01");

            modelBuilder.HasSequence("PEDME_SEQ_01");

            modelBuilder.HasSequence("PEMPR_SEQ_01");

            modelBuilder.HasSequence("PERCENT_ATUAL_MONETARIA_SEQ_01");

            modelBuilder.HasSequence("PERCENTUAL_ATM_SEQ_01");

            modelBuilder.HasSequence("PLANRECON_SEQ_01");

            modelBuilder.HasSequence("PMPC_SEQ_01");

            modelBuilder.HasSequence("POD_SEQ_01");

            modelBuilder.HasSequence("PPCAD_SEQ_01");

            modelBuilder.HasSequence("PPSERV_SEQ_01");

            modelBuilder.HasSequence("PRACR_SEQ_01");

            modelBuilder.HasSequence("PRCON_SEQ_01");

            modelBuilder.HasSequence("PROC_SEQ_01");

            modelBuilder.HasSequence("PROF_SEQ_01");

            modelBuilder.HasSequence("PROT_SEQ_01");

            modelBuilder.HasSequence("PROTD_SEQ_01");

            modelBuilder.HasSequence("RCCC_SEQ_01");

            modelBuilder.HasSequence("RCPM_SEQ_01");

            modelBuilder.HasSequence("REL_DMENOSUM_EXTRACAO_SEQ_01");

            modelBuilder.HasSequence("REL_DMENOSUM_LOG_SEQ_01");

            modelBuilder.HasSequence("REL_MOD_PRDF_CRITERIOS_SEQ_01");

            modelBuilder.HasSequence("RELAT_SEQ_01");

            modelBuilder.HasSequence("RELATORIO_MOVIMENTACAO_CC_SEQ");

            modelBuilder.HasSequence("RELATORIO_MOVIMENTACAO_JEC_SEQ");

            modelBuilder.HasSequence("RELATORIO_PAG_ESCRITORIO_SEQ");

            modelBuilder.HasSequence("RELATORIOS_LANCAMENTO_SEQ_01");

            modelBuilder.HasSequence("RELSERV_SEQ_01");

            modelBuilder.HasSequence("REORG_SEQ_01");

            modelBuilder.HasSequence("REPENG_MODELO_SEQ_01");

            modelBuilder.HasSequence("RESDP_SEQ_01");

            modelBuilder.HasSequence("RESULT_EXEC_APP_PREPOSTO_SEQ");

            modelBuilder.HasSequence("RESULTADO_APURACAO_SEQ_01");

            modelBuilder.HasSequence("RMP_SEQ_01");

            modelBuilder.HasSequence("RSEP_SEQ_01");

            modelBuilder.HasSequence("RTO_SEQ_01");

            modelBuilder.HasSequence("RTOD_SEQ_01");

            modelBuilder.HasSequence("RTS_SEQ_01");

            modelBuilder.HasSequence("SCHE_LOG_SEQ_01");

            modelBuilder.HasSequence("SEQ_ACOMP_EXEC_FORMULARIOS");

            modelBuilder.HasSequence("SEQ_ACOMPANHAMENTO_EXECUTOR");

            modelBuilder.HasSequence("SEQ_BASE_CALC_VEP_ESCRITORIO");

            modelBuilder.HasSequence("SEQ_COD_PARAM_DISTRIB_ESCRIT");

            modelBuilder.HasSequence("SEQ_EMP_TERCEIRO_CONTRATADA");

            modelBuilder.HasSequence("SEQ_EMPRESA_CONTRATADA");

            modelBuilder.HasSequence("SEQ_ID_ANEXOS_DIST_ESCRITORIO");

            modelBuilder.HasSequence("SEQ_ID_ES_DASHBOARD");

            modelBuilder.HasSequence("SEQ_ID_ES_EMPRESA_AGRUPADORA");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_ABONO");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_DEPENDENTE");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_IDEPERIODO");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_INFOCONTRATO");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_MUDCATEGATIV");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_OBSERVACOES");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_REMUNERACAO");

            modelBuilder.HasSequence("SEQ_ID_ES_F2500_UNICCONTR");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_BENEFPEN");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_CALCTRIB");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_DEDDEPEN");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_DEDSUSP");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_IDEADV");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_INFOCRCONTRIB");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_INFOCRIRRF");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_INFODEP");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_INFOPROCRET");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_INFOVALORES");

            modelBuilder.HasSequence("SEQ_ID_ES_F2501_PENALIM");

            modelBuilder.HasSequence("SEQ_ID_F2500");

            modelBuilder.HasSequence("SEQ_PARAM_DISTRIBUICAO");

            modelBuilder.HasSequence("SEQ_RELATORIO_CALC_VEP_ESC");

            modelBuilder.HasSequence("SEQ_RESULTADO_CTT_MTV");

            modelBuilder.HasSequence("SEQ_RESULTADO_NEGOCIACAO");

            modelBuilder.HasSequence("SEQ_SOLICITANTE");

            modelBuilder.HasSequence("SEQ_STATUS_CONTATO");

            modelBuilder.HasSequence("SEQ_TERCEIRO_CONTRATADO");

            modelBuilder.HasSequence("SEQ_TRE");

            modelBuilder.HasSequence("SERV_BLOCO_AGEND_PROC_SEQ_01");

            modelBuilder.HasSequence("SERV_BLOCO_AGENDAMENTO_SEQ_01");

            modelBuilder.HasSequence("SERV_BLOCO_CRIACAO_SEQ_01");

            modelBuilder.HasSequence("SERV_BLOCO_INS_ANDAM_SEQ_01");

            modelBuilder.HasSequence("SERV_BLOCO_VALOR_ATRIB_SEQ_01");

            modelBuilder.HasSequence("SERVAUT_SEQ_01");

            modelBuilder.HasSequence("SERVICO_AUTOMATICO_COM_SEQ_01");

            modelBuilder.HasSequence("SERVICO_AUTOMATICO_ELO_SEQ_01");

            modelBuilder.HasSequence("SERVICO_PRESTADO_PROC_SEQ_01");

            modelBuilder.HasSequence("SITCON_SEQ_01");

            modelBuilder.HasSequence("SLPD_SEQ_01");

            modelBuilder.HasSequence("SOL_AMPLIACAO_ACESSO_SEQ");

            modelBuilder.HasSequence("SOL_LANC_DESDOBRAMENTO_SEQ_01");

            modelBuilder.HasSequence("SOLACE_SEQ_01");

            modelBuilder.HasSequence("SOLALC_SEQ_01");

            modelBuilder.HasSequence("SOLAP_SEQ_01");

            modelBuilder.HasSequence("SOLIC_FECH_CONT_EMP_CENT_SEQ");

            modelBuilder.HasSequence("SOLIC_FECH_GAR_EMP_CENT_SEQ");

            modelBuilder.HasSequence("SOLIC_FECHAMENTO_CONT_SEQ");

            modelBuilder.HasSequence("SOLIC_FECHAMENTO_GAR_SEQ");

            modelBuilder.HasSequence("SOLIC_LANC_DEPOSITO_SEQ_01");

            modelBuilder.HasSequence("SOLIC_LANC_PROCESSO_SEQ_01");

            modelBuilder.HasSequence("SOLICITACAO_LANCAMENTO_SEQ_01");

            modelBuilder.HasSequence("SOLPR_SEQ_01");

            modelBuilder.HasSequence("SOX_JANELA_ITEM_ALTERACAO_SEQ");

            modelBuilder.HasSequence("SOX_JANELA_ITEM_SEQ");

            modelBuilder.HasSequence("SOX_JANELA_SEQ");

            modelBuilder.HasSequence("SRA_SEQ_01");

            modelBuilder.HasSequence("STATD_SEQ_01");

            modelBuilder.HasSequence("STATUS_DE_PARA_ID");

            modelBuilder.HasSequence("STATUS_DE_PARA_NEG_ID");

            modelBuilder.HasSequence("STP_SEQ_01");

            modelBuilder.HasSequence("STPPR_SEQ_01");

            modelBuilder.HasSequence("SVATR_SEQ_01");

            modelBuilder.HasSequence("TAE_SEQ_01");

            modelBuilder.HasSequence("TBEM_SEQ_01");

            modelBuilder.HasSequence("TECNOL_SERV_PRESTADO_SEQ_01");

            modelBuilder.HasSequence("TESE_SEQ_01");

            modelBuilder.HasSequence("TEVSO_SEQ_01");

            modelBuilder.HasSequence("TIPO_CONTRATO_ESCRITORIO_SEQ");

            modelBuilder.HasSequence("TIPO_RESGATE_SEQ_01");

            modelBuilder.HasSequence("TITP_SEQ_01");

            modelBuilder.HasSequence("TMGAR_SEQ_01");

            modelBuilder.HasSequence("TMPORIGEMAIL_SEQ_01");

            modelBuilder.HasSequence("TOKEN_SEQ_01");

            modelBuilder.HasSequence("TOTALIZADORES_AUDITORIA_SEQ_01");

            modelBuilder.HasSequence("TPEMP_SEQ_01");

            modelBuilder.HasSequence("TPPAPEL_SEQ_01");

            modelBuilder.HasSequence("TPRCD_SEQ_01");

            modelBuilder.HasSequence("TSEARE_SEQ_01");

            modelBuilder.HasSequence("TSERV_SEQ_01");

            modelBuilder.HasSequence("TSESTE_SEQ_01");

            modelBuilder.HasSequence("TSOL_SEQ_01");

            modelBuilder.HasSequence("TURMAREC_SEQ_01");

            modelBuilder.HasSequence("UDOCP_SEQ_01");

            modelBuilder.HasSequence("USOPR_SEQ_01");

            modelBuilder.HasSequence("USUARIO_ESTRANGEIRO_SEQ_01");

            modelBuilder.HasSequence("VCMUL_SEQ_01");

            modelBuilder.HasSequence("WS_ANDA_BLOCO_SEQ_01");

            modelBuilder.HasSequence("WS_AREA_EMAIL_COBRANCA_SEQ_01");

            modelBuilder.HasSequence("WS_AREA_TRATAMENTO_SEQ_01");

            modelBuilder.HasSequence("WS_LOG_SERVICO_PROCESSO_SEQ_01");

            modelBuilder.HasSequence("WS_MOTIVO_TRATAMENTO_SEQ_01");

            modelBuilder.HasSequence("WS_SERV_BLOCO_SEQ_01");

            modelBuilder.HasSequence("WS_SERVICO_AUTOMATICO_SEQ_01");

            modelBuilder.HasSequence("WS_STATUS_SERVICO_SEQ_01");

            modelBuilder.HasSequence("WS_TIPO_ANDAMENTO_SEQ_01");

            modelBuilder.HasSequence("WS_TIPO_SERVICO_SEQ_01");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
