// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.V2.AtmPexContext.Entities
{
    public partial class AgendFechAtmPexUf
    {
        public decimal Id { get; set; }
        public decimal AgFechAtmPexId { get; set; }
        public int? CodTipoProcesso { get; set; }
        public string CodEstado { get; set; }
        public short CodIndice { get; set; }

        public virtual AgendFechAtmPex AgFechAtmPex { get; set; }
        public virtual Estado CodEstadoNavigation { get; set; }
        public virtual Indice CodIndiceNavigation { get; set; }
    }
}