// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.V2.AtmJecContext.Data;
using Oi.Juridico.Contextos.V2.AtmJecContext.Entities;
using System;


namespace Oi.Juridico.Contextos.V2.AtmJecContext.Data.Configurations
{
    public partial class AgendFechAtmJecConfiguration : IEntityTypeConfiguration<AgendFechAtmJec>
    {
        public void Configure(EntityTypeBuilder<AgendFechAtmJec> entity)
        {
            entity.HasKey(e => e.AfajId);

            entity.ToTable("AGEND_FECH_ATM_JEC");

            entity.Property(e => e.AfajId)
                .HasPrecision(8)
                .ValueGeneratedNever()
                .HasColumnName("AFAJ_ID");

            entity.Property(e => e.DatAgendamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.FajId)
                .HasPrecision(8)
                .HasColumnName("FAJ_ID");

            entity.Property(e => e.MsgErro)
                .HasColumnType("CLOB")
                .HasColumnName("MSG_ERRO");

            entity.Property(e => e.Status)
                .HasPrecision(2)
                .HasColumnName("STATUS");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.HasOne(d => d.Faj)
                .WithMany(p => p.AgendFechAtmJec)
                .HasForeignKey(d => d.FajId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AFAJ_FAJ");

            entity.HasOne(d => d.UsrCodUsuarioNavigation)
                .WithMany(p => p.AgendFechAtmJec)
                .HasForeignKey(d => d.UsrCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AFAJ_ACA_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendFechAtmJec> entity);
    }
}
