// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacoesJecContext.Entities
{
    public partial class EmpresasCentralizadoras
    {
        public EmpresasCentralizadoras()
        {
            FechamentoMovJec = new HashSet<FechamentoMovJec>();
        }

        public short Codigo { get; set; }
        public string Nome { get; set; }
        public byte NumOrdemClassifProcesso { get; set; }
        public short? NumAgenciaDepositaria { get; set; }
        public byte? NumDigitoAgenciaDepositaria { get; set; }
        public short? CodConvenioBb { get; set; }
        public virtual ICollection<FechamentoMovJec> FechamentoMovJec { get; set; }
    }
}