// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PerfilContext.Entities
{
    public partial class AcaLogUsuario
    {
        public string CodUsuario { get; set; }
        public string Operacao { get; set; }
        public DateTime DatLog { get; set; }
        public string NomeUsuarioA { get; set; }
        public string NomeUsuarioD { get; set; }
        public string SenhaA { get; set; }
        public string SenhaD { get; set; }
        public string PerfilA { get; set; }
        public string PerfilD { get; set; }
        public string IndCivelA { get; set; }
        public string IndCivelD { get; set; }
        public string IndTrabalhistaA { get; set; }
        public string IndTrabalhistaD { get; set; }
        public string IndRegulatorioA { get; set; }
        public string IndRegulatorioD { get; set; }
        public string IndTributarioA { get; set; }
        public string IndTributarioD { get; set; }
        public string IndControladoriaA { get; set; }
        public string IndControladoriaD { get; set; }
        public string IndUsuarioInternetA { get; set; }
        public string IndUsuarioInternetD { get; set; }
        public string IndAtivoA { get; set; }
        public string IndAtivoD { get; set; }
        public string IndBloqueadoA { get; set; }
        public string IndBloqueadoD { get; set; }
        public string IndMudarSenhaA { get; set; }
        public string IndMudarSenhaD { get; set; }
        public DateTime? DatValidadeSenhaA { get; set; }
        public DateTime? DatValidadeSenhaD { get; set; }
        public string CodUsuarioLog { get; set; }
        public string IndUsuarioInternet { get; set; }
        public string IndJuizadoA { get; set; }
        public string IndJuizadoD { get; set; }
        public string IndPerfilWebA { get; set; }
        public string IndPerfilWebD { get; set; }
        public string IndPrepostoA { get; set; }
        public string IndPrepostoD { get; set; }
        public string IndAutorizaServicoA { get; set; }
        public string IndAutorizaServicoD { get; set; }
        public DateTime DataOperacaoRetro { get; set; }
        public DateTime MesAnoCont { get; set; }
        public DateTime MesAnoContRetro { get; set; }
        public string UsrCodUsuarioOperRetro { get; set; }
        public string IndOperacaoWebRetro { get; set; }
        public string IndCivelEstrategicoA { get; set; }
        public string IndCivelEstrategicoD { get; set; }
        public DateTime? DataDesativacaoA { get; set; }
        public DateTime? DataDesativacaoD { get; set; }
        public string IndRestritoA { get; set; }
        public string IndRestritoD { get; set; }
        public short? AreaCodAreaJecA { get; set; }
        public short? AreaCodAreaJecD { get; set; }
        public string NomAreaJecA { get; set; }
        public string NomAreaJecD { get; set; }
        public byte? CodPrioridadeExecRelA { get; set; }
        public byte? CodPrioridadeExecRelD { get; set; }
        public string IndCriminalAdmA { get; set; }
        public string IndCriminalAdmD { get; set; }
        public string IndCriminalJudicialA { get; set; }
        public string IndCriminalJudicialD { get; set; }
        public string IndCivelAdmA { get; set; }
        public string IndCivelAdmD { get; set; }
        public string IndProconA { get; set; }
        public string IndProconD { get; set; }
        public string IndAutorizaServProconA { get; set; }
        public string IndAutorizaServProconD { get; set; }
        public string ObsUsuarioA { get; set; }
        public string ObsUsuarioD { get; set; }
        public string IndPexA { get; set; }
        public string IndPexD { get; set; }
        public string IndAdmAprovadorAcessosA { get; set; }
        public string IndAdmAprovadorAcessosD { get; set; }
        public string IndGestorAprovadorAcessosA { get; set; }
        public string IndGestorAprovadorAcessosD { get; set; }
        public string CodTipoUsuarioPerfilA { get; set; }
        public string CodTipoUsuarioPerfilD { get; set; }
        public string NumCpfA { get; set; }
        public string NumCpfD { get; set; }
        public decimal? IdBoA { get; set; }
        public decimal? IdBoD { get; set; }
        public string IndOperadorCadastroA { get; set; }
        public string IndOperadorCadastroD { get; set; }
        public string CodGestorDefaultA { get; set; }
        public string CodGestorDefaultD { get; set; }
        public string IndOperadorValidacaoJecA { get; set; }
        public string IndOperadorValidacaoJecD { get; set; }
        public string IndOperadorValidacaoCconsA { get; set; }
        public string IndOperadorValidacaoCconsD { get; set; }
        public decimal? CodOrigemUsuarioA { get; set; }
        public decimal? CodOrigemUsuarioD { get; set; }
        public string CodSituacaoUsuarioA { get; set; }
        public string CodSituacaoUsuarioD { get; set; }
        public string IndInativacaoManualA { get; set; }
        public string IndInativacaoManualD { get; set; }
        public string IndInativacaoAutomaticaA { get; set; }
        public string IndInativacaoAutomaticaD { get; set; }
        public string DscEmailA { get; set; }
        public string DscEmailD { get; set; }
    }
}