// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PerfilContext.Entities
{
    public partial class AcaUsuario
    {
        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string Perfil { get; set; }
        public string IndAtivo { get; set; }
        public string IndPerfilWeb { get; set; }
        public string IndRestrito { get; set; }
        public string CodTipoUsuarioPerfil { get; set; }
        public string CodGestorDefault { get; set; }
    }
}