// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Data;
using Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Data.Configurations
{
    public partial class GrupoJuizadoConfiguration : IEntityTypeConfiguration<GrupoJuizado>
    {
        public void Configure(EntityTypeBuilder<GrupoJuizado> entity)
        {
            entity.HasKey(e => e.CodGrupoJuizado);

            entity.ToTable("GRUPO_JUIZADO");

            entity.Property(e => e.CodGrupoJuizado)
                .HasPrecision(4)
                .HasColumnName("COD_GRUPO_JUIZADO");

            entity.Property(e => e.DscGrupoJuizado)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_GRUPO_JUIZADO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrupoJuizado> entity);
    }
}
