// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.StatusContatoContext.Entities
{
    public partial class LogStatusContato
    {
        public int? CodStatusContato { get; set; }
        public string Operacao { get; set; }
        public DateTime? DatLog { get; set; }
        public string CodUsuario { get; set; }
        public string DscStatusContatoA { get; set; }
        public string DscStatusContatoD { get; set; }
        public string IndContatoRealizadoA { get; set; }
        public string IndContatoRealizadoD { get; set; }
        public string IndAcordoRealizadoA { get; set; }
        public string IndAcordoRealizadoD { get; set; }
        public string IndAtivoA { get; set; }
        public string IndAtivoD { get; set; }
    }
}