// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Data;
using Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Data.Configurations
{
    public partial class ParteConfiguration : IEntityTypeConfiguration<Parte>
    {
        public void Configure(EntityTypeBuilder<Parte> entity)
        {
            entity.HasKey(e => e.CodParte);

            entity.ToTable("PARTE");

            entity.HasIndex(e => new { e.CodTipoParte, e.CodParte }, "IDX_PARTE_01_3CON");

            entity.HasIndex(e => new { e.CodTipoParte, e.NomParte }, "IDX_PARTE_05");

            entity.HasIndex(e => e.NomParte, "IDX_PARTE_07");

            entity.HasIndex(e => e.CodTipoParte, "PARTE_IX_01");

            entity.Property(e => e.CodParte)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE");

            entity.Property(e => e.CodTipoParte)
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_TIPO_PARTE")
                .IsFixedLength();

            entity.Property(e => e.NomParte)
                .HasMaxLength(400)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("NOM_PARTE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Parte> entity);
    }
}
