// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Data;
using Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Data.Configurations
{
    public partial class PrepostoConfiguration : IEntityTypeConfiguration<Preposto>
    {
        public void Configure(EntityTypeBuilder<Preposto> entity)
        {
            entity.HasKey(e => e.CodPreposto);

            entity.ToTable("PREPOSTO");

            entity.Property(e => e.CodPreposto)
                .HasPrecision(6)
                .ValueGeneratedNever()
                .HasColumnName("COD_PREPOSTO");

            entity.Property(e => e.IndPrepostoTrabalhista)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PREPOSTO_TRABALHISTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.NomPreposto)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("NOM_PREPOSTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Preposto> entity);
    }
}
