// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.RelatoriosContingenciaTrabalhistaContext.Data;
using Oi.Juridico.Contextos.RelatoriosContingenciaTrabalhistaContext.Entities;
using System;

namespace Oi.Juridico.Contextos.RelatoriosContingenciaTrabalhistaContext.Data.Configurations
{
    public partial class FechamentosProvisoesTrabConfiguration : IEntityTypeConfiguration<FechamentosProvisoesTrab>
    {
        public void Configure(EntityTypeBuilder<FechamentosProvisoesTrab> entity)
        {
            entity.ToTable("FECHAMENTOS_PROVISOES_TRAB");

            //entity.HasIndex(e => new { e.DataFechamento, e.EmpceCodEmpCentralizadora, e.NumMesesMediaHistorica, e.CodTipoOutlier }, "FPTR_UK_01")
            //    .IsUnique();

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.CodTipoOutlier)
                //.HasPrecision(2)
                .HasColumnName("COD_TIPO_OUTLIER")
                .HasDefaultValueSql("0                 ");

            entity.Property(e => e.DataFechamento)
                .HasColumnType("DATE")
                .HasColumnName("DATA_FECHAMENTO");

            entity.Property(e => e.DataGeracao)
                .HasColumnType("DATE")
                .HasColumnName("DATA_GERACAO");

            entity.Property(e => e.DataIndMensal)
                .HasColumnType("DATE")
                .HasColumnName("DATA_IND_MENSAL");

            entity.Property(e => e.EmpceCodEmpCentralizadora)
                //.HasPrecision(4)
                .HasColumnName("EMPCE_COD_EMP_CENTRALIZADORA");

            entity.Property(e => e.IndBaseGerada)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_BASE_GERADA")
                .HasDefaultValueSql("'N'	")
                .IsFixedLength(true);

            entity.Property(e => e.IndMensal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_MENSAL")
                .HasDefaultValueSql("'N'	")
                .IsFixedLength(true);

            entity.Property(e => e.IndPossuiHibrido)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_POSSUI_HIBRIDO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.NumMesesMediaHistorica)
                //.HasPrecision(3)
                .HasColumnName("NUM_MESES_MEDIA_HISTORICA");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.Property(e => e.ValAjusteDesvioPadrao)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("VAL_AJUSTE_DESVIO_PADRAO");

            entity.Property(e => e.ValPercentProcOutliers)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("VAL_PERCENT_PROC_OUTLIERS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FechamentosProvisoesTrab> entity);
    }
}
