// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContext.Data.Configurations
{
    public partial class AndamentoProcessoConfiguration : IEntityTypeConfiguration<AndamentoProcesso>
    {
        public void Configure(EntityTypeBuilder<AndamentoProcesso> entity)
        {
            entity.HasKey(e => new { e.CodProcesso, e.SeqAndamento });

            entity.ToTable("ANDAMENTO_PROCESSO");

            entity.HasIndex(e => new { e.CodEvento, e.CodDecisao }, "ANDPR_DECEV_FK_IX");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_PROCESSO");

            entity.Property(e => e.SeqAndamento)
                .HasPrecision(4)              
                .HasColumnName("SEQ_ANDAMENTO");

            entity.Property(e => e.CodAcao)
                .HasPrecision(4)            
                .HasColumnName("COD_ACAO");

            entity.Property(e => e.CodDecisao)
                .HasPrecision(2)          
                .HasColumnName("COD_DECISAO");

            entity.Property(e => e.CodEvento)
                .HasPrecision(4)             
                .HasColumnName("COD_EVENTO");

            entity.Property(e => e.DatEvento)
                .HasColumnType("DATE")           
                .HasColumnName("DAT_EVENTO");

            entity.Property(e => e.DataCriacao)
                .HasColumnType("DATE")   
                .HasColumnName("DATA_CRIACAO");

            entity.Property(e => e.DscComentario)
                .IsUnicode(false)
                .HasColumnName("DSC_COMENTARIO");

            entity.Property(e => e.DscObrigacaoFazer)
                .IsUnicode(false)
                .HasColumnName("DSC_OBRIGACAO_FAZER");

            entity.Property(e => e.DscObrigacaoPagar)
                .IsUnicode(false)
                .HasColumnName("DSC_OBRIGACAO_PAGAR");

            entity.Property(e => e.IndAcessoRestrito)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)   
                .HasColumnName("IND_ACESSO_RESTRITO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.NroEvento)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NRO_EVENTO");

            entity.HasOne(d => d.CodAcaoNavigation)
                .WithMany(p => p.AndamentoProcesso)
                .HasForeignKey(d => d.CodAcao)
                .HasConstraintName("FK_ACAO_ANDAMENTO_PROC");

            entity.HasOne(d => d.CodProcessoNavigation)
                .WithMany(p => p.AndamentoProcesso)
                .HasForeignKey(d => d.CodProcesso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROCESSO_ANDAMENTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AndamentoProcesso> entity);
    }
}
