// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContext.Data.Configurations
{
    public partial class BbNaturezasAcoesConfiguration : IEntityTypeConfiguration<BbNaturezasAcoes>
    {
        public void Configure(EntityTypeBuilder<BbNaturezasAcoes> entity)
        {
            entity.ToTable("BB_NATUREZAS_ACOES");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.Codigo)
                .HasPrecision(4)
                .HasColumnName("CODIGO");

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BbNaturezasAcoes> entity);
    }
}
