// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContext.Data.Configurations
{
    public partial class DeParaStatusAppPrepostoConfiguration : IEntityTypeConfiguration<DeParaStatusAppPreposto>
    {
        public void Configure(EntityTypeBuilder<DeParaStatusAppPreposto> entity)
        {
            entity.ToTable("DE_PARA_STATUS_APP_PREPOSTO");

            entity.HasIndex(e => new { e.StatusApp, e.SubstatusApp, e.StatusSisjur, e.CodTipoProcesso }, "DE_PARA_STATUS_APP_PREPOS_UK1")
                .IsUnique();

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.CodTipoProcesso)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_PROCESSO");

            entity.Property(e => e.CriarAudiencia)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("CRIAR_AUDIENCIA")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.StatusApp)
                .HasPrecision(4)
                .HasColumnName("STATUS_APP");

            entity.Property(e => e.StatusSisjur)
                .HasPrecision(4)
                .HasColumnName("STATUS_SISJUR");

            entity.Property(e => e.SubstatusApp)
                .HasPrecision(4)
                .HasColumnName("SUBSTATUS_APP");

            entity.HasOne(d => d.StatusAppNavigation)
                .WithMany(p => p.DeParaStatusAppPrepostoStatusAppNavigation)
                .HasForeignKey(d => d.StatusApp)
                .HasConstraintName("DE_PARA_STATUS_APP_PREPOS_FK1");

            entity.HasOne(d => d.StatusSisjurNavigation)
                .WithMany(p => p.DeParaStatusAppPreposto)
                .HasForeignKey(d => d.StatusSisjur)
                .HasConstraintName("DE_PARA_STATUS_APP_PREPOS_FK3");

            entity.HasOne(d => d.SubstatusAppNavigation)
                .WithMany(p => p.DeParaStatusAppPrepostoSubstatusAppNavigation)
                .HasForeignKey(d => d.SubstatusApp)
                .HasConstraintName("DE_PARA_STATUS_APP_PREPOS_FK2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DeParaStatusAppPreposto> entity);
    }
}
