// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContext.Data.Configurations
{
    public partial class MigAcaoConfiguration : IEntityTypeConfiguration<MigAcao>
    {
        public void Configure(EntityTypeBuilder<MigAcao> entity)
        {
            entity.HasKey(e => new { e.CodAcaoCivel, e.CodAcaoCivelEstrat })
                .HasName("MACAO_PK");

            entity.ToTable("MIG_ACAO");

            entity.Property(e => e.CodAcaoCivel)
                .HasPrecision(4)
                .HasColumnName("COD_ACAO_CIVEL");

            entity.Property(e => e.CodAcaoCivelEstrat)
                .HasPrecision(4)
                .HasColumnName("COD_ACAO_CIVEL_ESTRAT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MigAcao> entity);
    }
}
