// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Entities
{
    public partial class AgendExpCargaComp
    {
        public decimal Id { get; set; }
        public decimal? TipoProcesso { get; set; }
        public decimal? StatusParcela { get; set; }
        public DateTime? VencimentoIni { get; set; }
        public DateTime? VencimentoFim { get; set; }
        public decimal? CargaId { get; set; }
        public decimal? AgendamentoId { get; set; }
        public string? NroProcesso { get; set; }
        public decimal? TpPesqProcesso { get; set; }
        public decimal? TpPesqPartCred { get; set; }
        public string? Documento { get; set; }
        public string? Nome { get; set; }
        public DateTime? DatSolicitacao { get; set; }
        public string? UsrSolicitacao { get; set; }
        public decimal Status { get; set; }
        public DateTime? DatIniExec { get; set; }
        public DateTime? DatFimExec { get; set; }
        public string? MensagemErroTrace { get; set; }
        public string? NomArqGerado { get; set; }
        public decimal? ClasseCredito { get; set; }
    }
}