// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Entities
{
    public partial class ClasseCredito
    {
        public decimal CodClasseCredito { get; set; }
        public string? DscClasseCredito { get; set; }
    }
}