// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Entities
{
    public partial class Processo
    {
        public Processo()
        {
            CargaCompromisso = new HashSet<CargaCompromisso>();
            CargaCompromissoParcela = new HashSet<CargaCompromissoParcela>();
            InverseCodProcessoAdmNavigation = new HashSet<Processo>();
            LancamentoProcesso = new HashSet<LancamentoProcesso>();
        }

        public int CodProcesso { get; set; }
        public byte CodTipoProcesso { get; set; }
        public string? IndProcessoAtivo { get; set; }
        public string? NroProcessoCartorio { get; set; }
        public int? CodProfissional { get; set; }
        public short? CodAdvogado { get; set; }
        public int? CodEscritorioAcompanhante { get; set; }
        public int? CodContador { get; set; }
        public string? CodResponsavelInterno { get; set; }
        public short? CodAcao { get; set; }
        public short? CodProcedimento { get; set; }
        public string IndPrioritaria { get; set; } = null!;
        public short? CodAssunto { get; set; }
        public string? CodEstado { get; set; }
        public short? CodComarca { get; set; }
        public short? CodVara { get; set; }
        public short? CodTipoVara { get; set; }
        public short? CodClienteInterno { get; set; }
        public long? CodParteEmpresa { get; set; }
        public long? CodParteOrgao { get; set; }
        public short? CodCompetencia { get; set; }
        public int? NroPasta { get; set; }
        public decimal? ValCausa { get; set; }
        public string? CodRiscoPerda { get; set; }
        public decimal? ValEconomico { get; set; }
        public decimal? ValEconomicoCorrigido { get; set; }
        public decimal? ValRiscoPerda { get; set; }
        public decimal? ValRiscoPerdaCorrigido { get; set; }
        public short? CodTipoPenalidade { get; set; }
        public decimal? ValMulta { get; set; }
        public decimal? ValMultaCorrigido { get; set; }
        public DateTime? DatBaseMulta { get; set; }
        public string? DscFianca { get; set; }
        public string? DscHipoteca { get; set; }
        public string? DscDepositoCaucao { get; set; }
        public string? DscPenhora { get; set; }
        public DateTime? DatFinalizacao { get; set; }
        public string? CodDecisaoFinalizacao { get; set; }
        public DateTime? DatContratacao { get; set; }
        public byte? CodTipoContratacao { get; set; }
        public DateTime? DatDistribuicao { get; set; }
        public string? IndChecado { get; set; }
        public DateTime? DatChecado { get; set; }
        public string? Observacao { get; set; }
        public string? Comentario { get; set; }
        public DateTime? DatUltAtualizacao { get; set; }
        public string? CodUsuarioUltAlteracao { get; set; }
        public string? IndUsuarioInternet { get; set; }
        public string? CodUsuarioInternet { get; set; }
        public short? SeqPagamento { get; set; }
        public short? SeqValor { get; set; }
        public short? SeqObservacao { get; set; }
        public short? SeqAudiencia { get; set; }
        public short? SeqAndamento { get; set; }
        public short? SeqFase { get; set; }
        public short? SeqPrazo { get; set; }
        public int? CodProcessoAdm { get; set; }
        public DateTime? DatFinalizacaoContabil { get; set; }
        public short? CodMunicipio { get; set; }
        public short? SeqValorObjeto { get; set; }
        public short? SeqPagObjeto { get; set; }
        public int? SeqMovimentacao { get; set; }
        public short? SeqPendencia { get; set; }
        public decimal? PerReducao { get; set; }
        public short? CodTipoPenalidadePrev { get; set; }
        public DateTime? DatPrev { get; set; }
        public decimal? ValMultaPrev { get; set; }
        public string? CodRiscoPerdaPrev { get; set; }
        public DateTime? DatDecisaoRecurso { get; set; }
        public DateTime? DatVencMulta { get; set; }
        public decimal? ValMultaInicial { get; set; }
        public decimal? ValMultaInicialCorrigida { get; set; }
        public decimal? ValMultaPosPagamento { get; set; }
        public long? CodEstabelecimento { get; set; }
        public short? CodRegional { get; set; }
        public short SeqLinha { get; set; }
        public DateTime? DatAberturaProc { get; set; }
        public DateTime? DatRecebimentoProc { get; set; }
        public short SeqLancamento { get; set; }
        public DateTime? DatEnvioEscritorio { get; set; }
        public int? CodExpressinho { get; set; }
        public decimal ValCausaEmSm { get; set; }
        public string? ObsExclusao { get; set; }
        public short SeqServico { get; set; }
        public short SeqContato { get; set; }
        public short SeqApuracao { get; set; }
        public short SeqApuracaoCdebito { get; set; }
        public short SeqApuracaoReparo { get; set; }
        public short SeqApuracaoBloqueio { get; set; }
        public short SeqApuracaoCconta { get; set; }
        public short SeqApuracaoMpulso { get; set; }
        public short SeqApuracaoCcobranca { get; set; }
        public short SeqApuracaoPcredito { get; set; }
        public string? EndPaginaConsulta { get; set; }
        public DateTime? DataFinalizacaoTribunal { get; set; }
        public int? CodDocumentoDigitalizado { get; set; }
        public string? IndEmpresaCredoraDevedora { get; set; }
        public DateTime? DataCadastro { get; set; }
        public decimal QteSalarioMinimoInicial { get; set; }
        public decimal QteSalarioMinimoAtual { get; set; }
        public string? NumPastaEscritorio { get; set; }
        public string? CodRiscoPerdaAvaliado { get; set; }
        public DateTime? DataAvaliacaoRiscoPerda { get; set; }
        public string? DescMotivoAvaliacaoRisco { get; set; }
        public string IndValorObrigatorio { get; set; } = null!;
        public decimal PercHonorariosSucumbencia { get; set; }
        public decimal ValorJurosInicial { get; set; }
        public decimal ValorJurosAtual { get; set; }
        public decimal ValorSalarioMinimoInicial { get; set; }
        public decimal ValorSalarioMinimoAtual { get; set; }
        public decimal ValorHonorSucumbPrincipal { get; set; }
        public decimal ValorHonorSucumbCorrJuros { get; set; }
        public string? CodClassificacaoProcesso { get; set; }
        public string IndValidado { get; set; } = null!;
        public DateTime? DataPublicacaoMulta { get; set; }
        public string IndSimplificado { get; set; } = null!;
        public short? EsfCodEsfera { get; set; }
        public short? NumCaf { get; set; }
        public string? IndProprioTerceiro { get; set; }
        public string? IndConsiderarProvisao { get; set; }
        public string UsrCodUsuarioCadastro { get; set; } = null!;
        public DateTime? DataUltAtuEscritorio { get; set; }
        public string? UsrCodUsuarioUltAtuEscrit { get; set; }
        public DateTime? DataExcLogica { get; set; }
        public string? UsrCodUsuarioExcLogica { get; set; }
        public string IndApuracao { get; set; } = null!;
        public DateTime? DataApuracao { get; set; }
        public string? UsrCodUsuarioApuracao { get; set; }
        public decimal? FtgerIdFatoGerador { get; set; }
        public decimal? ArenvIdAreaEnvolvida { get; set; }
        public DateTime? DataFatoGerador { get; set; }
        public string? ObsFatoGerador { get; set; }
        public decimal? IdMotivoAlteracaoEscritorio { get; set; }
        public string? ComentarioAltEscritorio { get; set; }
        public decimal? StpprIdSubtipoProcesso { get; set; }
        public decimal? ReorgIdRepresentanteOrgao { get; set; }
        public string? CodCriticidade { get; set; }
        public string IndEstratificado { get; set; } = null!;
        public byte? CodFarol { get; set; }
        public string? NumeroProcSemFormatacao { get; set; }
        public decimal? IdUltMovimentacaoPasta { get; set; }
        public string IndMigrado { get; set; } = null!;
        public decimal? CodMigracaoSistema { get; set; }
        public decimal? IdCamara { get; set; }
        public decimal? IdTurmaRecursal { get; set; }
        public decimal? IdFaseProcessual { get; set; }
        public DateTime? DataTransitoJulgado { get; set; }
        public string? DescApuracaoContrato { get; set; }
        public string? NumProcessoAntigo { get; set; }
        public string IndTributarioPrincipal { get; set; } = null!;
        public decimal? IdBo { get; set; }
        public DateTime? DatEnvioValidacao { get; set; }
        public string? CodUsuarioEnvioValidacao { get; set; }
        public string? CodUsuarioValidacao { get; set; }
        public DateTime? DatValidacao { get; set; }
        public string? IndNroProcessoDivergente { get; set; }
        public string? IndComarcaDivergente { get; set; }
        public string? IndJuizadoVaraDivergente { get; set; }
        public string? IndEmpresaGrupoDivergente { get; set; }
        public string? IndDatAudienciaDivergente { get; set; }
        public string? IndHoraAudienciaDivergente { get; set; }
        public string? IndEscritorioDivergente { get; set; }
        public decimal? IdComplAreaEnvolvida { get; set; }
        public string? CodUsuarioFinalizacao { get; set; }
        public decimal? IdTese { get; set; }
        public DateTime? DatUltFinalizacao { get; set; }
        public DateTime? DatUltFinalizacaoContabil { get; set; }
        public short? SeqDesdobramento { get; set; }
        public int? CodEscritorioAdverso { get; set; }
        public string? IndRecuperacaoJudicial { get; set; }
        public short? SeqCompromisso { get; set; }
        public string? IndConsideraCalculoMedia { get; set; }
        public DateTime? DatConciliacao { get; set; }
        public string? IndAutorInfServicoPrestado { get; set; }
        public string? ComentarioFinalizacao { get; set; }
        public byte? PrePos { get; set; }
        public decimal? ValRiscoPerdaPre { get; set; }
        public decimal? ValRiscoPerdaPos { get; set; }
        public decimal? ValRiscoPerCorPre { get; set; }
        public decimal? ValRiscoPerCorPos { get; set; }
        public decimal? ValorJurosAtualPre { get; set; }
        public decimal? ValorJurosAtualPos { get; set; }
        public decimal? ValorHonorSucumbJuros { get; set; }
        public decimal? ValorHonorSucumbCorr { get; set; }
        public string? IndMediacao { get; set; }
        public string? CodPrescricao { get; set; }
        public decimal? ValSaldoBaseProvMediacao { get; set; }
        public byte? CodClassificacaoClosing { get; set; }
        public decimal? PerResponsOi { get; set; }
        public string? IndHaircut { get; set; }
        public byte? CodRemuneracaoEscritorio { get; set; }
        public short? CodTipoContratoEscritorio { get; set; }
        public byte? CodClassfClosingClientco { get; set; }

        public virtual Processo? CodProcessoAdmNavigation { get; set; }
        public virtual ICollection<CargaCompromisso> CargaCompromisso { get; set; }
        public virtual ICollection<CargaCompromissoParcela> CargaCompromissoParcela { get; set; }
        public virtual ICollection<Processo> InverseCodProcessoAdmNavigation { get; set; }
        public virtual ICollection<LancamentoProcesso> LancamentoProcesso { get; set; }
    }
}