// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.AgendamentoCalculoVEPContext.Data;
using Oi.Juridico.Contextos.V2.AgendamentoCalculoVEPContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AgendamentoCalculoVEPContext.Data.Configurations
{
    public partial class AgendCalcVepConfiguration : IEntityTypeConfiguration<AgendCalcVep>
    {
        public void Configure(EntityTypeBuilder<AgendCalcVep> entity)
        {
            entity.HasKey(e => e.CodAgendCalcVep);

            entity.ToTable("AGEND_CALC_VEP");

            entity.Property(e => e.CodAgendCalcVep)
                .HasPrecision(10)
                .HasColumnName("COD_AGEND_CALC_VEP");

            entity.Property(e => e.DatAgendamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO");

            entity.Property(e => e.DatEspecifica)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ESPECIFICA");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.DatProximaExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_PROXIMA_EXECUCAO");

            entity.Property(e => e.DatUltimaExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULTIMA_EXECUCAO");

            entity.Property(e => e.DiaDoMes)
                .HasPrecision(2)
                .HasColumnName("DIA_DO_MES");

            entity.Property(e => e.IndUltimoDiaDoMes)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ULTIMO_DIA_DO_MES")
                .IsFixedLength();

            entity.Property(e => e.NomArquivoGerado)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("NOM_ARQUIVO_GERADO");

            entity.Property(e => e.NumMeses)
                .HasPrecision(2)
                .HasColumnName("NUM_MESES");

            entity.Property(e => e.PeriodicidadeExecucao)
                .HasPrecision(2)
                .HasColumnName("PERIODICIDADE_EXECUCAO");

            entity.Property(e => e.Status)
                .HasPrecision(2)
                .HasColumnName("STATUS");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendCalcVep> entity);
    }
}
