// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.RelatorioMovimentacoesPexContext.Data;
using Oi.Juridico.Contextos.RelatorioMovimentacoesPexContext.Entities;
using System;


namespace Oi.Juridico.Contextos.RelatorioMovimentacoesPexContext.Data.Configurations
{
    public partial class AgendMovimentacaoPexConfiguration : IEntityTypeConfiguration<AgendMovimentacaoPex>
    {
        public void Configure(EntityTypeBuilder<AgendMovimentacaoPex> entity)
        {
            entity.ToTable("AGEND_MOVIMENTACAO_PEX");

            entity.HasKey(x => x.Id)
                .HasName("AMP_PK");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.FechamentoPexMediaFimCodSolic)
                .HasColumnName("COD_SOLIC_FECHAMENTO_FIM");

            entity.Property(e => e.FechamentoPexMediaIniCodSolic)
                .HasColumnName("COD_SOLIC_FECHAMENTO_INI");

            entity.Property(e => e.DatAgendamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO");

            entity.Property(e => e.DatFechamentoFim)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FECHAMENTO_FIM");

            entity.Property(e => e.DatFechamentoIni)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FECHAMENTO_INI");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.MsgErro)
                .HasColumnType("CLOB")
                .HasColumnName("MSG_ERRO");

            entity.Property(e => e.Status)
                .HasColumnName("STATUS");

            entity.Property(e => e.UsuarioId)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.HasOne(e => e.Usuario).WithOne();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendMovimentacaoPex> entity);
    }
}
