export const ItensMenuLogJec = [
    {
        id: 1,
        titulo: 'Dados Gerais',
        icone: 'dadosGerais',
        nav: 'dadosGerais',
        selecionado: true,
    },
    {
        id: 2,
        titulo: 'Pedidos',
        icone: 'pedidos',
        nav: 'pedidos',
        selecionado: false,
    },
    {
        id: 3,
        titulo: 'Partes',
        icone: 'partes',
        nav: 'partes',
        selecionado: false,
    },
    {
        id: 4,
        titulo: 'Advogados dos Autores',
        icone: 'adv-autores',
        nav: 'adv-autores',
        selecionado: false,
    }, 
    {
        id: 5,
        titulo: 'Linhas',
        icone: 'linhas',
        nav: 'linhas',
        selecionado: false,
    }, 
    {
        id: 6,
        titulo: 'Apurações',
        icone: 'apuracoes',
        nav: 'apuracoes',
        subMenu: false,
        selecionado: false,
        subItens: [
            {
                id: 6.1,
                titulo: 'Dossiês',
                selecionado: false,
            },
            {
                id: 6.2,
                titulo: 'Bloqueios',
                selecionado: false,
            },
            {
                id: 6.3,
                titulo: 'Reparos',
                selecionado: false,
            },
            {
                id: 6.4,
                titulo: 'Contestações',
                selecionado: false,
            },
            {
                id: 6.5,
                titulo: 'Contas em Débito',
                selecionado: false,
            },
            {
                id: 6.6,
                titulo: 'Cartas de Cobrança',
                selecionado: false,
            },
            {
                id: 6.7,
                titulo: 'Medições de Pulso',
                selecionado: false,
            },
            {
                id: 6.8,
                titulo: 'Proteções ao Crédito',
                selecionado: false,
            },
        ]
    },
    {
        id: 7,
        titulo: 'Andamentos',
        icone: 'andamentos',
        nav: 'andamentos',
        selecionado: false,
    }, 
    {
        id: 8,
        titulo: 'Decisões sobre Pedidos',
        icone: 'decisoes-pedidos',
        nav: 'decisoes-pedidos',
        selecionado: false,
    },
    {
        id: 9,
        titulo: 'Observações',
        icone: 'observacoes',
        nav: 'observacoes',
        selecionado: false,
    },
    {
        id: 10,
        titulo: 'Motivações',
        icone: 'motivacoes',
        nav: 'motivacoes',
        selecionado: false,        
    },
    {
        id: 11,
        titulo: 'Audiências',
        icone: 'audiencias',
        nav: 'audiencias',
        selecionado: false,        
    },
    {
        id: 12,
        titulo: 'Acordos de uma Audiência',
        icone: 'acordos-audiencia',
        nav: 'acordos-audiencia',
        selecionado: false,        
    },
    {
        id: 13,
        titulo: 'Propostas de Acordo de uma Audiência',
        icone: 'proposta-acordo-audiencia',
        nav: 'proposta-acordo-audiencia',
        selecionado: false,        
    },
    {
        id: 14,
        titulo: 'Prazos',
        icone: 'prazos',
        nav: 'prazos',
        selecionado: false,        
    },
    {
        id: 15,
        titulo: 'Serviços',
        icone: 'servicos',
        nav: 'servicos',
        selecionado: false,        
    },
    {
        id: 16,
        titulo: 'Andamento dos Serviços',
        icone: 'andamento-servicos',
        nav: 'andamento-servicos',
        selecionado: false,        
    },
    {
        id: 17,
        titulo: 'Contatos',
        icone: 'contatos',
        nav: 'contatos',
        selecionado: false,        
    },
    {
        id: 18,
        titulo: 'Propostas de um Contato',
        icone: 'propostas-contato',
        nav: 'propostas-contato',
        selecionado: false,        
    },
    {
        id: 19,
        titulo: 'Serviços Gratuitos',
        icone: 'servicos-gratuitos',
        nav: 'servicos-gratuitos',
        selecionado: false,        
    },
    {
        id: 20,
        titulo: 'Lançamentos',
        icone: 'lancamentos',
        nav: 'lancamentos',
        selecionado: false,
        subMenu: false,
        subItens: [
            {
                id: 20.1,
                titulo: 'Garantias',
                selecionado: false,
            },
            {
                id: 20.2,
                titulo: 'Despesas Judiciais',
                selecionado: false,
            },
            {
                id: 20.3,
                titulo: 'Pagamentos',
                selecionado: false,
            },
        ]
    },
    {
        id: 21,
        titulo: 'Lotes',
        icone: 'lotes',
        nav: 'lotes',
        selecionado: false,
    },
];