export const ItensMenuLogTrinutarioJudicial = [
    {
        id: 1,
        titulo: 'Dados Gerais',
        icone: 'dadosGerais',
        nav: 'dadosGerais',
        selecionado: true,
    },
    {
        id: 2,
        titulo: 'Partes',
        icone: 'partes',
        nav: 'partes',
        selecionado: false,
    }, 
    {
        id: 3,
        titulo: 'Andamentos',
        icone: 'andamentos',
        nav: 'andamentos',
        selecionado: false,
    }, 
    {
        id: 4,
        titulo: 'Observações',
        icone: 'observacoes',
        nav: 'observacoes',
        selecionado: false,
    }, 
    {
        id: 5,
        titulo: 'Audiências',
        icone: 'audiencias',
        nav: 'audiencias',
        selecionado: false,
    },
    {
        id: 6,
        titulo: 'Prazos',
        icone: 'prazos',
        nav: 'prazos',
        selecionado: false,        
    },
    {
        id: 7,
        titulo: 'Lançamentos',
        icone: 'lancamentos',
        nav: 'lancamentos',
        selecionado: false,
        subMenu: true,
        subItens: [
            {
                id: 7.1,
                titulo: 'Garantias',
                selecionado: false,
            },
            {
                id: 7.2,
                titulo: 'Despesas Judiciais',
                selecionado: false,
            },
            {
                id: 7.3,
                titulo: 'Honorários',
                selecionado: false,
            },
            {
                id: 7.4,
                titulo: 'Pagamentos',
                selecionado: false,
            },
        ]
    },
    {
        id: 8,
        titulo: 'Composição de \nPagamentos',
        icone: 'comp-pagamentos',
        nav: 'comp-pagamentos',
        selecionado: false,
    },
    {
        id: 9,
        titulo: 'Objetos',
        icone: 'objetos',
        nav: 'objetos',
        selecionado: false,
    },
    {
        id: 10,
        titulo: 'Decisões por Objeto/ \nPeríodo Infração',
        icone: 'decisoes-objetos',
        nav: 'decisoes-objetos',
        selecionado: false,
    },
    {
        id: 11,
        titulo: 'Valores por Objeto/ \nPeríodo Infração',
        icone: 'valores-objeto',
        nav: 'valores-objeto',
        selecionado: false,
    },
    {
        id: 12,
        titulo: 'Pendências',
        icone: 'pendencias',
        nav: 'pendencias',
        selecionado: false,
    },
    {
        id: 13,
        titulo: 'Processos Incidentes',
        icone: 'processos-incidentes',
        nav: 'processos-incidentes',
        selecionado: false,
    },
];