// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsDashboardConfiguration : IEntityTypeConfiguration<EsDashboard>
    {
        public void Configure(EntityTypeBuilder<EsDashboard> entity)
        {
            entity.HasKey(e => e.IdEsDashboard)
                .HasName("ES_DASHBOARD_PK");

            entity.ToTable("ES_DASHBOARD");

            entity.HasIndex(e => new { e.DatPeriodoVigente, e.IdEsEmpresaAgrupadora, e.CodEstado }, "ES_DASHBOARD_UK")
                .IsUnique();

            entity.Property(e => e.IdEsDashboard)
                .HasPrecision(18)
                .HasColumnName("ID_ES_DASHBOARD");

            entity.Property(e => e.CodEstado)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_ESTADO");

            entity.Property(e => e.DatPeriodoVigente)
                .HasColumnType("DATE")
                .HasColumnName("DAT_PERIODO_VIGENTE");

            entity.Property(e => e.DatUltimaAtualizacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULTIMA_ATUALIZACAO");

            entity.Property(e => e.IdEsEmpresaAgrupadora)
                .HasPrecision(5)
                .HasColumnName("ID_ES_EMPRESA_AGRUPADORA");

            entity.Property(e => e.NumSlaAguardRetorno)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_AGUARD_RETORNO");

            entity.Property(e => e.NumSlaNaoAnalisado)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_NAO_ANALISADO");

            entity.Property(e => e.NumSlaNaoIniciados)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_NAO_INICIADOS");

            entity.Property(e => e.NumSlaRascunhoCon)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_RASCUNHO_CON");

            entity.Property(e => e.NumSlaRascunhoEnv)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_RASCUNHO_ENV");

            entity.Property(e => e.NumSlaRascunhoEsc)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_RASCUNHO_ESC");

            entity.Property(e => e.NumSlaRetornoCritica)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_RETORNO_CRITICA");

            entity.Property(e => e.NumSlaSemRecibo)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_SEM_RECIBO");

            entity.Property(e => e.NumSlaVencendo)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_VENCENDO");

            entity.Property(e => e.NumSlaVencidos)
                .HasPrecision(5)
                .HasColumnName("NUM_SLA_VENCIDOS");

            entity.Property(e => e.NumTotEnvAguardRetorno)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_ENV_AGUARD_RETORNO");

            entity.Property(e => e.NumTotEnvRetornoOk)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_ENV_RETORNO_OK");

            entity.Property(e => e.NumTotEnvSemRecibo)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_ENV_SEM_RECIBO");

            entity.Property(e => e.NumTotEnviados)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_ENVIADOS");

            entity.Property(e => e.NumTotExcluidos)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_EXCLUIDOS");

            entity.Property(e => e.NumTotPendNaoAnalisados)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_NAO_ANALISADOS");

            entity.Property(e => e.NumTotPendNaoIniciados)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_NAO_INICIADOS");

            entity.Property(e => e.NumTotPendRascunhoCont)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_RASCUNHO_CONT");

            entity.Property(e => e.NumTotPendRascunhoEnv)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_RASCUNHO_ENV");

            entity.Property(e => e.NumTotPendRascunhoEsc)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_RASCUNHO_ESC");

            entity.Property(e => e.NumTotPendRetornoCritica)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PEND_RETORNO_CRITICA");

            entity.Property(e => e.NumTotPendentes)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_PENDENTES");

            entity.Property(e => e.NumTotRetificados)
                .HasPrecision(10)
                .HasColumnName("NUM_TOT_RETIFICADOS");

            entity.Property(e => e.TipoPrazoSlaVencendo)
                .HasPrecision(1)
                .HasColumnName("TIPO_PRAZO_SLA_VENCENDO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsDashboard> entity);
    }
}
