// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2501InfodepConfiguration : IEntityTypeConfiguration<EsF2501Infodep>
    {
        public void Configure(EntityTypeBuilder<EsF2501Infodep> entity)
        {
            entity.HasKey(e => e.IdEsF2501Infodep)
                .HasName("ES_F2501_INFODEP_PK");

            entity.ToTable("ES_F2501_INFODEP");

            entity.Property(e => e.IdEsF2501Infodep)
                .HasColumnType("NUMBER(15,2)")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID_ES_F2501_INFODEP");

            entity.Property(e => e.IdEsF2501)
                .HasPrecision(10)
                .HasColumnName("ID_ES_F2501");

            entity.Property(e => e.InfodepCpfdep)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("INFODEP_CPFDEP");

            entity.Property(e => e.InfodepDepirrf)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("INFODEP_DEPIRRF")
                .IsFixedLength();

            entity.Property(e => e.InfodepDescrdep)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("INFODEP_DESCRDEP");

            entity.Property(e => e.InfodepDtnascto)
                .HasColumnType("DATE")
                .HasColumnName("INFODEP_DTNASCTO");

            entity.Property(e => e.InfodepNome)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("INFODEP_NOME");

            entity.Property(e => e.InfodepTpdep)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("INFODEP_TPDEP");

            entity.Property(e => e.LogCodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.HasOne(d => d.IdEsF2501Navigation)
                .WithMany(p => p.EsF2501Infodep)
                .HasForeignKey(d => d.IdEsF2501)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ES_F2501_INFODEP_FK1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2501Infodep> entity);
    }
}
