// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2500InfointermConfiguration : IEntityTypeConfiguration<EsF2500Infointerm>
    {
        public void Configure(EntityTypeBuilder<EsF2500Infointerm> entity)
        {
            entity.HasKey(e => e.IdEsF2500Infointerm)
                .HasName("ES_F2500_INFOINTERM_PK");

            entity.ToTable("ES_F2500_INFOINTERM");

            entity.Property(e => e.IdEsF2500Infointerm)
                .ValueGeneratedOnAdd()
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2500_INFOINTERM");

            entity.Property(e => e.IdEsF2500Ideperiodo)
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2500_IDEPERIODO");

            entity.Property(e => e.InfointermDia)
                .HasPrecision(2)
                .HasColumnName("INFOINTERM_DIA");

            entity.Property(e => e.InfointermHrstrab)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("INFOINTERM_HRSTRAB");

            entity.Property(e => e.LogCodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.HasOne(d => d.IdEsF2500IdeperiodoNavigation)
                .WithMany(p => p.EsF2500Infointerm)
                .HasForeignKey(d => d.IdEsF2500Ideperiodo)
                .HasConstraintName("ES_F2500_INFOINTERM_FK1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2500Infointerm> entity);
    }
}
