// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2500DependenteConfiguration : IEntityTypeConfiguration<EsF2500Dependente>
    {
        public void Configure(EntityTypeBuilder<EsF2500Dependente> entity)
        {
            entity.HasKey(e => e.IdEsF2500Dependente)
                .HasName("PK_ES_F2500_DEPENDENTE_ID_ES_F");

            entity.ToTable("ES_F2500_DEPENDENTE");

            entity.HasIndex(e => new { e.IdF2500, e.DependenteCpfdep }, "KEY_ES_F2500_DEPENDENTE")
                .IsUnique();

            entity.Property(e => e.IdEsF2500Dependente)
                .ValueGeneratedOnAdd()
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2500_DEPENDENTE");

            entity.Property(e => e.DependenteCpfdep)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("DEPENDENTE_CPFDEP");

            entity.Property(e => e.DependenteDescdep)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("DEPENDENTE_DESCDEP");

            entity.Property(e => e.DependenteTpdep)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("DEPENDENTE_TPDEP");

            entity.Property(e => e.IdF2500)
                .HasPrecision(10)
                .HasColumnName("ID_F2500");

            entity.Property(e => e.LogCodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.HasOne(d => d.IdF2500Navigation)
                .WithMany(p => p.EsF2500Dependente)
                .HasForeignKey(d => d.IdF2500)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_F2500_DEPENDENTE_ID_F250");

            entity.HasOne(d => d.LogCodUsuarioNavigation)
                .WithMany(p => p.EsF2500Dependente)
                .HasForeignKey(d => d.LogCodUsuario)
                .HasConstraintName("FK_ES_F2500_DEPENDENTE_LOG_COD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2500Dependente> entity);
    }
}
