// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2500UniccontrConfiguration : IEntityTypeConfiguration<EsF2500Uniccontr>
    {
        public void Configure(EntityTypeBuilder<EsF2500Uniccontr> entity)
        {
            entity.HasKey(e => e.IdEsF2500Uniccontr);

            entity.ToTable("ES_F2500_UNICCONTR");

            entity.Property(e => e.IdEsF2500Uniccontr)
                .ValueGeneratedOnAdd()
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2500_UNICCONTR");

            entity.Property(e => e.IdEsF2500Infocontrato)
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2500_INFOCONTRATO");

            entity.Property(e => e.LogCodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.Property(e => e.UniccontrCodcateg)
                .HasPrecision(5)
                .HasColumnName("UNICCONTR_CODCATEG");

            entity.Property(e => e.UniccontrDtinicio)
                .HasColumnType("DATE")
                .HasColumnName("UNICCONTR_DTINICIO");

            entity.Property(e => e.UniccontrMatunic)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("UNICCONTR_MATUNIC");

            entity.HasOne(d => d.IdEsF2500InfocontratoNavigation)
                .WithMany(p => p.EsF2500Uniccontr)
                .HasForeignKey(d => d.IdEsF2500Infocontrato)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_F2500_UNICCONTR_CONTR");

            entity.HasOne(d => d.LogCodUsuarioNavigation)
                .WithMany(p => p.EsF2500Uniccontr)
                .HasForeignKey(d => d.LogCodUsuario)
                .HasConstraintName("FK_ES_F2500_UNICCONTR_LOG_COD_");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2500Uniccontr> entity);
    }
}
