// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2501BenefpenConfiguration : IEntityTypeConfiguration<EsF2501Benefpen>
    {
        public void Configure(EntityTypeBuilder<EsF2501Benefpen> entity)
        {
            entity.HasKey(e => e.IdEsF2501Benefpen)
                .HasName("ES_F2501_BENEFPEN_PK");

            entity.ToTable("ES_F2501_BENEFPEN");

            entity.Property(e => e.IdEsF2501Benefpen)
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2501_BENEFPEN");

            entity.Property(e => e.BenefpenCpfdep)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("BENEFPEN_CPFDEP");

            entity.Property(e => e.BenefpenVlrdepensusp)
                .HasColumnType("NUMBER(14,2)")
                .HasColumnName("BENEFPEN_VLRDEPENSUSP");

            entity.Property(e => e.IdEsF2501Dedsusp)
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2501_DEDSUSP");

            entity.Property(e => e.LogCodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.HasOne(d => d.IdEsF2501DedsuspNavigation)
                .WithMany(p => p.EsF2501Benefpen)
                .HasForeignKey(d => d.IdEsF2501Dedsusp)
                .HasConstraintName("ES_F2501_BENEFPEN_FK1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2501Benefpen> entity);
    }
}
