// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2501DeddepenConfiguration : IEntityTypeConfiguration<EsF2501Deddepen>
    {
        public void Configure(EntityTypeBuilder<EsF2501Deddepen> entity)
        {
            entity.HasKey(e => e.IdEsF2501Deddepen)
                .HasName("ES_F2501_DEDDEPEN_PK");

            entity.ToTable("ES_F2501_DEDDEPEN");

            entity.Property(e => e.IdEsF2501Deddepen)
                .ValueGeneratedOnAdd()
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2501_DEDDEPEN");

            entity.Property(e => e.DeddepenCpfdep)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("DEDDEPEN_CPFDEP");

            entity.Property(e => e.DeddepenTprend)
                .HasPrecision(2)
                .HasColumnName("DEDDEPEN_TPREND");

            entity.Property(e => e.DeddepenVlrdeducao)
                .HasColumnType("NUMBER(12,2)")
                .HasColumnName("DEDDEPEN_VLRDEDUCAO");

            entity.Property(e => e.IdEsF2501Infocrirrf)
                .HasPrecision(15)
                .HasColumnName("ID_ES_F2501_INFOCRIRRF");

            entity.Property(e => e.LogCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.HasOne(d => d.IdEsF2501InfocrirrfNavigation)
                .WithMany(p => p.EsF2501Deddepen)
                .HasForeignKey(d => d.IdEsF2501Infocrirrf)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ES_F2501_DEDDEPEN_FK1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2501Deddepen> entity);
    }
}
