// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsF2500Configuration : IEntityTypeConfiguration<EsF2500>
    {
        public void Configure(EntityTypeBuilder<EsF2500> entity)
        {
            entity.HasKey(e => e.IdF2500)
                .HasName("PK_ES_F2500_ID_F2500");

            entity.ToTable("ES_F2500");

            entity.Property(e => e.IdF2500)
                .ValueGeneratedOnAdd()
                .HasPrecision(10)
                .HasColumnName("ID_F2500");

            entity.Property(e => e.CodParte)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .HasColumnName("COD_PROCESSO");

            entity.Property(e => e.EvtproctrabId)
                .HasMaxLength(36)
                .IsUnicode(false)
                .HasColumnName("EVTPROCTRAB_ID");

            entity.Property(e => e.ExclusaoNrrecibo)
                .HasMaxLength(23)
                .IsUnicode(false)
                .HasColumnName("EXCLUSAO_NRRECIBO");

            entity.Property(e => e.FinalizadoContador)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("FINALIZADO_CONTADOR")
                .IsFixedLength();

            entity.Property(e => e.FinalizadoEscritorio)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("FINALIZADO_ESCRITORIO")
                .IsFixedLength();

            entity.Property(e => e.IdeempregadorNrinsc)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("IDEEMPREGADOR_NRINSC");

            entity.Property(e => e.IdeempregadorTpinsc)
                .HasPrecision(2)
                .HasColumnName("IDEEMPREGADOR_TPINSC");

            entity.Property(e => e.IdeeventoIndretif)
                .HasPrecision(2)
                .HasColumnName("IDEEVENTO_INDRETIF");

            entity.Property(e => e.IdeeventoNrrecibo)
                .HasMaxLength(23)
                .IsUnicode(false)
                .HasColumnName("IDEEVENTO_NRRECIBO");

            entity.Property(e => e.IdeeventoProcemi)
                .HasPrecision(2)
                .HasColumnName("IDEEVENTO_PROCEMI");

            entity.Property(e => e.IdeeventoTpamb)
                .HasPrecision(2)
                .HasColumnName("IDEEVENTO_TPAMB");

            entity.Property(e => e.IdeeventoVerproc)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("IDEEVENTO_VERPROC");

            entity.Property(e => e.IderespDtadmrespdir)
                .HasColumnType("DATE")
                .HasColumnName("IDERESP_DTADMRESPDIR");

            entity.Property(e => e.IderespMatrespdir)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("IDERESP_MATRESPDIR");

            entity.Property(e => e.IderespNrinsc)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("IDERESP_NRINSC");

            entity.Property(e => e.IderespTpinsc)
                .HasPrecision(2)
                .HasColumnName("IDERESP_TPINSC");

            entity.Property(e => e.IdetrabCpftrab)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("IDETRAB_CPFTRAB");

            entity.Property(e => e.IdetrabDtnascto)
                .HasColumnType("DATE")
                .HasColumnName("IDETRAB_DTNASCTO");

            entity.Property(e => e.IdetrabNmtrab)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("IDETRAB_NMTRAB");

            entity.Property(e => e.InfoccpCnpjccp)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("INFOCCP_CNPJCCP");

            entity.Property(e => e.InfoccpDtccp)
                .HasColumnType("DATE")
                .HasColumnName("INFOCCP_DTCCP");

            entity.Property(e => e.InfoccpTpccp)
                .HasPrecision(2)
                .HasColumnName("INFOCCP_TPCCP");

            entity.Property(e => e.InfoprocessoNrproctrab)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("INFOPROCESSO_NRPROCTRAB");

            entity.Property(e => e.InfoprocessoObsproctrab)
                .HasMaxLength(999)
                .IsUnicode(false)
                .HasColumnName("INFOPROCESSO_OBSPROCTRAB");

            entity.Property(e => e.InfoprocessoOrigem)
                .HasPrecision(2)
                .HasColumnName("INFOPROCESSO_ORIGEM");

            entity.Property(e => e.InfoprocjudCodmunic)
                .HasPrecision(7)
                .HasColumnName("INFOPROCJUD_CODMUNIC");

            entity.Property(e => e.InfoprocjudDtsent)
                .HasColumnType("DATE")
                .HasColumnName("INFOPROCJUD_DTSENT");

            entity.Property(e => e.InfoprocjudIdvara)
                .HasPrecision(4)
                .HasColumnName("INFOPROCJUD_IDVARA");

            entity.Property(e => e.InfoprocjudUfvara)
                .HasMaxLength(2)
                .HasColumnName("INFOPROCJUD_UFVARA");

            entity.Property(e => e.LogCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.Property(e => e.MsgsInconsistenciasEsocial)
               .HasColumnType("CLOB")
               .HasColumnName("MSGS_INCONSISTENCIAS_ESOCIAL");

            entity.Property(e => e.NomeArquivoEnviado)
                .HasMaxLength(75)
                .IsUnicode(false)
                .HasColumnName("NOME_ARQUIVO_ENVIADO");

            entity.Property(e => e.NomeArquivoRetornado)
                .HasMaxLength(75)
                .IsUnicode(false)
                .HasColumnName("NOME_ARQUIVO_RETORNADO");

            entity.Property(e => e.NomeArquivoExclusao)
                .HasMaxLength(75)
                .IsUnicode(false)
                .HasColumnName("NOME_ARQUIVO_EXCLUSAO");

            entity.Property(e => e.StatusFormulario)
                .HasPrecision(2)
                .HasColumnName("STATUS_FORMULARIO");

            entity.Property(e => e.VersaoEsocial)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("VERSAO_ESOCIAL");

            entity.Property(e => e.OkSemRecibo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("OK_SEM_RECIBO")
                .IsFixedLength();

            entity.HasOne(d => d.LogCodUsuarioNavigation)
                .WithMany(p => p.EsF2500)
                .HasForeignKey(d => d.LogCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_F2500_LOG_COD_USUARIO");

            entity.HasOne(d => d.CodP)
                .WithMany(p => p.EsF2500)
                .HasForeignKey(d => new { d.CodProcesso, d.CodParte })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_F2500");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsF2500> entity);
    }
}
