// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsParteProcessoConfiguration : IEntityTypeConfiguration<EsParteProcesso>
    {
        public void Configure(EntityTypeBuilder<EsParteProcesso> entity)
        {
            entity.HasKey(e => new { e.CodProcesso, e.CodParte });

            entity.ToTable("ES_PARTE_PROCESSO");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .HasColumnName("COD_PROCESSO");

            entity.Property(e => e.CodParte)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE");

            entity.Property(e => e.LogCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("LOG_COD_USUARIO");

            entity.Property(e => e.LogDataOperacao)
                .HasPrecision(6)
                .HasColumnName("LOG_DATA_OPERACAO");

            entity.Property(e => e.StatusReclamante)
                .HasPrecision(2)
                .HasColumnName("STATUS_RECLAMANTE");

            entity.HasOne(d => d.CodParteNavigation)
                .WithMany(p => p.EsParteProcesso)
                .HasForeignKey(d => d.CodParte)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_PARTE_PROCESSO_COD_PARTE");

            entity.HasOne(d => d.CodProcessoNavigation)
                .WithMany(p => p.EsParteProcesso)
                .HasForeignKey(d => d.CodProcesso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_PARTE_PROCESSO_COD_PROCE");

            entity.HasOne(d => d.LogCodUsuarioNavigation)
                .WithMany(p => p.EsParteProcesso)
                .HasForeignKey(d => d.LogCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_PARTE_PROCESSO_LOG_COD_U");

            entity.HasOne(d => d.CodP)
                .WithOne(p => p.EsParteProcesso)
                .HasForeignKey<EsParteProcesso>(d => new { d.CodProcesso, d.CodParte })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ES_PARTE_PROCESSO_COD_PROC2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsParteProcesso> entity);
    }
}
