// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsTabelaTipoContratoTsveConfiguration : IEntityTypeConfiguration<EsTabelaTipoContratoTsve>
    {
        public void Configure(EntityTypeBuilder<EsTabelaTipoContratoTsve> entity)
        {
            entity.HasKey(e => e.CodEsTipoContrato)
                .HasName("ES_TIPO_CONTRATO_TSVE_PK");

            entity.ToTable("ES_TABELA_TIPO_CONTRATO_TSVE");

            entity.Property(e => e.CodEsTipoContrato)
                .HasColumnType("NUMBER")
                .HasColumnName("COD_ES_TIPO_CONTRATO");

            entity.Property(e => e.DataVigenciaFinal)
                .HasColumnType("DATE")
                .HasColumnName("DATA_VIGENCIA_FINAL");

            entity.Property(e => e.DataVigenciaInicial)
                .HasColumnType("DATE")
                .HasColumnName("DATA_VIGENCIA_INICIAL");

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            entity.Property(e => e.NomEsTipoContrato)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOM_ES_TIPO_CONTRATO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsTabelaTipoContratoTsve> entity);
    }
}
