// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsTabela07Configuration : IEntityTypeConfiguration<EsTabela07>
    {
        public void Configure(EntityTypeBuilder<EsTabela07> entity)
        {
            entity.HasKey(e => new { e.CodEsTabela07, e.DatInicio });

            entity.ToTable("ES_TABELA_07");

            entity.Property(e => e.CodEsTabela07)
                .HasPrecision(2)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_ES_TABELA_07");

            entity.Property(e => e.DatInicio)
                .HasColumnType("DATE")
                .ValueGeneratedOnAdd()
                .HasColumnName("DAT_INICIO");

            entity.Property(e => e.DatTermino)
                .HasColumnType("DATE")
                .ValueGeneratedOnAdd()
                .HasColumnName("DAT_TERMINO");

            entity.Property(e => e.DscEsTabela07)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("DSC_ES_TABELA_07");

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsTabela07> entity);
    }
}
