// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsTabelaCrIrrfConfiguration : IEntityTypeConfiguration<EsTabelaCrIrrf>
    {
        public void Configure(EntityTypeBuilder<EsTabelaCrIrrf> entity)
        {
            entity.HasKey(e => e.CodCrirrf)
                .HasName("ES_CR_IRRF_PK");

            entity.ToTable("ES_TABELA_CR_IRRF");

            entity.Property(e => e.CodCrirrf)
                 .HasColumnType("NUMBER(6,0)")
                .IsUnicode(false)
                .HasColumnName("COD_CRIRRF");

            entity.Property(e => e.DataVigenciaFinal)
                .HasColumnType("DATE")
                .HasColumnName("DATA_VIGENCIA_FINAL");

            entity.Property(e => e.DataVigenciaInicial)
                .HasColumnType("DATE")
                .HasColumnName("DATA_VIGENCIA_INICIAL");

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            entity.Property(e => e.NomCrirrf)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOM_CRIRRF");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsTabelaCrIrrf> entity);
    }
}
