// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EsTipoContratoProcJudConfiguration : IEntityTypeConfiguration<EsTipoContratoProcJud>
    {
        public void Configure(EntityTypeBuilder<EsTipoContratoProcJud> entity)
        {
            entity.HasKey(e => e.CodEsTipoContrato)
                .HasName("PK_ES_TIPO_CONTRATO_PROC_JUD_C");

            entity.ToTable("ES_TIPO_CONTRATO_PROC_JUD");

            entity.Property(e => e.CodEsTipoContrato)
                .HasPrecision(2)
                .HasColumnName("COD_ES_TIPO_CONTRATO");

            entity.Property(e => e.DscEsTipoContrato)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_ES_TIPO_CONTRATO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EsTipoContratoProcJud> entity);
    }
}
