// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class EventoConfiguration : IEntityTypeConfiguration<Evento>
    {
        public void Configure(EntityTypeBuilder<Evento> entity)
        {
            entity.HasKey(e => e.CodEvento);

            entity.ToTable("EVENTO");

            entity.HasIndex(e => e.IndDecisao, "IDX_EVENTO_01");

            entity.Property(e => e.CodEvento)
                .HasPrecision(4)
                .HasColumnName("COD_EVENTO");

            entity.Property(e => e.CatevIdCategoriaEvento)
                .HasPrecision(4)
                .HasColumnName("CATEV_ID_CATEGORIA_EVENTO");

            entity.Property(e => e.CodInstancia)
                .HasPrecision(1)
                .HasColumnName("COD_INSTANCIA");

            entity.Property(e => e.CodTipoMulta)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_TIPO_MULTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.DscEvento)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_EVENTO");

            entity.Property(e => e.IndAlteraExclui)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ALTERA_EXCLUI")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivel)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndCivelAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelEstrategico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ESTRATEGICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndComentarioObrig)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_COMENTARIO_OBRIG")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalJudicial)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndDecisao)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_DECISAO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndEscritorioAtualiza)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ESCRITORIO_ATUALIZA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndFinalizacaoContabil)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_FINALIZACAO_CONTABIL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndFinalizacaoProcesso)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_FINALIZACAO_PROCESSO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndJuizado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_JUIZADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndNotificarViaEmail)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_NOTIFICAR_VIA_EMAIL")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndPexCivelConsumidor)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEX_CIVEL_CONSUMIDOR")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPexJuizado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEX_JUIZADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPrazo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PRAZO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPreencheMulta)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PREENCHE_MULTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndRegulatorio)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_REGULATORIO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndReverCalculo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_REVER_CALCULO")
                .IsFixedLength();

            entity.Property(e => e.IndTrabalhista)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRABALHISTA")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndTrabalhistaAdm)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRABALHISTA_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTributarioAdm)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIO_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTributarioJud)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIO_JUD")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.SeqDecisao)
                .HasPrecision(2)
                .HasColumnName("SEQ_DECISAO")
                .HasDefaultValueSql("0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Evento> entity);
    }
}
