// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class TipoVaraConfiguration : IEntityTypeConfiguration<TipoVara>
    {
        public void Configure(EntityTypeBuilder<TipoVara> entity)
        {
            entity.HasKey(e => e.CodTipoVara);

            entity.ToTable("TIPO_VARA");

            entity.Property(e => e.CodTipoVara)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_VARA");

            entity.Property(e => e.IndCivel)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelEstrategico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ESTRATEGICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalJudicial)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndJuizado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_JUIZADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTrabalhista)
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("IND_TRABALHISTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTributaria)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.NomTipoVara)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("NOM_TIPO_VARA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoVara> entity);
    }
}
