// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ESocialContext.Data;
using Oi.Juridico.Contextos.V2.ESocialContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Data.Configurations
{
    public partial class VersaoServidorModuloConfiguration : IEntityTypeConfiguration<VersaoServidorModulo>
    {
        public void Configure(EntityTypeBuilder<VersaoServidorModulo> entity)
        {
            entity.HasKey(e => e.Codigo)
                .HasName("VERSERMOD_PK");

            entity.ToTable("VERSAO_SERVIDOR_MODULO");

            entity.HasIndex(e => new { e.Servidor, e.Modulo }, "VERSERMOD_UE")
                .IsUnique();

            entity.Property(e => e.Codigo)
                .HasColumnType("NUMBER")
                .HasColumnName("CODIGO");

            entity.Property(e => e.Data)
                .HasColumnType("DATE")
                .HasColumnName("DATA");

            entity.Property(e => e.Modulo)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("MODULO");

            entity.Property(e => e.Servidor)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("SERVIDOR");

            entity.Property(e => e.Versao)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("VERSAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VersaoServidorModulo> entity);
    }
}
