// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.RelatorioMovimentacoesPexContext.Entities
{
    public partial class AcaUsuario
    {
        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string Senha { get; set; }
        public string Perfil { get; set; }
        public string IndCivel { get; set; }
        public string IndTrabalhista { get; set; }
        public string IndRegulatorio { get; set; }
        public string IndUsuarioInternet { get; set; }
        public string DscEmail { get; set; }
        public string IndTributario { get; set; }
        public string IndAtivo { get; set; }
        public string IndControladoria { get; set; }
        public string IndBloqueado { get; set; }
        public string IndMudarSenha { get; set; }
        public DateTime? DatValidadeSenha { get; set; }
        public string IndJuizado { get; set; }
        public string IndPerfilWeb { get; set; }
        public string IndPreposto { get; set; }
        public string IndAutorizaServico { get; set; }
        public string IndCivelEstrategico { get; set; }
        public DateTime DataDesativacao { get; set; }
        public string IndRestrito { get; set; }
        public byte? AreaCodAreaJec { get; set; }
        public byte CodPrioridadeExecRel { get; set; }
        public string IndCriminalAdm { get; set; }
        public string IndCriminalJudicial { get; set; }
        public string IndCivelAdm { get; set; }
        public string IndProcon { get; set; }
        public string IndAutorizaServProcon { get; set; }
        public string ObsUsuario { get; set; }
        public string IndPex { get; set; }
        public string IndAdmAprovadorAcessos { get; set; }
        public string IndGestorAprovadorAcessos { get; set; }
        public string CodTipoUsuarioPerfil { get; set; }
        public string NumCpf { get; set; }
        public decimal? IdBo { get; set; }
        public string IndOperadorCadastro { get; set; }
        public string CodGestorDefault { get; set; }
        public string IndOperadorValidacaoJec { get; set; }
        public string IndOperadorValidacaoCcons { get; set; }
        public decimal? CodOrigemUsuario { get; set; }
        public string CodSituacaoUsuario { get; set; }
        public string IndInativacaoManual { get; set; }
        public string IndInativacaoAutomatica { get; set; }
        public string IndUsuarioEstrangeiro { get; set; }
        public string CodUsuarioResponsavel { get; set; }
    }
}