// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.RelatorioMovimentacoesPexContext.Entities
{
    public partial class AgendMovimentacaoPex
    {

        public static AgendMovimentacaoPex Adicionar(
            DateTime DatAgendamento,
            int FechamentoPexMediaIniCodSolic,
            int FechamentoPexMediaFimCodSolic,
            DateTime DatFechamentoIni,
            DateTime DatFechamentoFim,
            int Status,
            string UsrCodUsuario)
        {
            return new AgendMovimentacaoPex
            {
                DatAgendamento = DatAgendamento,
                FechamentoPexMediaIniCodSolic = FechamentoPexMediaIniCodSolic,
                FechamentoPexMediaFimCodSolic = FechamentoPexMediaFimCodSolic,
                DatFechamentoIni = DatFechamentoIni,
                DatFechamentoFim = DatFechamentoFim,
                Status = Status,
                UsuarioId = UsrCodUsuario
            };
        }

        public decimal Id { get; private set; }
        public DateTime DatAgendamento { get; private set; }
        public int FechamentoPexMediaIniCodSolic { get; private set; }
        public int FechamentoPexMediaFimCodSolic { get; private set; }
        public DateTime DatFechamentoIni { get; private set; }
        public DateTime DatFechamentoFim { get; private set; }
        public DateTime? DatInicioExecucao { get; private set; }
        public DateTime? DatFimExecucao { get; private set; }
        public int Status { get; private set; }
        public string MsgErro { get; private set; }
        public string UsuarioId { get; private set; }
        public virtual AcaUsuario Usuario { get; set; }
    }
}