// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.PermissaoContext.Entities;

namespace Oi.Juridico.Contextos.V2.PermissaoContext.Data.Configurations
{
    public partial class VPermissoesModulosConfiguration : IEntityTypeConfiguration<VPermissoesModulos>
    {
        public void Configure(EntityTypeBuilder<VPermissoesModulos> entity)
        {
            entity.HasNoKey();

            entity.ToView("V_PERMISSOES_MODULOS");

            entity.Property(e => e.CodAplicacao)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("COD_APLICACAO");

            entity.Property(e => e.CodMenu)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("COD_MENU");

            entity.Property(e => e.DescricaoMenu)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("DESCRICAO_MENU");

            entity.Property(e => e.DscCaminhoMenuTela)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("DSC_CAMINHO_MENU_TELA");

            entity.Property(e => e.Modulos)
                .IsUnicode(false)
                .HasColumnName("MODULOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VPermissoesModulos> entity);
    }
}
