// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContext.Entities
{
    public partial class BbNaturezasAcoes
    {
        public BbNaturezasAcoes()
        {
            Acao = new HashSet<Acao>();
        }

        public decimal Id { get; set; }
        public short Codigo { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<Acao> Acao { get; set; }
    }
}