// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Data;
using Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Entities;
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.V2.CargaDeCompromissoContext.Data.Configurations
{
    public partial class CargaCompromissoParcelaConfiguration : IEntityTypeConfiguration<CargaCompromissoParcela>
    {
        public void Configure(EntityTypeBuilder<CargaCompromissoParcela> entity)
        {
            entity.ToTable("CARGA_COMPROMISSO_PARCELA");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.CodLancamento)
                .HasPrecision(5)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_LANCAMENTO")
                .HasDefaultValueSql("NULL ");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_PROCESSO")
                .HasDefaultValueSql("NULL ");

            entity.Property(e => e.ComentarioCancelamento)
                .HasMaxLength(250)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("COMENTARIO_CANCELAMENTO");

            entity.Property(e => e.ComentarioEstorno)
                .HasMaxLength(250)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("COMENTARIO_ESTORNO");

            entity.Property(e => e.DataSolicCancelamento)
                .HasMaxLength(250)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("DATA_SOLIC_CANCELAMENTO");

            entity.Property(e => e.Deletado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("DELETADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.DeletadoDatahora)
                .HasColumnType("DATE")
                .ValueGeneratedOnAdd()
                .HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(200)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.IdCompromisso)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID_COMPROMISSO");

            entity.Property(e => e.MotivoCancelamento)
                .HasMaxLength(250)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("MOTIVO_CANCELAMENTO");

            entity.Property(e => e.MotivoExclusao)
                .HasMaxLength(200)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("MOTIVO_EXCLUSAO");

            entity.Property(e => e.NroParcela)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("NRO_PARCELA");

            entity.Property(e => e.SeqLancamento)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("SEQ_LANCAMENTO");

            entity.Property(e => e.Status)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("STATUS");

            entity.Property(e => e.UsrSolicCancelamento)
                .HasMaxLength(250)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("USR_SOLIC_CANCELAMENTO");

            entity.Property(e => e.Valor)
                .HasColumnType("NUMBER(18,3)")
                .ValueGeneratedOnAdd()
                .HasColumnName("VALOR");

            entity.Property(e => e.Vencimento)
                .HasColumnType("DATE")
                .ValueGeneratedOnAdd()
                .HasColumnName("VENCIMENTO");

            entity.HasOne(d => d.CodProcessoNavigation)
                .WithMany(p => p.CargaCompromissoParcela)
                .HasForeignKey(d => d.CodProcesso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CARGA_COMPROMISSO_PARCELA_FK2");

            entity.HasOne(d => d.IdCompromissoNavigation)
                .WithMany(p => p.CargaCompromissoParcela)
                .HasForeignKey(d => d.IdCompromisso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CARGA_COMPROMISSO_PARCELA_FK1");

            entity.HasOne(d => d.Cod)
                .WithMany(p => p.CargaCompromissoParcela)
                .HasForeignKey(d => new { d.CodProcesso, d.CodLancamento })
                .HasConstraintName("CARGA_COMPROMISSO_PARCELA_FK3");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CargaCompromissoParcela> entity);
    }
}
