// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Entities
{
    public partial class AcaOrigemUsuario
    {
        public AcaOrigemUsuario()
        {
            AcaSolicitacaoAcesso = new HashSet<AcaSolicitacaoAcesso>();
            AcaUsuario = new HashSet<AcaUsuario>();
        }

        public decimal CodOrigemUsuario { get; set; }
        public string NomOrigemUsuario { get; set; }
        public decimal CodImportacaoAuto { get; set; }
        public string IndEscritorio { get; set; }
        public string IndAtivo { get; set; }

        public virtual ICollection<AcaSolicitacaoAcesso> AcaSolicitacaoAcesso { get; set; }
        public virtual ICollection<AcaUsuario> AcaUsuario { get; set; }
    }
}