// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Entities
{
    public partial class AcaSolicitacaoAcesso
    {
        public AcaSolicitacaoAcesso()
        {
            SolAprovacaoPerfil = new HashSet<SolAprovacaoPerfil>();
        }

        public decimal Id { get; set; }
        public string CodUsuarioSolicitacao { get; set; }
        public string CodTipoSolicitacaoAcesso { get; set; }
        public DateTime DataSolicitacaoAcesso { get; set; }
        public string NomeUsuario { get; set; }
        public string DescEmail { get; set; }
        public string NomeProfissional { get; set; }
        public string DescOutrosAcessos { get; set; }
        public string IndPendente { get; set; }
        public string Observacao { get; set; }
        public string CodUsuarioAtuPendencia { get; set; }
        public DateTime? DataAtualizacaoPendencia { get; set; }
        public string DescRemetenteEmail { get; set; }
        public string DescDestinatarioEmail { get; set; }
        public string CpfUsuario { get; set; }
        public decimal? IdAreaAtuacao { get; set; }
        public byte? CodStatusSolicitacao { get; set; }
        public string DescricaoRejeicao { get; set; }
        public int? CodProfissional { get; set; }
        public decimal? IdStatusRenovacaoAcesso { get; set; }
        public string DescObservacao { get; set; }
        public decimal? CodOrigemUsuario { get; set; }
        public string IndUsuarioEstrangeiro { get; set; }
        public string CodUsuarioAdmAprov { get; set; }
        public DateTime? DatUsuarioAdmAprov { get; set; }
        public int? CodBoResponsavel { get; set; }
        public string Justificativa { get; set; }

        public virtual AcaOrigemUsuario CodOrigemUsuarioNavigation { get; set; }
        public virtual AcaUsuario CodUsuarioSolicitacaoNavigation { get; set; }
        public virtual StatusRenovacaoAcesso IdStatusRenovacaoAcessoNavigation { get; set; }
        public virtual ICollection<SolAprovacaoPerfil> SolAprovacaoPerfil { get; set; }
    }
}