// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Entities
{
    public partial class AcaUsuarioEscritorio
    {
        public string CodUsuario { get; set; }
        public int CodProfissional { get; set; }

        public virtual AcaUsuario CodUsuarioNavigation { get; set; }
    }
}