// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Entities
{
    public partial class AcaUsuario
    {
        public AcaUsuario()
        {
            AcaSolicitacaoAcesso = new HashSet<AcaSolicitacaoAcesso>();
            AcaUsuarioEscritorio = new HashSet<AcaUsuarioEscritorio>();
            SolAprovacaoPerfilCodUsuarioAdministradorNavigation = new HashSet<SolAprovacaoPerfil>();
            SolAprovacaoPerfilCodUsuarioGestorNavigation = new HashSet<SolAprovacaoPerfil>();
            SolAprovacaoPerfilCodUsuarioSolicitanteNavigation = new HashSet<SolAprovacaoPerfil>();
        }

        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string DscEmail { get; set; }
        public DateTime? DatValidadeSenha { get; set; }
        public byte? AreaCodAreaJec { get; set; }
        public decimal? IdBo { get; set; }
        public decimal? CodOrigemUsuario { get; set; }
        public string CodSituacaoUsuario { get; set; }

        public virtual AcaOrigemUsuario CodOrigemUsuarioNavigation { get; set; }
        public virtual ICollection<AcaSolicitacaoAcesso> AcaSolicitacaoAcesso { get; set; }
        public virtual ICollection<AcaUsuarioEscritorio> AcaUsuarioEscritorio { get; set; }
        public virtual ICollection<SolAprovacaoPerfil> SolAprovacaoPerfilCodUsuarioAdministradorNavigation { get; set; }
        public virtual ICollection<SolAprovacaoPerfil> SolAprovacaoPerfilCodUsuarioGestorNavigation { get; set; }
        public virtual ICollection<SolAprovacaoPerfil> SolAprovacaoPerfilCodUsuarioSolicitanteNavigation { get; set; }
    }
}