// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Data;
using Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Entities;
using System.Collections.Generic;
using System;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Data.Configurations
{
    public partial class AlocacaoPrepostoConfiguration : IEntityTypeConfiguration<AlocacaoPreposto>
    {
        public void Configure(EntityTypeBuilder<AlocacaoPreposto> entity)
        {
            entity.HasKey(e => new { e.CodParteEmpresa, e.CodComarca, e.CodVara, e.CodTipoVara, e.CodPreposto, e.DatAlocacao });

            entity.ToTable("ALOCACAO_PREPOSTO");

            entity.HasIndex(e => new { e.CodComarca, e.CodVara, e.CodTipoVara }, "FK_VARA_ALOCACAO_PREPOSTO_I");

            entity.Property(e => e.CodParteEmpresa)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE_EMPRESA");

            entity.Property(e => e.CodComarca)
                .HasPrecision(4)
                .HasColumnName("COD_COMARCA");

            entity.Property(e => e.CodVara)
                .HasPrecision(3)
                .HasColumnName("COD_VARA");

            entity.Property(e => e.CodTipoVara)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_VARA");

            entity.Property(e => e.CodPreposto)
                .HasPrecision(6)
                .HasColumnName("COD_PREPOSTO");

            entity.Property(e => e.DatAlocacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ALOCACAO");

            entity.Property(e => e.IndPrincipal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PRINCIPAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.HasOne(d => d.CodParteEmpresaNavigation)
                .WithMany(p => p.AlocacaoPreposto)
                .HasForeignKey(d => d.CodParteEmpresa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PARTE_ALOCACAO");

            entity.HasOne(d => d.CodPrepostoNavigation)
                .WithMany(p => p.AlocacaoPreposto)
                .HasForeignKey(d => d.CodPreposto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PREPOSTO_ALOCACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AlocacaoPreposto> entity);
    }
}
