// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Data;
using Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Entities;
using System.Collections.Generic;
using System;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Data.Configurations
{
    public partial class PedidoConfiguration : IEntityTypeConfiguration<Pedido>
    {
        public void Configure(EntityTypeBuilder<Pedido> entity)
        {
            entity.HasKey(e => e.CodPedido);

            entity.ToTable("PEDIDO");

            entity.Property(e => e.CodPedido)
                .HasPrecision(4)
                .HasColumnName("COD_PEDIDO");

            entity.Property(e => e.CodRiscoPerda)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_RISCO_PERDA")
                .IsFixedLength();

            entity.Property(e => e.CppCodClassificacaoPedido)
                .HasPrecision(4)
                .HasColumnName("CPP_COD_CLASSIFICACAO_PEDIDO");

            entity.Property(e => e.DataBaseReceitaMedia)
                .HasColumnType("DATE")
                .HasColumnName("DATA_BASE_RECEITA_MEDIA");

            entity.Property(e => e.DscPedido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_PEDIDO");

            entity.Property(e => e.GrpdCodGrupoPedido)
                .HasPrecision(4)
                .HasColumnName("GRPD_COD_GRUPO_PEDIDO");

            entity.Property(e => e.IndAtivoTributarioAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO_TRIBUTARIO_ADM")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndAtivoTributarioJud)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO_TRIBUTARIO_JUD")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelEstrategico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ESTRATEGICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalJudicial)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndEscritorioObrigatorio)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ESCRITORIO_OBRIGATORIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndInfluenciaContingencia)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_INFLUENCIA_CONTINGENCIA")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_ATIVO")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoCivel)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_CIVEL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoJuizado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_JUIZADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoRegulatorio)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_REGULATORIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoTrabalhista)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_TRABALHISTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoTrabalhistaAdm)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_TRABALHISTA_ADM")
                .HasDefaultValueSql("'N'");

            entity.Property(e => e.IndPedidoTributarioAdm)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_TRIBUTARIO_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPedidoTributarioJud)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEDIDO_TRIBUTARIO_JUD")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPex)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEX")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndProprioTerceiro)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROPRIO_TERCEIRO")
                .HasDefaultValueSql("'P' ")
                .IsFixedLength();

            entity.Property(e => e.IndProvavelZero)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROVAVEL_ZERO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndRequerAtualizacaoDebito)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_REQUER_ATUALIZACAO_DEBITO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.PercMelhorRealizavel)
                .HasColumnType("NUMBER(7,4)")
                .HasColumnName("PERC_MELHOR_REALIZAVEL")
                .HasDefaultValueSql("0 ");

            entity.Property(e => e.PercRateioRisco)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PERC_RATEIO_RISCO")
                .HasDefaultValueSql("0   ");

            entity.Property(e => e.ValorReceitaMedia)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_RECEITA_MEDIA")
                .HasDefaultValueSql("0 ");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pedido> entity);
    }
}
