// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Entities
{
    public partial class AcaUsuario
    {
        public AcaUsuario()
        {
            Preposto = new HashSet<Preposto>();
            UsuarioRegional = new HashSet<UsuarioRegional>();
            CodProfissional = new HashSet<Profissional>();
        }

        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public short? AreaCodAreaJec { get; set; }
        public decimal? IdBo { get; set; }
        public decimal? CodOrigemUsuario { get; set; }

        public virtual ICollection<Preposto> Preposto { get; set; }
        public virtual ICollection<UsuarioRegional> UsuarioRegional { get; set; }

        public virtual ICollection<Profissional> CodProfissional { get; set; }
    }
}