// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Entities
{
    public partial class GrupoJuizado
    {
        public short CodGrupoJuizado { get; set; }
        public string DscGrupoJuizado { get; set; }
    }
}