// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoPesquisaContext.Entities
{
    public partial class UsuarioRegional
    {
        public short CodRegional { get; set; }
        public string CodUsuario { get; set; }
        public short CodTipoProcesso { get; set; }
        public string IndResponsavel { get; set; }

        public virtual AcaUsuario CodUsuarioNavigation { get; set; }
    }
}