// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class AcaUsuarioEmpresaGrupo
    {
        public string CodUsuario { get; set; }
        public int CodParte { get; set; }

        public virtual Parte CodParteNavigation { get; set; }
        public virtual AcaUsuario CodUsuarioNavigation { get; set; }
    }
}