// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class AndamentoProcesso
    {
        public long CodProcesso { get; set; }
        public short SeqAndamento { get; set; }
        public byte? CodAcao { get; set; }
        public DateTime DatEvento { get; set; }
        public int CodEvento { get; set; }
        public byte? CodDecisao { get; set; }
        public string DscComentario { get; set; }
        public string NroEvento { get; set; }
        public string DscObrigacaoFazer { get; set; }
        public string DscObrigacaoPagar { get; set; }
        public DateTime DataCriacao { get; set; }
        public string IndAcessoRestrito { get; set; }

        public virtual Evento CodEventoNavigation { get; set; }
        public virtual Processo CodProcessoNavigation { get; set; }
    }
}