// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsF2500Dependente
    {
        public long IdEsF2500Dependente { get; set; }
        public int IdF2500 { get; set; }
        public string DependenteCpfdep { get; set; }
        public string DependenteTpdep { get; set; }
        public string DependenteDescdep { get; set; }
        public string LogCodUsuario { get; set; }
        public DateTime? LogDataOperacao { get; set; }

        public virtual EsF2500 IdF2500Navigation { get; set; }
        public virtual AcaUsuario LogCodUsuarioNavigation { get; set; }
    }
}