// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsF2501Penalim
    {
        public long IdEsF2501Infocrirrf { get; set; }
        public long IdEsF2501Penalim { get; set; }
        public string LogCodUsuario { get; set; }
        public DateTime LogDataOperacao { get; set; }
        public byte? PenalimTprend { get; set; }
        public string PenalimCpfdep { get; set; }
        public decimal? PenalimVlrpensao { get; set; }

        public virtual EsF2501Infocrirrf IdEsF2501InfocrirrfNavigation { get; set; }
    }
}