// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsF2501Infocrirrf
    {
        public EsF2501Infocrirrf()
        {
            EsF2501Deddepen = new HashSet<EsF2501Deddepen>();
            EsF2501Ideadv = new HashSet<EsF2501Ideadv>();
            EsF2501Infoprocret = new HashSet<EsF2501Infoprocret>();
            EsF2501Penalim = new HashSet<EsF2501Penalim>();
        }

        public long IdEsF2501Infocrirrf { get; set; }
        public int IdF2501 { get; set; }
        public DateTime LogDataOperacao { get; set; }
        public string LogCodUsuario { get; set; }
        public int? InfocrcontribTpcr { get; set; }
        public decimal? InfocrcontribVrcr { get; set; }
        public decimal? InfoirVrrendtrib { get; set; }
        public decimal? InfoirVrrendtrib13 { get; set; }
        public decimal? InfoirVrrendmolegrave { get; set; }
        public decimal? InfoirVrrendisen65 { get; set; }
        public decimal? InfoirVrjurosmora { get; set; }
        public decimal? InfoirVrrendisenntrib { get; set; }
        public string InfoirDescisenntrib { get; set; }
        public decimal? InfoirVrprevoficial { get; set; }
        public string InforraDescrra { get; set; }
        public decimal? InforraQtdmesesrra { get; set; }
        public decimal? DespprocjudVlrdespcustas { get; set; }
        public decimal? DespprocjudVlrdespadvogados { get; set; }
        public decimal? InfoirVrrendmolegrave13 { get; set; }
        public decimal? InfoirRrendisen65dec { get; set; }
        public decimal? InfoirVrjurosmora13 { get; set; }
        public decimal? InfoirVrprevoficial13 { get; set; }
        public decimal? InfocrcontribVrcr13 { get; set; }
        public decimal? InfoirVlrDiarias { get; set; }
        public decimal? InfoirVlrAjudaCusto { get; set; }
        public decimal? InfoirVlrIndResContrato { get; set; }
        public decimal? InfoirVlrAbonoPec { get; set; }
        public decimal? InfoirVlrAuxMoradia { get; set; }

        public virtual EsF2501 IdF2501Navigation { get; set; }
        public virtual AcaUsuario LogCodUsuarioNavigation { get; set; }
        public virtual ICollection<EsF2501Deddepen> EsF2501Deddepen { get; set; }
        public virtual ICollection<EsF2501Ideadv> EsF2501Ideadv { get; set; }
        public virtual ICollection<EsF2501Infoprocret> EsF2501Infoprocret { get; set; }
        public virtual ICollection<EsF2501Penalim> EsF2501Penalim { get; set; }
    }
}