// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsF2501Benefpen
    {
        public long? IdEsF2501Dedsusp { get; set; }
        public long IdEsF2501Benefpen { get; set; }
        public string LogCodUsuario { get; set; }
        public DateTime? LogDataOperacao { get; set; }
        public string BenefpenCpfdep { get; set; }
        public decimal? BenefpenVlrdepensusp { get; set; }

        public virtual EsF2501Dedsusp IdEsF2501DedsuspNavigation { get; set; }
    }
}