// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsInconsistenciasF2500F2501
    {
        public int Id { get; set; }
        public int? CodProcesso { get; set; }
        public int? CodParte { get; set; }
        public DateTime? DataCreate { get; set; }
        public int? IdF2500 { get; set; }
        public int? IdF2501 { get; set; }
        public string LogCodUsuario { get; set; }
        public DateTime LogDataOperacao { get; set; }
        public string Datahoraprocessamento { get; set; }
        public string Sequencial { get; set; }
        public string Inconsistencia { get; set; }
        public string Codigo { get; set; }
        public string Tipoinconsistencia { get; set; }
        public string Localizacao { get; set; }
        public string Acao { get; set; }
        public string Campotela { get; set; }
        public string NomeArquivoEnviado { get; set; }
        public int? IdExecucao { get; set; }
    }
}