// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsTabela05
    {
        public byte CodEsTabela05 { get; set; }
        public string DscEsTabela05 { get; set; }
        public string IndAtivo { get; set; }
    }
}