// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsTabela07
    {
        public byte CodEsTabela07 { get; set; }
        public string DscEsTabela07 { get; set; }
        public DateTime DatInicio { get; set; }
        public DateTime? DatTermino { get; set; }
        public string IndAtivo { get; set; }
    }
}