// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class EsTipoContratoProcJud
    {
        public byte CodEsTipoContrato { get; set; }
        public string DscEsTipoContrato { get; set; }
    }
}