// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ESocialContext.Entities
{
    public partial class MunicipioIbge
    {
        public int CodMunicipioIbge { get; set; }
        public string CodEstado { get; set; }
        public byte? CodEstadoIbge { get; set; }
        public string NomMunicipio { get; set; }

        public virtual Estado CodEstadoNavigation { get; set; }
    }
}