// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.FechamentoTrabalhistaContext.Data;
using Oi.Juridico.Contextos.V2.FechamentoTrabalhistaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoTrabalhistaContext.Data.Configurations
{
    public partial class GrupoEmpresasOutliersParteConfiguration : IEntityTypeConfiguration<GrupoEmpresasOutliersParte>
    {
        public void Configure(EntityTypeBuilder<GrupoEmpresasOutliersParte> entity)
        {
            entity.HasKey(e => e.CodGrupoEmpresasOutParte)
                .HasName("GEOP_PK");

            entity.ToTable("GRUPO_EMPRESAS_OUTLIERS_PARTE");

            entity.Property(e => e.CodGrupoEmpresasOutParte)
                .HasPrecision(4)
                .HasColumnName("COD_GRUPO_EMPRESAS_OUT_PARTE");

            entity.Property(e => e.CodGrupoEmpresasOutliers)
                .HasPrecision(2)
                .HasColumnName("COD_GRUPO_EMPRESAS_OUTLIERS");

            entity.Property(e => e.CodParte)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE");

            entity.HasOne(d => d.CodGrupoEmpresasOutliersNavigation)
                .WithMany(p => p.GrupoEmpresasOutliersParte)
                .HasForeignKey(d => d.CodGrupoEmpresasOutliers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("GEOP_GRUPO_EMP_OUTLIERS_FK");

            entity.HasOne(d => d.CodParteNavigation)
                .WithMany(p => p.GrupoEmpresasOutliersParte)
                .HasForeignKey(d => d.CodParte)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("GEOP_PARTE_FK");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrupoEmpresasOutliersParte> entity);
    }
}
