// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.EmpresaContratadaContext.Data;
using Oi.Juridico.Contextos.V2.EmpresaContratadaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.EmpresaContratadaContext.Data.Configurations
{
    public partial class EmpresaContratadaConfiguration : IEntityTypeConfiguration<EmpresaContratada>
    {
        public void Configure(EntityTypeBuilder<EmpresaContratada> entity)
        {
            entity.HasKey(e => e.CodEmpresaContratada)
                .HasName("PK_COD_EMPRESA_CONTRATADA");

            entity.ToTable("EMPRESA_CONTRATADA");

            entity.Property(e => e.CodEmpresaContratada)
                .HasPrecision(10)
                .HasColumnName("COD_EMPRESA_CONTRATADA");

            entity.Property(e => e.NomEmpresaContratada)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_EMPRESA_CONTRATADA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmpresaContratada> entity);
    }
}
