// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoContratoEscritorioContext.Entities
{
    public partial class TipoContratoEscritorio
    {
        public TipoContratoEscritorio()
        {
            ContratoEscritorio = new HashSet<ContratoEscritorio>();
        }

        public long CodTipoContratoEscritorio { get; set; }
        public string DscTipoContrato { get; set; }
        public string IndAtivo { get; set; }

        public virtual ICollection<ContratoEscritorio> ContratoEscritorio { get; set; }
    }
}