// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Data;
using Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Data.Configurations
{
    public partial class VGrupamentoEmpresasGrupoConfiguration : IEntityTypeConfiguration<VGrupamentoEmpresasGrupo>
    {
        public void Configure(EntityTypeBuilder<VGrupamentoEmpresasGrupo> entity)
        {
            entity.HasNoKey();

            entity.ToView("V_GRUPAMENTO_EMPRESAS_GRUPO");

            entity.Property(e => e.Codigo)
                .HasPrecision(4)
                .HasColumnName("CODIGO");

            entity.Property(e => e.NomGrupoEmpresasOutliers)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_GRUPO_EMPRESAS_OUTLIERS");

            entity.Property(e => e.NomParte)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("NOM_PARTE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VGrupamentoEmpresasGrupo> entity);
    }
}
