// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Data.Configurations
{
    public partial class AgendMovimentacaoCcConfiguration : IEntityTypeConfiguration<AgendMovimentacaoCc>
    {
        public void Configure(EntityTypeBuilder<AgendMovimentacaoCc> entity)
        {
            entity.ToTable("AGEND_MOVIMENTACAO_CC");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.DatAgendamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.FimDataFechamento)
                .HasColumnType("DATE")
                .HasColumnName("FIM_DATA_FECHAMENTO");

            entity.Property(e => e.FimEmpresas)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("FIM_EMPRESAS");

            entity.Property(e => e.FimIndFechamentoParcial)
                .HasPrecision(1)
                .HasColumnName("FIM_IND_FECHAMENTO_PARCIAL");

            entity.Property(e => e.FimIndMensal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("FIM_IND_MENSAL")
                .IsFixedLength();

            entity.Property(e => e.FimNumMesesMediaHistorica)
                .HasPrecision(3)
                .HasColumnName("FIM_NUM_MESES_MEDIA_HISTORICA");

            entity.Property(e => e.FimPercentualHaircut)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("FIM_PERCENTUAL_HAIRCUT");

            entity.Property(e => e.IniDataFechamento)
                .HasColumnType("DATE")
                .HasColumnName("INI_DATA_FECHAMENTO");

            entity.Property(e => e.IniEmpresas)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("INI_EMPRESAS");

            entity.Property(e => e.IniIndFechamentoParcial)
                .HasPrecision(1)
                .HasColumnName("INI_IND_FECHAMENTO_PARCIAL");

            entity.Property(e => e.IniIndMensal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("INI_IND_MENSAL")
                .IsFixedLength();

            entity.Property(e => e.IniNumMesesMediaHistorica)
                .HasPrecision(3)
                .HasColumnName("INI_NUM_MESES_MEDIA_HISTORICA");

            entity.Property(e => e.IniPercentualHaircut)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("INI_PERCENTUAL_HAIRCUT");

            entity.Property(e => e.MsgErro)
                .HasColumnType("CLOB")
                .HasColumnName("MSG_ERRO");

            entity.Property(e => e.NomArquivo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_ARQUIVO");

            entity.Property(e => e.Status)
                .HasPrecision(2)
                .HasColumnName("STATUS");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.HasOne(d => d.UsrCodUsuarioNavigation)
                .WithMany(p => p.AgendMovimentacaoCc)
                .HasForeignKey(d => d.UsrCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AGEND_MOV_CC_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendMovimentacaoCc> entity);
    }
}
