// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacoesCivelConsumidorContext.Data.Configurations
{
    public partial class VSoliFechMovRelCcConfiguration : IEntityTypeConfiguration<VSoliFechMovRelCc>
    {
        public void Configure(EntityTypeBuilder<VSoliFechMovRelCc> entity)
        {
            entity.HasNoKey();

            entity.ToView("V_SOLI_FECH_MOV_REL_CC");

            entity.Property(e => e.DataExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DATA_EXECUCAO");

            entity.Property(e => e.DataFechamento)
                .HasColumnType("DATE")
                .HasColumnName("DATA_FECHAMENTO");

            entity.Property(e => e.EmpresasGrupo)
                .IsUnicode(false)
                .HasColumnName("EMPRESAS_GRUPO");

            entity.Property(e => e.IndFechamentoMensal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_FECHAMENTO_MENSAL")
                .IsFixedLength();

            entity.Property(e => e.IndFechamentoParcial)
                .HasPrecision(1)
                .HasColumnName("IND_FECHAMENTO_PARCIAL");

            entity.Property(e => e.NumeroMeses)
                .HasPrecision(3)
                .HasColumnName("NUMERO_MESES");

            entity.Property(e => e.PercHaircut)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PERC_HAIRCUT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VSoliFechMovRelCc> entity);
    }
}
