// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities
{
    public partial class AdvogadoAutorProcesso
    {
        public int CodProcesso { get; set; }
        public int CodProfissional { get; set; }
        public string DscComentario { get; set; }

        public virtual Processo CodProcessoNavigation { get; set; }
        public virtual Profissional CodProfissionalNavigation { get; set; }
    }
}