// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities
{
    public partial class PagamentoProcesso
    {
        public int CodProcesso { get; set; }
        public short CodSeqPagamento { get; set; }
        public string CodTipoPagamento { get; set; }
        public string CodTipoDespesa { get; set; }
        public int? CodPedidoSap { get; set; }
        public short? NroItemPedidoSap { get; set; }
        public decimal? ValAtribuido { get; set; }
        public int? CodProfissional { get; set; }
        public int? CodParte { get; set; }
        public DateTime? DatPagamento { get; set; }
        public decimal? ValPedido { get; set; }
        public string NomFornecedor { get; set; }
        public string DscMaterial { get; set; }
        public int? CentroCusto { get; set; }
        public string NroDocumento { get; set; }
        public string Comentario { get; set; }

        public virtual Processo CodProcessoNavigation { get; set; }
        public virtual Profissional CodProfissionalNavigation { get; set; }
    }
}