// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities
{
    public partial class Protocolos
    {
        public int Id { get; set; }
        public DateTime? DataProtocoloDocumento { get; set; }
        public DateTime? DataEntradaEmpresa { get; set; }
        public DateTime? DataEntradaJuridico { get; set; }
        public string NomeAutorRemetente { get; set; }
        public string NumDocumento { get; set; }
        public short? TpdocCodTipoDocumento { get; set; }
        public string DescObservacao { get; set; }
        public int? ProcCodProcesso { get; set; }
        public DateTime DataCriacao { get; set; }
        public string UsrCodUsuarioCriacao { get; set; }
        public decimal? LcentIdLocalEntrega { get; set; }
        public string DescComplemento { get; set; }
        public DateTime? DataVinculoProcesso { get; set; }
        public byte CodTipoProcesso { get; set; }
        public decimal? IdSubtipoProcesso { get; set; }
        public short? CodComarca { get; set; }
        public short? CodVara { get; set; }
        public short? CodTipoVara { get; set; }
        public int? CodProfissional { get; set; }
        public string NomeArquivo { get; set; }
        public decimal? IdAutoDocumentoGed { get; set; }
        public string IndDocumentoLocalizadoGed { get; set; }
        public string NumCpfCnpjAutor { get; set; }
        public string NumCodigoBarras { get; set; }
        public DateTime? DataColeta { get; set; }
        public DateTime? DatAudienciaPrazo { get; set; }
        public int? CodDocumentoDigitalizado { get; set; }
        public DateTime? DatEntradaGed { get; set; }
        public DateTime? DatDisponibilizacaoGed { get; set; }
        public string DscRetornoGed { get; set; }
        public DateTime? DatEnvioGed { get; set; }
        public DateTime? DatRecepcaoGed { get; set; }
        public string CodStatusInterfaceGed { get; set; }
        public string CodUsuarioVinculoProcesso { get; set; }
        public string IndEnvioVinculoGed { get; set; }
        public decimal? CodIdGedEnvio { get; set; }
        public decimal? CodIdGedRetorno { get; set; }
        public string CodUsuarioValidacaoImagem { get; set; }
        public string CodUsuarioRejeicaoImagem { get; set; }
        public string CodUsuarioAssociouNatureza { get; set; }
        public string CodUsuarioAssociouSubtipo { get; set; }
        public DateTime? DatValidacaoImagem { get; set; }
        public DateTime? DatRejeicaoImagem { get; set; }
        public DateTime? DatAssociouNatureza { get; set; }
        public DateTime? DatAssociouSubtipo { get; set; }
        public int? IdSubtipoProtocolo { get; set; }
        public int? IdNaturezaProtocolo { get; set; }
        public DateTime? DatPrazo { get; set; }
        public DateTime? DatUltStatusGed { get; set; }

        public virtual Profissional CodProfissionalNavigation { get; set; }
        public virtual Processo ProcCodProcessoNavigation { get; set; }
    }
}