// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.PerfilContext.Data;
using Oi.Juridico.Contextos.V2.PerfilContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PerfilContext.Data.Configurations
{
    public partial class AcaUsuarioConfiguration : IEntityTypeConfiguration<AcaUsuario>
    {
        public void Configure(EntityTypeBuilder<AcaUsuario> entity)
        {
            entity.HasKey(e => e.CodUsuario);

            entity.ToTable("ACA_USUARIO");

            entity.HasIndex(e => e.Perfil, "USR_IX_01");

            entity.HasIndex(e => e.IndPerfilWeb, "USR_IX_02");

            entity.HasIndex(e => new { e.IndAtivo, e.IndPerfilWeb }, "USR_IX_03");

            entity.Property(e => e.CodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO");

            entity.Property(e => e.CodGestorDefault)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_GESTOR_DEFAULT");

            entity.Property(e => e.CodTipoUsuarioPerfil)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_TIPO_USUARIO_PERFIL")
                .IsFixedLength();

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPerfilWeb)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PERFIL_WEB")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndRestrito)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_RESTRITO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.NomeUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOME_USUARIO");

            entity.Property(e => e.Perfil)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("PERFIL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AcaUsuario> entity);
    }
}
