// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.AtmPexContext.Data;
using Oi.Juridico.Contextos.AtmPexContext.Entities;
using System;


namespace Oi.Juridico.Contextos.AtmPexContext.Data.Configurations
{
    public partial class AgendFechAtmPexConfiguration : IEntityTypeConfiguration<AgendFechAtmPex>
    {
        public void Configure(EntityTypeBuilder<AgendFechAtmPex> entity)
        {
            entity.ToTable("AGEND_FECH_ATM_PEX");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.CodSolicFechamento)
                //.HasPrecision(8)
                .HasColumnName("COD_SOLIC_FECHAMENTO");

            entity.Property(e => e.DatAgendamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO");

            entity.Property(e => e.DatFechamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FECHAMENTO");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.MsgErro)
                .HasColumnType("CLOB")
                .HasColumnName("MSG_ERRO");

            entity.Property(e => e.NroMesesMediaHistorica)
                //.HasPrecision(3)
                .HasColumnName("NRO_MESES_MEDIA_HISTORICA");

            entity.Property(e => e.Status)
                //.HasPrecision(2)
                .HasColumnName("STATUS");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.Property(e => e.ValMultDesvioPadrao)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("VAL_MULT_DESVIO_PADRAO");

            entity.HasOne(d => d.UsrCodUsuarioNavigation)
                .WithMany(p => p.AgendFechAtmPex)
                .HasForeignKey(d => d.UsrCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AGEND_FECH_ATM_PEX_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendFechAtmPex> entity);
    }
}
