// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.AtmPexContext.Data;
using Oi.Juridico.Contextos.AtmPexContext.Entities;
using System;


namespace Oi.Juridico.Contextos.AtmPexContext.Data.Configurations
{
    public partial class CotacaoIndiceConfiguration : IEntityTypeConfiguration<CotacaoIndice>
    {
        public void Configure(EntityTypeBuilder<CotacaoIndice> entity)
        {
            entity.ToTable("COTACAO_INDICE");
            entity.HasKey(e => new { e.IndiceId,e.DataCotacao });
            entity.Property(e => e.IndiceId).HasColumnName("COD_INDICE");
            entity.Property(e => e.DataCotacao).HasColumnName("DAT_COTACAO");
            entity.Property(e => e.ValorCotacao).HasColumnName("VAL_COTACAO");
            entity.Property(e => e.ValorCotacaoAcumulado).HasColumnName("VAL_COTACAO_ACUMULADO");

        }
       
    }
}
