// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Entities
{
    public partial class LogResultadoNegociacao
    {
        public int? CodResultadoNegociacao { get; set; }
        public string Operacao { get; set; }
        public DateTime? DatLog { get; set; }
        public string CodUsuario { get; set; }
        public string DscResultadoNegociacaoA { get; set; }
        public string DscResultadoNegociacaoD { get; set; }
        public string IndNegociacaoA { get; set; }
        public string IndNegociacaoD { get; set; }
        public string IndPosSentencaA { get; set; }
        public string IndPosSentencaD { get; set; }
        public byte? CodTipoResultadoA { get; set; }
        public byte? CodTipoResultadoD { get; set; }
        public string IndAtivoA { get; set; }
        public string IndAtivoD { get; set; }
    }
}