// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Entities
{
    public partial class ResultadoCttMtv
    {
        public int CodResultadoCttMtv { get; set; }
        public byte SeqContato { get; set; }
        public int CodProcesso { get; set; }
        public int CodResultadoNegociacao { get; set; }
    }
}