// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Data;
using Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ResultadoNegociacaoContext.Data.Configurations
{
    public partial class ResultadoNegociacaoConfiguration : IEntityTypeConfiguration<ResultadoNegociacao>
    {
        public void Configure(EntityTypeBuilder<ResultadoNegociacao> entity)
        {
            entity.HasKey(e => e.CodResultadoNegociacao)
                .HasName("PK_COD_RESULTADO_NEGOCIACAO");

            entity.ToTable("RESULTADO_NEGOCIACAO");

            entity.Property(e => e.CodResultadoNegociacao)
                .HasPrecision(10)
                .HasColumnName("COD_RESULTADO_NEGOCIACAO");

            entity.Property(e => e.CodTipoResultado)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_RESULTADO");

            entity.Property(e => e.DscResultadoNegociacao)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_RESULTADO_NEGOCIACAO");

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            entity.Property(e => e.IndNegociacao)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_NEGOCIACAO")
                .IsFixedLength();

            entity.Property(e => e.IndPosSentenca)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_POS_SENTENCA")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ResultadoNegociacao> entity);
    }
}
