// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.V2.ParametroJuridicoContext.Entities
{
    public partial class ParametroJuridico
    {
        public string CodParametro { get; set; }
        public string CodTipoParametro { get; set; }
        public string DscParametro { get; set; }
        public string DscConteudoParametro { get; set; }
        public string IndUsuarioAtualiza { get; set; }
        public string DscDonoParametro { get; set; }
        public DateTime? DatUltAtualizacao { get; set; }
    }
}