// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Entities
{
    public partial class AlocacaoPreposto
    {
        public int CodParteEmpresa { get; set; }
        public short CodComarca { get; set; }
        public short CodVara { get; set; }
        public short CodTipoVara { get; set; }
        public int CodPreposto { get; set; }
        public DateTime DatAlocacao { get; set; }
        public string IndPrincipal { get; set; }

        public virtual Parte CodParteEmpresaNavigation { get; set; }
        public virtual Preposto CodPrepostoNavigation { get; set; }
    }
}