// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.PautaJuizadoComposicaoContext.Entities
{
    public partial class TipoAudiencia
    {
        public TipoAudiencia()
        {
            AudienciaProcesso = new HashSet<AudienciaProcesso>();
        }

        public short CodTipoAud { get; set; }
        public string DscTipoAudiencia { get; set; }
        public string SglTipoAudiencia { get; set; }
        public string IndCivel { get; set; }
        public string IndTrabalhista { get; set; }
        public string IndTrabalhistaAdm { get; set; }
        public string IndTributariaAdm { get; set; }
        public string IndTributariaJud { get; set; }
        public string IndJuizado { get; set; }
        public string IndCivelEstrategico { get; set; }
        public string IndAdministrativo { get; set; }
        public string IndAtivo { get; set; }
        public string IndCriminalAdm { get; set; }
        public string IndCriminalJudicial { get; set; }
        public string IndCivelAdm { get; set; }
        public string IndProcon { get; set; }
        public string IndPex { get; set; }

        public virtual ICollection<AudienciaProcesso> AudienciaProcesso { get; set; }
    }
}