// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Entities
{
    public partial class AcaUsuario
    {
        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string DscEmail { get; set; }
        public DateTime? DatValidadeSenha { get; set; }
        public byte? AreaCodAreaJec { get; set; }
        public decimal? IdBo { get; set; }
        public decimal? CodOrigemUsuario { get; set; }
        public string CodSituacaoUsuario { get; set; }
    }
}