// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Entities
{
    public partial class EmpCentAgendamFechAuto
    {
        public int IdEmpCentAgendamFechAuto { get; set; }
        public DateTime? DataFechamento { get; set; }
        public int? Mes { get; set; }
        public int? Ano { get; set; }
        public int? NumeroMeses { get; set; }
        public int? TipoFechamento { get; set; }
        public int? IdEmpCentralizadora { get; set; }
        public decimal? ValorCorte { get; set; }
        public DateTime? Data { get; set; }
        public string Email { get; set; }
        public string UsuarioNome { get; set; }
        public decimal? CodSolicFechamentoCont { get; set; }
        public decimal? StatusAgendamento { get; set; }
        public decimal? TipoDataMediaMovel { get; set; }
        public DateTime? DataInicioExecucao { get; set; }
        public DateTime? DataFimExecucao { get; set; }
        public string Error { get; set; }
        public decimal? ValPercentProcOutliers { get; set; }
        public decimal? ValAjusteDesvioPadrao { get; set; }
        public decimal? PercentualHaircut { get; set; }
        public decimal? MultDesvioPadrao { get; set; }
        public string IndAplicarHaircutProcGar { get; set; }
        public string ObsValorCorte { get; set; }
    }
}