// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Entities
{
    public partial class SolicFechContEmpCent
    {
        public int CodSolicFechContEmpCent { get; set; }
        public int CodSolicFechamentoCont { get; set; }
        public short CodEmpresasCentralizadoras { get; set; }

        public virtual EmpresasCentralizadoras CodEmpresasCentralizadorasNavigation { get; set; }
        public virtual SolicFechamentoCont CodSolicFechamentoContNavigation { get; set; }
    }
}