// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.FechamentoContingenciaContext.Entities
{
    public partial class VGrupamentoEmpresasGrupo
    {
        public short Codigo { get; set; }
        public string NomGrupoEmpresasOutliers { get; set; }
        public string NomParte { get; set; }
    }
}