// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Entities
{
    public partial class Parte
    {
        public int CodParte { get; set; }
        public string CodTipoParte { get; set; }
        public string NomParte { get; set; }
    }
}