// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.LogProcessoTrabalhistaContext.Entities
{
    public partial class Preposto
    {
        public int CodPreposto { get; set; }
        public string NomPreposto { get; set; }
        public string IndPrepostoTrabalhista { get; set; }
    }
}