// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AgendamentoRelatorioNegociacaoContext.Entities
{
    public partial class AgendExecRelNegociacao
    {
        public int CodAgendExecRelNegociacao { get; set; }
        public DateTime DatAgendamento { get; set; }
        public string UsrCodUsuario { get; set; }
        public DateTime? DatProxExec { get; set; }
        public DateTime? DatIniExec { get; set; }
        public DateTime? DatFimExec { get; set; }
        public byte Status { get; set; }
        public string NomArquivoGerado { get; set; }
        public string Mensagem { get; set; }
        public string MensagemErroTrace { get; set; }
        public string IndProcessoCc { get; set; }
        public string IndProcessoJec { get; set; }
        public string IndProcessoProcon { get; set; }
        public byte PeriodicidadeExecucao { get; set; }
        public byte? DiaDaSemana { get; set; }
        public string IndUltimoDiaMes { get; set; }
        public byte? DiaDoMes { get; set; }
        public DateTime? DatInicioNegociacao { get; set; }
        public DateTime? DatFimNegociacao { get; set; }
        public byte? PeriodoSemanal { get; set; }
        public byte? PeriodoMensal { get; set; }
        public string IndNegociacoesAtivas { get; set; }
    }
}