// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoSolicitanteContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoSolicitanteContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoSolicitanteContext.Data.Configurations
{
    public partial class SolicitanteConfiguration : IEntityTypeConfiguration<Solicitante>
    {
        public void Configure(EntityTypeBuilder<Solicitante> entity)
        {
            entity.HasKey(e => e.CodSolicitante)
                .HasName("PK_SOLICITANTE_COD_SOLICITANTE");

            entity.ToTable("SOLICITANTE");

            entity.Property(e => e.CodSolicitante)
                .HasPrecision(8)
                .HasColumnName("COD_SOLICITANTE");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("EMAIL");

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("NOME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Solicitante> entity);
    }
}
