// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioPagamentoEscritorioContext.Entities
{
    public partial class AgendCalcRelPagEsc
    {
        public long CodAgendCalcRelPagEsc { get; set; }
        public DateTime DatAgendamento { get; set; }
        public DateTime? DatUltimaExecucao { get; set; }
        public DateTime? DatEspecifica { get; set; }
        public DateTime? DatInicioExecucao { get; set; }
        public DateTime? DatFimExecucao { get; set; }
        public DateTime? DatProximaExecucao { get; set; }
        public string UsrCodUsuario { get; set; }
        public byte PeriodicidadeExecucao { get; set; }
        public DateTime MesReferencia { get; set; }
        public byte? DiaDoMes { get; set; }
        public byte Status { get; set; }
        public string NomArquivoGerado { get; set; }
    }
}