// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.CriminalContext.Data;
using Oi.Juridico.Contextos.V2.CriminalContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Data.Configurations
{
    public partial class AcaoConfiguration : IEntityTypeConfiguration<Acao>
    {
        public void Configure(EntityTypeBuilder<Acao> entity)
        {
            entity.HasKey(e => e.CodAcao);

            entity.ToTable("ACAO");

            entity.Property(e => e.CodAcao)
                .HasPrecision(4)
                .HasColumnName("COD_ACAO");

            entity.Property(e => e.BbnatIdBbNatAcao)
                .HasColumnType("NUMBER")
                .HasColumnName("BBNAT_ID_BB_NAT_ACAO");

            entity.Property(e => e.DscAcao)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("DSC_ACAO");

            entity.Property(e => e.IndAcaoCivel)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ACAO_CIVEL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndAcaoJuizado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ACAO_JUIZADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndAcaoPex)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ACAO_PEX")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndAcaoTrabalhista)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ACAO_TRABALHISTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndAcaoTributaria)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ACAO_TRIBUTARIA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelEstrategico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ESTRATEGICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalJudicial)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndPrincipalParalela)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("IND_PRINCIPAL_PARALELA")
                .HasDefaultValueSql("'PR' ")
                .IsFixedLength();

            entity.Property(e => e.IndProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndRequerEscritorio)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_REQUER_ESCRITORIO")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Acao> entity);
    }
}
