// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.CriminalContext.Data;
using Oi.Juridico.Contextos.V2.CriminalContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Data.Configurations
{
    public partial class ProcessoConfiguration : IEntityTypeConfiguration<Processo>
    {
        public void Configure(EntityTypeBuilder<Processo> entity)
        {
            entity.HasKey(e => e.CodProcesso);

            entity.ToTable("PROCESSO");

            entity.HasIndex(e => e.CodProcedimento, "IDX03_3CON");

            entity.HasIndex(e => e.FtgerIdFatoGerador, "IDX_3CON_PROC_FATO_GERADOR_ID");

            entity.HasIndex(e => e.IdComplAreaEnvolvida, "IDX_COMPLEMENTOAREA");

            entity.HasIndex(e => e.NroProcessoCartorio, "IDX_PROCESSO_01");

            entity.HasIndex(e => e.CodProfissional, "IDX_PROCESSO_02");

            entity.HasIndex(e => e.CodComarca, "IDX_PROCESSO_03");

            entity.HasIndex(e => e.CodEstado, "IDX_PROCESSO_04");

            entity.HasIndex(e => e.CodTipoProcesso, "IDX_PROCESSO_05");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodEscritorioAdverso }, "IDX_PROCESSO_07");

            entity.HasIndex(e => new { e.CodComarca, e.CodVara, e.CodTipoVara }, "IDX_PROCESSO_14");

            entity.HasIndex(e => e.CodParteOrgao, "IDX_PROCESSO_15");

            entity.HasIndex(e => e.CodContador, "IDX_PROCESSO_16");

            entity.HasIndex(e => e.CodParteEmpresa, "IDX_PROCESSO_17");

            entity.HasIndex(e => e.CodEscritorioAcompanhante, "IDX_PROCESSO_18");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.IndProcessoAtivo }, "IDX_PROCESSO_19");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.PrePos }, "IDX_PROCESSO_20");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.IndConsiderarProvisao }, "IDX_PROCESSO_21");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.DataCadastro, e.DatFinalizacaoContabil, e.CodProcesso, e.NroProcessoCartorio, e.DatFinalizacao, e.PrePos, e.IndConsiderarProvisao }, "IDX_PROCESSO_22");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodParteEmpresa, e.CodAcao, e.CodEstado }, "IDX_PROCESSO_23");

            entity.HasIndex(e => new { e.CodAcao, e.CodTipoProcesso, e.DataCadastro }, "IDX_PROCESSO_25");

            entity.HasIndex(e => new { e.CodProcesso, e.IndConsiderarProvisao }, "IDX_PROCESSO_26");

            entity.HasIndex(e => new { e.IndProcessoAtivo, e.IdBo, e.CodTipoProcesso, e.DataCadastro }, "IDX_PROCESSO_27");

            entity.HasIndex(e => e.CodMunicipio, "IDX_PROCESSO_28");

            entity.HasIndex(e => e.CodClassificacaoClosing, "IDX_PROCESSO_29");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodComarca, e.CodVara, e.CodTipoVara, e.CodParteEmpresa, e.CodProcesso, e.NroProcessoCartorio, e.IndProcessoAtivo, e.DataCadastro, e.CodClassificacaoClosing, e.PerResponsOi }, "IDX_PROCESSO_30");

            entity.HasIndex(e => e.EsfCodEsfera, "IDX_PROCESSO_ESFERAS_3CON");

            entity.HasIndex(e => new { e.CodProfissional, e.IndProcessoAtivo, e.CodTipoProcesso, e.IndChecado }, "PROC_IX_01");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodParteEmpresa, e.IndProcessoAtivo, e.CodAcao, e.CodAssunto, e.CodComarca, e.CodTipoVara }, "PROC_IX_02");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodAcao, e.CodAssunto, e.CodComarca, e.CodProcesso }, "PROC_IX_03");

            entity.HasIndex(e => e.NumPastaEscritorio, "PROC_IX_04");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.IndMigrado, e.CodMigracaoSistema }, "PROC_IX_06");

            entity.HasIndex(e => new { e.NroProcessoCartorio, e.CodComarca, e.CodVara, e.CodTipoVara, e.CodTipoProcesso, e.CodProcesso }, "PROC_IX_07");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodParteEmpresa, e.IndProcessoAtivo, e.CodAcao, e.CodAssunto, e.CodComarca, e.CodTipoVara, e.NroProcessoCartorio }, "PROC_IX_08");

            entity.HasIndex(e => e.CodProcessoAdm, "PROC_IX_09");

            entity.HasIndex(e => new { e.NumProcessoAntigo, e.CodComarca, e.CodVara, e.CodTipoVara, e.CodTipoProcesso }, "PROC_IX_10");

            entity.HasIndex(e => e.NumProcessoAntigo, "PROC_IX_11");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.CodParteEmpresa, e.IndProcessoAtivo, e.CodAcao, e.CodAssunto, e.CodComarca, e.CodTipoVara, e.NumProcessoAntigo }, "PROC_IX_12");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.NroProcessoCartorio }, "PROC_IX_13");

            entity.HasIndex(e => new { e.CodTipoProcesso, e.NroProcessoCartorio, e.NumProcessoAntigo }, "PROC_IX_14");

            entity.HasIndex(e => e.CodRegional, "PROC_IX_15");

            entity.HasIndex(e => new { e.CodProcesso, e.CodTipoProcesso, e.CodParteEmpresa, e.CodAssunto, e.CodRiscoPerda, e.NroProcessoCartorio }, "PROC_IX_16");

            entity.HasIndex(e => e.CodVara, "QUEST_SX_IDX01_3CON");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .HasColumnName("COD_PROCESSO");

            entity.Property(e => e.ArenvIdAreaEnvolvida)
                .HasColumnType("NUMBER")
                .HasColumnName("ARENV_ID_AREA_ENVOLVIDA");

            entity.Property(e => e.CodAcao)
                .HasPrecision(4)
                .HasColumnName("COD_ACAO");

            entity.Property(e => e.CodAdvogado)
                .HasPrecision(4)
                .HasColumnName("COD_ADVOGADO");

            entity.Property(e => e.CodAssunto)
                .HasPrecision(4)
                .HasColumnName("COD_ASSUNTO");

            entity.Property(e => e.CodClassificacaoClosing)
                .HasPrecision(2)
                .HasColumnName("COD_CLASSIFICACAO_CLOSING");

            entity.Property(e => e.CodClassificacaoProcesso)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_CLASSIFICACAO_PROCESSO")
                .IsFixedLength();

            entity.Property(e => e.CodClienteInterno)
                .HasPrecision(4)
                .HasColumnName("COD_CLIENTE_INTERNO");

            entity.Property(e => e.CodComarca)
                .HasPrecision(4)
                .HasColumnName("COD_COMARCA");

            entity.Property(e => e.CodCompetencia)
                .HasPrecision(4)
                .HasColumnName("COD_COMPETENCIA");

            entity.Property(e => e.CodContador)
                .HasPrecision(6)
                .HasColumnName("COD_CONTADOR");

            entity.Property(e => e.CodCriticidade)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_CRITICIDADE")
                .IsFixedLength();

            entity.Property(e => e.CodDecisaoFinalizacao)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_DECISAO_FINALIZACAO");

            entity.Property(e => e.CodDocumentoDigitalizado)
                .HasPrecision(9)
                .HasColumnName("COD_DOCUMENTO_DIGITALIZADO");

            entity.Property(e => e.CodEscritorioAcompanhante)
                .HasPrecision(6)
                .HasColumnName("COD_ESCRITORIO_ACOMPANHANTE");

            entity.Property(e => e.CodEscritorioAdverso)
                .HasPrecision(8)
                .HasColumnName("COD_ESCRITORIO_ADVERSO");

            entity.Property(e => e.CodEstabelecimento)
                .HasPrecision(10)
                .HasColumnName("COD_ESTABELECIMENTO");

            entity.Property(e => e.CodEstado)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("COD_ESTADO");

            entity.Property(e => e.CodExpressinho)
                .HasPrecision(6)
                .HasColumnName("COD_EXPRESSINHO");

            entity.Property(e => e.CodFarol)
                .HasPrecision(1)
                .HasColumnName("COD_FAROL");

            entity.Property(e => e.CodMigracaoSistema)
                .HasColumnType("NUMBER")
                .HasColumnName("COD_MIGRACAO_SISTEMA");

            entity.Property(e => e.CodMunicipio)
                .HasPrecision(4)
                .HasColumnName("COD_MUNICIPIO");

            entity.Property(e => e.CodParteEmpresa)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE_EMPRESA");

            entity.Property(e => e.CodParteOrgao)
                .HasPrecision(10)
                .HasColumnName("COD_PARTE_ORGAO");

            entity.Property(e => e.CodPrescricao)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_PRESCRICAO")
                .IsFixedLength();

            entity.Property(e => e.CodProcedimento)
                .HasPrecision(4)
                .HasColumnName("COD_PROCEDIMENTO");

            entity.Property(e => e.CodProcessoAdm)
                .HasPrecision(8)
                .HasColumnName("COD_PROCESSO_ADM");

            entity.Property(e => e.CodProfissional)
                .HasPrecision(6)
                .HasColumnName("COD_PROFISSIONAL");

            entity.Property(e => e.CodRegional)
                .HasPrecision(4)
                .HasColumnName("COD_REGIONAL");

            entity.Property(e => e.CodRemuneracaoEscritorio)
                .HasPrecision(2)
                .HasColumnName("COD_REMUNERACAO_ESCRITORIO");

            entity.Property(e => e.CodResponsavelInterno)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_RESPONSAVEL_INTERNO");

            entity.Property(e => e.CodRiscoPerda)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_RISCO_PERDA")
                .IsFixedLength();

            entity.Property(e => e.CodRiscoPerdaAvaliado)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_RISCO_PERDA_AVALIADO")
                .IsFixedLength();

            entity.Property(e => e.CodRiscoPerdaPrev)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_RISCO_PERDA_PREV")
                .IsFixedLength();

            entity.Property(e => e.CodTipoContratacao)
                .HasPrecision(1)
                .HasColumnName("COD_TIPO_CONTRATACAO");

            entity.Property(e => e.CodTipoPenalidade)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_PENALIDADE");

            entity.Property(e => e.CodTipoPenalidadePrev)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_PENALIDADE_PREV");

            entity.Property(e => e.CodTipoProcesso)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_PROCESSO");

            entity.Property(e => e.CodTipoVara)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_VARA");

            entity.Property(e => e.CodUsuarioEnvioValidacao)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_ENVIO_VALIDACAO");

            entity.Property(e => e.CodUsuarioFinalizacao)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_FINALIZACAO");

            entity.Property(e => e.CodUsuarioInternet)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_INTERNET");

            entity.Property(e => e.CodUsuarioUltAlteracao)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_ULT_ALTERACAO");

            entity.Property(e => e.CodUsuarioValidacao)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_VALIDACAO");

            entity.Property(e => e.CodVara)
                .HasPrecision(3)
                .HasColumnName("COD_VARA");

            entity.Property(e => e.Comentario)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO");

            entity.Property(e => e.ComentarioAltEscritorio)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO_ALT_ESCRITORIO");

            entity.Property(e => e.ComentarioFinalizacao)
                .HasColumnType("CLOB")
                .HasColumnName("COMENTARIO_FINALIZACAO");

            entity.Property(e => e.DatAberturaProc)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ABERTURA_PROC");

            entity.Property(e => e.DatBaseMulta)
                .HasColumnType("DATE")
                .HasColumnName("DAT_BASE_MULTA");

            entity.Property(e => e.DatChecado)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CHECADO");

            entity.Property(e => e.DatConciliacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CONCILIACAO");

            entity.Property(e => e.DatContratacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CONTRATACAO");

            entity.Property(e => e.DatDecisaoRecurso)
                .HasColumnType("DATE")
                .HasColumnName("DAT_DECISAO_RECURSO");

            entity.Property(e => e.DatDistribuicao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_DISTRIBUICAO");

            entity.Property(e => e.DatEnvioEscritorio)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ENVIO_ESCRITORIO");

            entity.Property(e => e.DatEnvioValidacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ENVIO_VALIDACAO");

            entity.Property(e => e.DatFinalizacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FINALIZACAO");

            entity.Property(e => e.DatFinalizacaoContabil)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FINALIZACAO_CONTABIL");

            entity.Property(e => e.DatPrev)
                .HasColumnType("DATE")
                .HasColumnName("DAT_PREV");

            entity.Property(e => e.DatRecebimentoProc)
                .HasColumnType("DATE")
                .HasColumnName("DAT_RECEBIMENTO_PROC");

            entity.Property(e => e.DatUltAtualizacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULT_ATUALIZACAO");

            entity.Property(e => e.DatUltFinalizacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULT_FINALIZACAO");

            entity.Property(e => e.DatUltFinalizacaoContabil)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULT_FINALIZACAO_CONTABIL");

            entity.Property(e => e.DatValidacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VALIDACAO");

            entity.Property(e => e.DatVencMulta)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VENC_MULTA");

            entity.Property(e => e.DataApuracao)
                .HasColumnType("DATE")
                .HasColumnName("DATA_APURACAO");

            entity.Property(e => e.DataAvaliacaoRiscoPerda)
                .HasColumnType("DATE")
                .HasColumnName("DATA_AVALIACAO_RISCO_PERDA");

            entity.Property(e => e.DataCadastro)
                .HasColumnType("DATE")
                .HasColumnName("DATA_CADASTRO");

            entity.Property(e => e.DataExcLogica)
                .HasColumnType("DATE")
                .HasColumnName("DATA_EXC_LOGICA");

            entity.Property(e => e.DataFatoGerador)
                .HasColumnType("DATE")
                .HasColumnName("DATA_FATO_GERADOR");

            entity.Property(e => e.DataFinalizacaoTribunal)
                .HasColumnType("DATE")
                .HasColumnName("DATA_FINALIZACAO_TRIBUNAL");

            entity.Property(e => e.DataPublicacaoMulta)
                .HasColumnType("DATE")
                .HasColumnName("DATA_PUBLICACAO_MULTA");

            entity.Property(e => e.DataTransitoJulgado)
                .HasColumnType("DATE")
                .HasColumnName("DATA_TRANSITO_JULGADO");

            entity.Property(e => e.DataUltAtuEscritorio)
                .HasColumnType("DATE")
                .HasColumnName("DATA_ULT_ATU_ESCRITORIO");

            entity.Property(e => e.DescApuracaoContrato)
                .IsUnicode(false)
                .HasColumnName("DESC_APURACAO_CONTRATO");

            entity.Property(e => e.DescMotivoAvaliacaoRisco)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("DESC_MOTIVO_AVALIACAO_RISCO");

            entity.Property(e => e.DscDepositoCaucao)
                .HasMaxLength(600)
                .IsUnicode(false)
                .HasColumnName("DSC_DEPOSITO_CAUCAO");

            entity.Property(e => e.DscFianca)
                .HasMaxLength(600)
                .IsUnicode(false)
                .HasColumnName("DSC_FIANCA");

            entity.Property(e => e.DscHipoteca)
                .HasMaxLength(600)
                .IsUnicode(false)
                .HasColumnName("DSC_HIPOTECA");

            entity.Property(e => e.DscPenhora)
                .HasMaxLength(600)
                .IsUnicode(false)
                .HasColumnName("DSC_PENHORA");

            entity.Property(e => e.EndPaginaConsulta)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("END_PAGINA_CONSULTA");

            entity.Property(e => e.EsfCodEsfera)
                .HasPrecision(4)
                .HasColumnName("ESF_COD_ESFERA");

            entity.Property(e => e.FtgerIdFatoGerador)
                .HasColumnType("NUMBER")
                .HasColumnName("FTGER_ID_FATO_GERADOR");

            entity.Property(e => e.IdBo)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_BO");

            entity.Property(e => e.IdCamara)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_CAMARA");

            entity.Property(e => e.IdComplAreaEnvolvida)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_COMPL_AREA_ENVOLVIDA");

            entity.Property(e => e.IdFaseProcessual)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_FASE_PROCESSUAL");

            entity.Property(e => e.IdMotivoAlteracaoEscritorio)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_MOTIVO_ALTERACAO_ESCRITORIO");

            entity.Property(e => e.IdTese)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_TESE");

            entity.Property(e => e.IdTurmaRecursal)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_TURMA_RECURSAL");

            entity.Property(e => e.IdUltMovimentacaoPasta)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_ULT_MOVIMENTACAO_PASTA");

            entity.Property(e => e.IndApuracao)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_APURACAO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndAutorInfServicoPrestado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_AUTOR_INF_SERVICO_PRESTADO")
                .IsFixedLength();

            entity.Property(e => e.IndChecado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CHECADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndComarcaDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_COMARCA_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndConsideraCalculoMedia)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CONSIDERA_CALCULO_MEDIA")
                .HasDefaultValueSql("'S'\n")
                .IsFixedLength();

            entity.Property(e => e.IndConsiderarProvisao)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CONSIDERAR_PROVISAO")
                .IsFixedLength();

            entity.Property(e => e.IndDatAudienciaDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_DAT_AUDIENCIA_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndEmpresaCredoraDevedora)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_EMPRESA_CREDORA_DEVEDORA")
                .IsFixedLength();

            entity.Property(e => e.IndEmpresaGrupoDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_EMPRESA_GRUPO_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndEscritorioDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ESCRITORIO_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndEstratificado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ESTRATIFICADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndHaircut)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_HAIRCUT")
                .IsFixedLength();

            entity.Property(e => e.IndHoraAudienciaDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_HORA_AUDIENCIA_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndJuizadoVaraDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_JUIZADO_VARA_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndMediacao)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_MEDIACAO")
                .IsFixedLength();

            entity.Property(e => e.IndMigrado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_MIGRADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndNroProcessoDivergente)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_NRO_PROCESSO_DIVERGENTE")
                .IsFixedLength();

            entity.Property(e => e.IndPrioritaria)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PRIORITARIA")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndProcessoAtivo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCESSO_ATIVO")
                .HasDefaultValueSql("'S'")
                .IsFixedLength();

            entity.Property(e => e.IndProprioTerceiro)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROPRIO_TERCEIRO")
                .IsFixedLength();

            entity.Property(e => e.IndRecuperacaoJudicial)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_RECUPERACAO_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndSimplificado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_SIMPLIFICADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndTributarioPrincipal)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIO_PRINCIPAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndUsuarioInternet)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_USUARIO_INTERNET")
                .HasDefaultValueSql("'N'\n")
                .IsFixedLength();

            entity.Property(e => e.IndValidado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_VALIDADO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndValorObrigatorio)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_VALOR_OBRIGATORIO")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.NroPasta)
                .HasPrecision(6)
                .HasColumnName("NRO_PASTA");

            entity.Property(e => e.NroProcessoCartorio)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NRO_PROCESSO_CARTORIO");

            entity.Property(e => e.NumCaf)
                .HasPrecision(4)
                .HasColumnName("NUM_CAF");

            entity.Property(e => e.NumPastaEscritorio)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NUM_PASTA_ESCRITORIO");

            entity.Property(e => e.NumProcessoAntigo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NUM_PROCESSO_ANTIGO");

            entity.Property(e => e.NumeroProcSemFormatacao)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NUMERO_PROC_SEM_FORMATACAO");

            entity.Property(e => e.ObsExclusao)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("OBS_EXCLUSAO");

            entity.Property(e => e.ObsFatoGerador)
                .IsUnicode(false)
                .HasColumnName("OBS_FATO_GERADOR");

            entity.Property(e => e.Observacao)
                .IsUnicode(false)
                .HasColumnName("OBSERVACAO");

            entity.Property(e => e.PerReducao)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PER_REDUCAO")
                .HasDefaultValueSql("0\n");

            entity.Property(e => e.PerResponsOi)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PER_RESPONS_OI");

            entity.Property(e => e.PercHonorariosSucumbencia)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PERC_HONORARIOS_SUCUMBENCIA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.PrePos)
                .HasPrecision(2)
                .HasColumnName("PRE_POS");

            entity.Property(e => e.QteSalarioMinimoAtual)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("QTE_SALARIO_MINIMO_ATUAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.QteSalarioMinimoInicial)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("QTE_SALARIO_MINIMO_INICIAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ReorgIdRepresentanteOrgao)
                .HasColumnType("NUMBER")
                .HasColumnName("REORG_ID_REPRESENTANTE_ORGAO");

            entity.Property(e => e.SeqAndamento)
                .HasPrecision(4)
                .HasColumnName("SEQ_ANDAMENTO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracao)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoBloqueio)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_BLOQUEIO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoCcobranca)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_CCOBRANCA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoCconta)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_CCONTA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoCdebito)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_CDEBITO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoMpulso)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_MPULSO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoPcredito)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_PCREDITO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqApuracaoReparo)
                .HasPrecision(4)
                .HasColumnName("SEQ_APURACAO_REPARO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqAudiencia)
                .HasPrecision(4)
                .HasColumnName("SEQ_AUDIENCIA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqCompromisso)
                .HasPrecision(4)
                .HasColumnName("SEQ_COMPROMISSO");

            entity.Property(e => e.SeqContato)
                .HasPrecision(4)
                .HasColumnName("SEQ_CONTATO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqDesdobramento)
                .HasPrecision(4)
                .HasColumnName("SEQ_DESDOBRAMENTO")
                .HasDefaultValueSql("0 ");

            entity.Property(e => e.SeqFase)
                .HasPrecision(4)
                .HasColumnName("SEQ_FASE")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqLancamento)
                .HasPrecision(4)
                .HasColumnName("SEQ_LANCAMENTO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqLinha)
                .HasPrecision(4)
                .HasColumnName("SEQ_LINHA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqMovimentacao)
                .HasPrecision(6)
                .HasColumnName("SEQ_MOVIMENTACAO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqObservacao)
                .HasPrecision(4)
                .HasColumnName("SEQ_OBSERVACAO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqPagObjeto)
                .HasPrecision(4)
                .HasColumnName("SEQ_PAG_OBJETO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqPagamento)
                .HasPrecision(4)
                .HasColumnName("SEQ_PAGAMENTO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqPendencia)
                .HasPrecision(4)
                .HasColumnName("SEQ_PENDENCIA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqPrazo)
                .HasPrecision(4)
                .HasColumnName("SEQ_PRAZO")
                .HasDefaultValueSql("0\n");

            entity.Property(e => e.SeqServico)
                .HasPrecision(4)
                .HasColumnName("SEQ_SERVICO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqValor)
                .HasPrecision(4)
                .HasColumnName("SEQ_VALOR")
                .HasDefaultValueSql("0");

            entity.Property(e => e.SeqValorObjeto)
                .HasPrecision(4)
                .HasColumnName("SEQ_VALOR_OBJETO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.StpprIdSubtipoProcesso)
                .HasColumnType("NUMBER")
                .HasColumnName("STPPR_ID_SUBTIPO_PROCESSO");

            entity.Property(e => e.UsrCodUsuarioApuracao)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_APURACAO");

            entity.Property(e => e.UsrCodUsuarioCadastro)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_CADASTRO");

            entity.Property(e => e.UsrCodUsuarioExcLogica)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_EXC_LOGICA");

            entity.Property(e => e.UsrCodUsuarioUltAtuEscrit)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_ULT_ATU_ESCRIT");

            entity.Property(e => e.ValCausa)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_CAUSA");

            entity.Property(e => e.ValCausaEmSm)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_CAUSA_EM_SM")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValEconomico)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_ECONOMICO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValEconomicoCorrigido)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_ECONOMICO_CORRIGIDO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValMulta)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_MULTA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValMultaCorrigido)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_MULTA_CORRIGIDO")
                .HasDefaultValueSql("0\n");

            entity.Property(e => e.ValMultaInicial)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_MULTA_INICIAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValMultaInicialCorrigida)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_MULTA_INICIAL_CORRIGIDA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValMultaPosPagamento)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_MULTA_POS_PAGAMENTO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValMultaPrev)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_MULTA_PREV")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValRiscoPerCorPos)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PER_COR_POS");

            entity.Property(e => e.ValRiscoPerCorPre)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PER_COR_PRE");

            entity.Property(e => e.ValRiscoPerda)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PERDA")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValRiscoPerdaCorrigido)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PERDA_CORRIGIDO")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValRiscoPerdaPos)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PERDA_POS");

            entity.Property(e => e.ValRiscoPerdaPre)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VAL_RISCO_PERDA_PRE");

            entity.Property(e => e.ValSaldoBaseProvMediacao)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VAL_SALDO_BASE_PROV_MEDIACAO");

            entity.Property(e => e.ValorHonorSucumbCorr)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VALOR_HONOR_SUCUMB_CORR");

            entity.Property(e => e.ValorHonorSucumbCorrJuros)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_HONOR_SUCUMB_CORR_JUROS")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValorHonorSucumbJuros)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VALOR_HONOR_SUCUMB_JUROS");

            entity.Property(e => e.ValorHonorSucumbPrincipal)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_HONOR_SUCUMB_PRINCIPAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValorJurosAtual)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_JUROS_ATUAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValorJurosAtualPos)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_JUROS_ATUAL_POS");

            entity.Property(e => e.ValorJurosAtualPre)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_JUROS_ATUAL_PRE");

            entity.Property(e => e.ValorJurosInicial)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_JUROS_INICIAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValorSalarioMinimoAtual)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_SALARIO_MINIMO_ATUAL")
                .HasDefaultValueSql("0");

            entity.Property(e => e.ValorSalarioMinimoInicial)
                .HasColumnType("NUMBER(15,2)")
                .HasColumnName("VALOR_SALARIO_MINIMO_INICIAL")
                .HasDefaultValueSql("0");

            entity.HasOne(d => d.CodAcaoNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodAcao)
                .HasConstraintName("FK_ACAO_PROCESSO");

            entity.HasOne(d => d.CodAssuntoNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodAssunto)
                .HasConstraintName("FK_ASSUNTO_PROCESSO");

            entity.HasOne(d => d.CodComarcaNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodComarca)
                .HasConstraintName("FK_COMARCA_PROCESSO");

            entity.HasOne(d => d.CodContadorNavigation)
                .WithMany(p => p.ProcessoCodContadorNavigation)
                .HasForeignKey(d => d.CodContador)
                .HasConstraintName("FK_CONTADOR_PROCESSO");

            entity.HasOne(d => d.CodEscritorioAcompanhanteNavigation)
                .WithMany(p => p.ProcessoCodEscritorioAcompanhanteNavigation)
                .HasForeignKey(d => d.CodEscritorioAcompanhante)
                .HasConstraintName("FK_ESCRITORIO_ACOMP_PROC");

            entity.HasOne(d => d.CodEstabelecimentoNavigation)
                .WithMany(p => p.ProcessoCodEstabelecimentoNavigation)
                .HasForeignKey(d => d.CodEstabelecimento)
                .HasConstraintName("FK_PARTE_ESTABELECIMENTO");

            entity.HasOne(d => d.CodEstadoNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodEstado)
                .HasConstraintName("FK_ESTADO_PROC");

            entity.HasOne(d => d.CodMunicipioNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodMunicipio)
                .HasConstraintName("FK_MUNICIPIO_PROCESSO");

            entity.HasOne(d => d.CodParteEmpresaNavigation)
                .WithMany(p => p.ProcessoCodParteEmpresaNavigation)
                .HasForeignKey(d => d.CodParteEmpresa)
                .HasConstraintName("FK_PARTE_EMPRESA_PROC");

            entity.HasOne(d => d.CodParteOrgaoNavigation)
                .WithMany(p => p.ProcessoCodParteOrgaoNavigation)
                .HasForeignKey(d => d.CodParteOrgao)
                .HasConstraintName("FK_PARTE_ORGAO_PROC");

            entity.HasOne(d => d.CodProcedimentoNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodProcedimento)
                .HasConstraintName("FK_PROCEDIMENTO_PROC");

            entity.HasOne(d => d.CodProcessoAdmNavigation)
                .WithMany(p => p.InverseCodProcessoAdmNavigation)
                .HasForeignKey(d => d.CodProcessoAdm)
                .HasConstraintName("FK_PROCESSO_ADM_ASSOCIADO");

            entity.HasOne(d => d.CodProfissionalNavigation)
                .WithMany(p => p.ProcessoCodProfissionalNavigation)
                .HasForeignKey(d => d.CodProfissional)
                .HasConstraintName("FK_PROFISSIONAL_PROCESSO");

            entity.HasOne(d => d.CodRegionalNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => d.CodRegional)
                .HasConstraintName("FK_REGIONAL_PROCESSO");

            entity.HasOne(d => d.CodResponsavelInternoNavigation)
                .WithMany(p => p.ProcessoCodResponsavelInternoNavigation)
                .HasForeignKey(d => d.CodResponsavelInterno)
                .HasConstraintName("FK_RESPONSAVEL_INTERNO_PROC");

            entity.HasOne(d => d.CodUsuarioEnvioValidacaoNavigation)
                .WithMany(p => p.ProcessoCodUsuarioEnvioValidacaoNavigation)
                .HasForeignKey(d => d.CodUsuarioEnvioValidacao)
                .HasConstraintName("PROC_USR_FK_04");

            entity.HasOne(d => d.CodUsuarioFinalizacaoNavigation)
                .WithMany(p => p.ProcessoCodUsuarioFinalizacaoNavigation)
                .HasForeignKey(d => d.CodUsuarioFinalizacao)
                .HasConstraintName("PROC_USR_FK_06");

            entity.HasOne(d => d.CodUsuarioValidacaoNavigation)
                .WithMany(p => p.ProcessoCodUsuarioValidacaoNavigation)
                .HasForeignKey(d => d.CodUsuarioValidacao)
                .HasConstraintName("PROC_USR_FK_05");

            entity.HasOne(d => d.UsrCodUsuarioApuracaoNavigation)
                .WithMany(p => p.ProcessoUsrCodUsuarioApuracaoNavigation)
                .HasForeignKey(d => d.UsrCodUsuarioApuracao)
                .HasConstraintName("PROC_USR_FK");

            entity.HasOne(d => d.UsrCodUsuarioCadastroNavigation)
                .WithMany(p => p.ProcessoUsrCodUsuarioCadastroNavigation)
                .HasForeignKey(d => d.UsrCodUsuarioCadastro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PROC_USR_FK_01");

            entity.HasOne(d => d.UsrCodUsuarioExcLogicaNavigation)
                .WithMany(p => p.ProcessoUsrCodUsuarioExcLogicaNavigation)
                .HasForeignKey(d => d.UsrCodUsuarioExcLogica)
                .HasConstraintName("PROC_USR_FK_03");

            entity.HasOne(d => d.UsrCodUsuarioUltAtuEscritNavigation)
                .WithMany(p => p.ProcessoUsrCodUsuarioUltAtuEscritNavigation)
                .HasForeignKey(d => d.UsrCodUsuarioUltAtuEscrit)
                .HasConstraintName("PROC_USR_FK_02");

            entity.HasOne(d => d.CodCompetenciaNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => new { d.CodParteOrgao, d.CodCompetencia })
                .HasConstraintName("FK_COMPETENCIA_PROC");

            entity.HasOne(d => d.CodVaraNavigation)
                .WithMany(p => p.Processo)
                .HasForeignKey(d => new { d.CodComarca, d.CodVara, d.CodTipoVara })
                .HasConstraintName("FK_VARA_PROCESSO");

            entity.HasMany(d => d.TpempIdTipoParticEmpresa)
                .WithMany(p => p.ProcCodProcesso)
                .UsingEntity<Dictionary<string, object>>(
                    "ParticipacaoEmpresaProcesso",
                    l => l.HasOne<TipoParticipacaoEmpresa>().WithMany().HasForeignKey("TpempIdTipoParticEmpresa").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("PEMPR_TPEMP_FK"),
                    r => r.HasOne<Processo>().WithMany().HasForeignKey("ProcCodProcesso").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("PEMPR_PROC_FK"),
                    j =>
                    {
                        j.HasKey("ProcCodProcesso", "TpempIdTipoParticEmpresa").HasName("PEMPR_PK");

                        j.ToTable("PARTICIPACAO_EMPRESA_PROCESSO");

                        j.IndexerProperty<int>("ProcCodProcesso").HasPrecision(8).ValueGeneratedOnAdd().HasColumnName("PROC_COD_PROCESSO");

                        j.IndexerProperty<decimal>("TpempIdTipoParticEmpresa").HasColumnType("NUMBER").ValueGeneratedOnAdd().HasColumnName("TPEMP_ID_TIPO_PARTIC_EMPRESA");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Processo> entity);
    }
}
