// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.CriminalContext.Data;
using Oi.Juridico.Contextos.V2.CriminalContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Data.Configurations
{
    public partial class ProcedimentoConfiguration : IEntityTypeConfiguration<Procedimento>
    {
        public void Configure(EntityTypeBuilder<Procedimento> entity)
        {
            entity.HasKey(e => e.CodProcedimento);

            entity.ToTable("PROCEDIMENTO");

            entity.Property(e => e.CodProcedimento)
                .HasPrecision(4)
                .HasColumnName("COD_PROCEDIMENTO");

            entity.Property(e => e.CodTipoParticipacao1)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_PARTICIPACAO_1");

            entity.Property(e => e.CodTipoParticipacao2)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_PARTICIPACAO_2");

            entity.Property(e => e.DscProcedimento)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_PROCEDIMENTO");

            entity.Property(e => e.IndAdministrativo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ADMINISTRATIVO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .HasDefaultValueSql("'S' ")
                .IsFixedLength();

            entity.Property(e => e.IndCivelAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndCriminalAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndOrgao1)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ORGAO_1")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndOrgao2)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ORGAO_2")
                .HasDefaultValueSql("'N'")
                .IsFixedLength();

            entity.Property(e => e.IndPoloPassivoUnico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_POLO_PASSIVO_UNICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndProvisionado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROVISIONADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTrabalhistaAdm)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRABALHISTA_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.IndTributario)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.HasOne(d => d.CodTipoParticipacao1Navigation)
                .WithMany(p => p.ProcedimentoCodTipoParticipacao1Navigation)
                .HasForeignKey(d => d.CodTipoParticipacao1)
                .HasConstraintName("FK_TIPO_PARTICIP1_PROCEDIMENTO");

            entity.HasOne(d => d.CodTipoParticipacao2Navigation)
                .WithMany(p => p.ProcedimentoCodTipoParticipacao2Navigation)
                .HasForeignKey(d => d.CodTipoParticipacao2)
                .HasConstraintName("FK_TIPO_PARTICIP2_PROCEDIMENTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Procedimento> entity);
    }
}
