// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Entities;

public partial class AgendRelatAtmCcIndiceUf
{
    public decimal CodAgenIndiceUf { get; set; }

    public decimal CodAgendRelatorioAtm { get; set; }

    public decimal CodIndice { get; set; }

    public string Uf { get; set; }

    public virtual AgendRelatorioAtmCc CodAgendRelatorioAtmNavigation { get; set; }
}