// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Entities;

public partial class FechCivelConsMediaBase
{
    public decimal Id { get; set; }

    public decimal FechCivelConsMediaId { get; set; }

    public int CodEmpresaGrupo { get; set; }

    public string NomEmpresaGrupo { get; set; }

    public int CodProcesso { get; set; }
}