// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Entities;

public partial class FechCivelConsMedia
{
    public decimal Id { get; set; }

    public DateTime DataFechamento { get; set; }

    public byte NumMesesMediaHistorica { get; set; }

    public string IndMensal { get; set; }

    public DateTime? DataIndMensal { get; set; }

    public string IndBaseGerada { get; set; }

    public DateTime DataGeracao { get; set; }

    public string UsrCodUsuario { get; set; }

    public byte? EmpceCodEmpCentralizadora { get; set; }

    public decimal? ValorCorte { get; set; }

    public decimal? PercHaircut { get; set; }

    public decimal? CodSolicFechamentoCont { get; set; }

    public byte? CodTipoProcAssFechamento { get; set; }

    public DateTime? MesAnoFechamento { get; set; }
}