// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class AssuntoProcesso
    {
        public int ProcCodProcesso { get; set; }
        public short AssCodAssunto { get; set; }
        public string IndAcessoRestrito { get; set; }

        public virtual Assunto AssCodAssuntoNavigation { get; set; }
        public virtual Processo ProcCodProcessoNavigation { get; set; }
    }
}