// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class Competencia
    {
        public Competencia()
        {
            Processo = new HashSet<Processo>();
        }

        public long CodParte { get; set; }
        public short CodCompetencia { get; set; }
        public string NomCompetencia { get; set; }

        public virtual Parte CodParteNavigation { get; set; }
        public virtual ICollection<Processo> Processo { get; set; }
    }
}