// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class Estado
    {
        public Estado()
        {
            Comarca = new HashSet<Comarca>();
            Municipio = new HashSet<Municipio>();
            Parte = new HashSet<Parte>();
            Processo = new HashSet<Processo>();
            ProfissionalCodEstadoNavigation = new HashSet<Profissional>();
            ProfissionalCodEstadoOabNavigation = new HashSet<Profissional>();
        }

        public string CodEstado { get; set; }
        public string NomEstado { get; set; }
        public short? CodIndice { get; set; }
        public decimal? ValJuros { get; set; }
        public short? SeqMunicipio { get; set; }

        public virtual ICollection<Comarca> Comarca { get; set; }
        public virtual ICollection<Municipio> Municipio { get; set; }
        public virtual ICollection<Parte> Parte { get; set; }
        public virtual ICollection<Processo> Processo { get; set; }
        public virtual ICollection<Profissional> ProfissionalCodEstadoNavigation { get; set; }
        public virtual ICollection<Profissional> ProfissionalCodEstadoOabNavigation { get; set; }
    }
}