// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class ProcessoAcessoRecentes
    {
        public decimal Id { get; set; }
        public DateTime DataUltimoAcesso { get; set; }
        public int ProcCodProcesso { get; set; }
        public string UsrCodUsuario { get; set; }
        public short? TprocCodTipoProcesso { get; set; }

        public virtual Processo ProcCodProcessoNavigation { get; set; }
        public virtual AcaUsuario UsrCodUsuarioNavigation { get; set; }
    }
}