// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class Profissional
    {
        public Profissional()
        {
            ComarcaCodEscritorioCivelNavigation = new HashSet<Comarca>();
            ComarcaCodEscritorioTrabalhistaNavigation = new HashSet<Comarca>();
            ComarcaProfCodProfissionalCivEstrNavigation = new HashSet<Comarca>();
            ProcessoCodContadorNavigation = new HashSet<Processo>();
            ProcessoCodEscritorioAcompanhanteNavigation = new HashSet<Processo>();
            ProcessoCodProfissionalNavigation = new HashSet<Processo>();
            Vara = new HashSet<Vara>();
            CodUsuario = new HashSet<AcaUsuario>();
        }

        public int CodProfissional { get; set; }
        public string CodTipoPessoa { get; set; }
        public string CgcProfissional { get; set; }
        public string CpfProfissional { get; set; }
        public string NomProfissional { get; set; }
        public string EndProfissional { get; set; }
        public int? CodCep { get; set; }
        public string CodEstado { get; set; }
        public string DscCidade { get; set; }
        public string DscBairro { get; set; }
        public string Telefone { get; set; }
        public string DddTelefone { get; set; }
        public string Fax { get; set; }
        public string DddFax { get; set; }
        public string Celular { get; set; }
        public string DddCelular { get; set; }
        public string DscSite { get; set; }
        public string DscEmail { get; set; }
        public string IndEscritorio { get; set; }
        public string IndContador { get; set; }
        public string IndAreaCivel { get; set; }
        public string IndAreaTrabalhista { get; set; }
        public string IndAreaRegulatoria { get; set; }
        public string IndAreaTributaria { get; set; }
        public string IndAlterarValorInternet { get; set; }
        public short? SeqAdvogado { get; set; }
        public int? SeqDespesa { get; set; }
        public int? CodFornecedor { get; set; }
        public short? AlertaEm { get; set; }
        public string IndAdvogado { get; set; }
        public string NroOabAdvogado { get; set; }
        public string IndAreaJuizado { get; set; }
        public string CodEstadoOab { get; set; }
        public short? GljCodGrupoLoteJuizado { get; set; }
        public string IndCivelEstrategico { get; set; }
        public string IndCriminalAdm { get; set; }
        public string IndCriminalJudicial { get; set; }
        public string IndCivelAdm { get; set; }
        public string IndProcon { get; set; }
        public string IndPex { get; set; }
        public string IndContadorPex { get; set; }
        public string DescricaoEndAdicionais { get; set; }
        public string DescricaoTelAdicionais { get; set; }
        public string CodProfissionalSap { get; set; }
        public string IndAtivo { get; set; }
        //public string IndOfensor { get; set; }

        public virtual Estado CodEstadoNavigation { get; set; }
        public virtual Estado CodEstadoOabNavigation { get; set; }
        public virtual ICollection<Comarca> ComarcaCodEscritorioCivelNavigation { get; set; }
        public virtual ICollection<Comarca> ComarcaCodEscritorioTrabalhistaNavigation { get; set; }
        public virtual ICollection<Comarca> ComarcaProfCodProfissionalCivEstrNavigation { get; set; }
        public virtual ICollection<Processo> ProcessoCodContadorNavigation { get; set; }
        public virtual ICollection<Processo> ProcessoCodEscritorioAcompanhanteNavigation { get; set; }
        public virtual ICollection<Processo> ProcessoCodProfissionalNavigation { get; set; }
        public virtual ICollection<Vara> Vara { get; set; }

        public virtual ICollection<AcaUsuario> CodUsuario { get; set; }
    }
}