// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.CriminalContext.Entities
{
    public partial class VEscritorios
    {
        public int? CodProfissional { get; set; }
        public string CodTipoPessoa { get; set; }
        public string CgcProfissional { get; set; }
        public string NomProfissional { get; set; }
        public string EndProfissional { get; set; }
        public int? CodCep { get; set; }
        public string CodEstado { get; set; }
        public string DscCidade { get; set; }
        public string DscBairro { get; set; }
        public string Telefone { get; set; }
        public string DddTelefone { get; set; }
        public string Fax { get; set; }
        public string DddFax { get; set; }
        public string Celular { get; set; }
        public string DddCelular { get; set; }
        public string DscSite { get; set; }
        public string DscEmail { get; set; }
        public string IndAreaCivel { get; set; }
        public string IndAreaTrabalhista { get; set; }
        public string IndAreaRegulatoria { get; set; }
        public string IndAreaTributaria { get; set; }
        public string IndAlterarValorInternet { get; set; }
        public int? CodFornecedor { get; set; }
        public string IndAreaJuizado { get; set; }
        public string IndCivelEstrategico { get; set; }
        public string IndCriminalAdm { get; set; }
        public string IndCriminalJudicial { get; set; }
        public string IndCivelAdm { get; set; }
        public string CodContadorEscritorio { get; set; }
        public string CodProfissionalSap { get; set; }
        public string IndAtivo { get; set; }
    }
}