// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Data;
using Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.SolicitacaoAcessoContext.Data.Configurations
{
    public partial class StatusRenovacaoAcessoConfiguration : IEntityTypeConfiguration<StatusRenovacaoAcesso>
    {
        public void Configure(EntityTypeBuilder<StatusRenovacaoAcesso> entity)
        {
            entity.ToTable("STATUS_RENOVACAO_ACESSO");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("DESCRICAO");

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusRenovacaoAcesso> entity);
    }
}
