// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AgendCargaCompromissoContext.Entities
{
    public partial class AgendCargaComp
    {
        public int CodAgendCargaComp { get; set; }
        public string TipoProcesso { get; set; }
        public string ConfigExec { get; set; } 
        public int Status { get; set; }
        public string Mensagem { get; set; }
        public string MensagemErroTrace { get; set; }
        public DateTime? DatIniExec { get; set; }
        public DateTime? DatFimExec { get; set; }
        public string UsrCodUsuario { get; set; }
        public string NomArquivoBase { get; set; }
        public string EmpresaCentralizadora { get; set; }
        public string NomArquivoGerado { get; set; }
        public DateTime? DatSolicitacao { get; set; }
        public DateTime DatAgendamento { get; set; }
        public string Deletado { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
    }
}