// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.AtmCCContext.Data;
using Oi.Juridico.Contextos.V2.AtmCCContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Data.Configurations
{
    public partial class AgendRelatorioAtmCcConfiguration : IEntityTypeConfiguration<AgendRelatorioAtmCc>
    {
        public void Configure(EntityTypeBuilder<AgendRelatorioAtmCc> entity)
        {
            entity.HasKey(e => e.CodAgendRelatorioAtm).HasName("SYS_C00958413");

            entity.ToTable("AGEND_RELATORIO_ATM_CC");

            entity.Property(e => e.CodAgendRelatorioAtm)
            .ValueGeneratedOnAdd()
            .HasColumnType("NUMBER(38)")
            .HasColumnName("COD_AGEND_RELATORIO_ATM");
            entity.Property(e => e.CodFechContCcMedia)
            .ValueGeneratedOnAdd()
            .HasColumnType("NUMBER(38)")
            .HasColumnName("COD_FECH_CONT_CC_MEDIA");
            entity.Property(e => e.DatFechamento)
            .ValueGeneratedOnAdd()
            .HasDefaultValueSql("NULL")
            .HasColumnType("DATE")
            .HasColumnName("DAT_FECHAMENTO");
            entity.Property(e => e.DatFimExec)
            .ValueGeneratedOnAdd()
            .HasColumnType("DATE")
            .HasColumnName("DAT_FIM_EXEC");
            entity.Property(e => e.DatIniExec)
            .ValueGeneratedOnAdd()
            .HasColumnType("DATE")
            .HasColumnName("DAT_INI_EXEC");
            entity.Property(e => e.DatSolicitacao)
            .ValueGeneratedOnAdd()
            .HasColumnType("DATE")
            .HasColumnName("DAT_SOLICITACAO");
            entity.Property(e => e.EmpresaCentralizadora)
            .HasMaxLength(200)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("EMPRESA_CENTRALIZADORA");
            entity.Property(e => e.IndFechMensal)
            .HasMaxLength(50)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .IsFixedLength()
            .HasColumnName("IND_FECH_MENSAL");
            entity.Property(e => e.Mensagem)
            .HasMaxLength(400)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("MENSAGEM");
            entity.Property(e => e.MensagemErroTrace)
            .HasMaxLength(400)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("MENSAGEM_ERRO_TRACE");
            entity.Property(e => e.MesAnoContabil)
            .ValueGeneratedOnAdd()
            .HasColumnType("DATE")
            .HasColumnName("MES_ANO_CONTABIL");
            entity.Property(e => e.NomArquivoBase)
            .HasMaxLength(400)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("NOM_ARQUIVO_BASE");
            entity.Property(e => e.NomArquivoGerado)
            .HasMaxLength(400)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("NOM_ARQUIVO_GERADO");
            entity.Property(e => e.NomArquivoRelatorio)
            .HasMaxLength(400)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("NOM_ARQUIVO_RELATORIO");
            entity.Property(e => e.NumeroMeses)
              .HasColumnName("NUMEROMESES");
            entity.Property(e => e.Status)
            .HasPrecision(2)
            .ValueGeneratedOnAdd()
            .HasColumnName("STATUS"); 
            entity.Property(e => e.UsrCodUsuario)
            .IsRequired()
            .HasMaxLength(30)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .HasColumnName("USR_COD_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendRelatorioAtmCc> entity);
    }
}
