// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.AtmCCContext.Data;
using Oi.Juridico.Contextos.V2.AtmCCContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Data.Configurations
{
    public partial class AgendRelatAtmCcIndiceUfConfiguration : IEntityTypeConfiguration<AgendRelatAtmCcIndiceUf>
    {
        public void Configure(EntityTypeBuilder<AgendRelatAtmCcIndiceUf> entity)
        {
            entity.HasKey(e => e.CodAgenIndiceUf).HasName("SYS_C00958418");

            entity.ToTable("AGEND_RELAT_ATM_CC_INDICE_UF");

            entity.Property(e => e.CodAgenIndiceUf)
            .ValueGeneratedOnAdd()
            .HasColumnType("NUMBER(38)")
            .HasColumnName("COD_AGEN_INDICE_UF");
            entity.Property(e => e.CodAgendRelatorioAtm)
            .ValueGeneratedOnAdd()
            .HasColumnType("NUMBER(38)")
            .HasColumnName("COD_AGEND_RELATORIO_ATM");
            entity.Property(e => e.CodIndice)
            .ValueGeneratedOnAdd()
            .HasColumnType("NUMBER(38)")
            .HasColumnName("COD_INDICE");
            entity.Property(e => e.Uf)
            .IsRequired()
            .HasMaxLength(2)
            .IsUnicode(false)
            .ValueGeneratedOnAdd()
            .IsFixedLength()
            .HasColumnName("UF");

            entity.HasOne(d => d.CodAgendRelatorioAtmNavigation).WithMany(p => p.AgendRelatAtmCcIndiceUf)
            .HasForeignKey(d => d.CodAgendRelatorioAtm)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_AGEND_RELATORIO_ATM");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgendRelatAtmCcIndiceUf> entity);
    }
}
