// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.AtmCCContext.Data;
using Oi.Juridico.Contextos.V2.AtmCCContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Data.Configurations
{
    public partial class FechCivelConsMediaBaseConfiguration : IEntityTypeConfiguration<FechCivelConsMediaBase>
    {
        public void Configure(EntityTypeBuilder<FechCivelConsMediaBase> entity)
        {
            entity
            .HasNoKey()
            .ToTable("FECH_CIVEL_CONS_MEDIA_BASE");

            entity.HasIndex(e => e.Id, "FCCMB_PK").IsUnique();

            entity.Property(e => e.CodEmpresaGrupo)
            .HasPrecision(10)
            .HasColumnName("COD_EMPRESA_GRUPO");
            entity.Property(e => e.CodProcesso)
            .HasPrecision(8)
            .HasColumnName("COD_PROCESSO");
            entity.Property(e => e.FechCivelConsMediaId)
            .HasColumnType("NUMBER")
            .HasColumnName("FECH_CIVEL_CONS_MEDIA_ID");
            entity.Property(e => e.Id)
            .HasColumnType("NUMBER")
            .HasColumnName("ID");
            entity.Property(e => e.NomEmpresaGrupo)
            .IsRequired()
            .HasMaxLength(400)
            .IsUnicode(false)
            .HasColumnName("NOM_EMPRESA_GRUPO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FechCivelConsMediaBase> entity);
    }
}
