// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.AtmCCContext.Data;
using Oi.Juridico.Contextos.V2.AtmCCContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.AtmCCContext.Data.Configurations
{
    public partial class IndiceConfiguration : IEntityTypeConfiguration<Indice>
    {
        public void Configure(EntityTypeBuilder<Indice> entity)
        {
            entity.HasKey(e => e.CodIndice);

            entity.ToTable("INDICE");

            entity.Property(e => e.CodIndice)
            .HasPrecision(4)
            .HasColumnName("COD_INDICE");
            entity.Property(e => e.CodTipoIndice)
            .IsRequired()
            .HasMaxLength(1)
            .IsUnicode(false)
            .IsFixedLength()
            .HasColumnName("COD_TIPO_INDICE");
            entity.Property(e => e.CodValorIndice)
            .HasMaxLength(1)
            .IsUnicode(false)
            .HasDefaultValueSql("'F' ")
            .IsFixedLength()
            .HasColumnName("COD_VALOR_INDICE");
            entity.Property(e => e.IndAcumulado)
            .IsRequired()
            .HasMaxLength(1)
            .IsUnicode(false)
            .HasDefaultValueSql("'N' ")
            .IsFixedLength()
            .HasColumnName("IND_ACUMULADO");
            entity.Property(e => e.IndCalcAcumuladoAuto)
            .IsRequired()
            .HasMaxLength(1)
            .IsUnicode(false)
            .HasDefaultValueSql("'N' ")
            .IsFixedLength()
            .HasColumnName("IND_CALC_ACUMULADO_AUTO");
            entity.Property(e => e.NomIndice)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("NOM_INDICE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Indice> entity);
    }
}
