// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities
{
    public partial class AnexosDistEscritorio
    {
        public AnexosDistEscritorio()
        {
            ParamDistribuicaoAnexos = new HashSet<ParamDistribuicaoAnexos>();
        }

        public int IdAnexoDistEscritorio { get; set; }
        public string NomeArquivo { get; set; }
        public string Comentario { get; set; }
        public string NomeArquivoNas { get; set; }
        public DateTime LogDataOperacao { get; set; }
        public string LogCodUsuario { get; set; }

        public virtual AcaUsuario LogCodUsuarioNavigation { get; set; }
        public virtual ICollection<ParamDistribuicaoAnexos> ParamDistribuicaoAnexos { get; set; }
    }
}