// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities
{
    public partial class EmpresasCentralizadoras
    {
        public EmpresasCentralizadoras()
        {
            ParamDistribuicao = new HashSet<ParamDistribuicao>();
        }

        public short Codigo { get; set; }
        public string Nome { get; set; }
        public short NumOrdemClassifProcesso { get; set; }
        public short? NumAgenciaDepositaria { get; set; }
        public byte? NumDigitoAgenciaDepositaria { get; set; }
        public short? CodConvenioBb { get; set; }

        public virtual ICollection<ParamDistribuicao> ParamDistribuicao { get; set; }
    }
}