// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities
{
    public partial class ParamDistribuicao
    {
        public ParamDistribuicao()
        {
            ParamDistribEscritorio = new HashSet<ParamDistribEscritorio>();
            ParamDistribuicaoAnexos = new HashSet<ParamDistribuicaoAnexos>();
        }

        public int CodParamDistribuicao { get; set; }
        public string CodEstado { get; set; }
        public short? CodTipoProcesso { get; set; }
        public short? CodComarca { get; set; }
        public short? CodVara { get; set; }
        public short? CodTipoVara { get; set; }
        public short? CodEmpresaCentralizadora { get; set; }
        public string IndAtivo { get; set; }

        public virtual Vara Vara { get; set; }
        public virtual Comarca CodComarcaNavigation { get; set; }
        public virtual EmpresasCentralizadoras CodEmpresaCentralizadoraNavigation { get; set; }
        public virtual Estado CodEstadoNavigation { get; set; }
        public virtual TipoProcesso CodTipoProcessoNavigation { get; set; }
        public virtual ICollection<ParamDistribEscritorio> ParamDistribEscritorio { get; set; }
        public virtual ICollection<ParamDistribuicaoAnexos> ParamDistribuicaoAnexos { get; set; }
    }
}