// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.DistribuicaoProcessoEscritorioContext.Entities
{
    public partial class ParamDistribuicaoAnexos
    {
        public int CodParamDistribuicao { get; set; }
        public int IdAnexoDistEscritorio { get; set; }

        public virtual ParamDistribuicao CodParamDistribuicaoNavigation { get; set; }
        public virtual AnexosDistEscritorio IdAnexoDistEscritorioNavigation { get; set; }
    }
}