// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.EmpresaContratadaContext.Entities
{
    public partial class LogEmpTerceiroContratada
    {
        public int? CodEmpTerceiroContratada { get; set; }
        public string Operacao { get; set; }
        public DateTime? DatLog { get; set; }
        public string CodUsuario { get; set; }
        public int? CodEmpresaContratadaA { get; set; }
        public int? CodEmpresaContratadaD { get; set; }
        public int? CodTerceiroContratadoA { get; set; }
        public int? CodTerceiroContratadoD { get; set; }
        public string NomEmpresaContratadaA { get; set; }
        public string NomEmpresaContratadaD { get; set; }
        public string LoginTerceiroA { get; set; }
        public string LoginTerceiroD { get; set; }
    }
}