// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.EmpresaContratadaContext.Entities
{
    public partial class TerceiroContratado
    {
        public TerceiroContratado()
        {
            EmpresaTerceiroContratada = new HashSet<EmpresaTerceiroContratada>();
        }

        public int CodTerceiroContratado { get; set; }
        public string LoginTerceiro { get; set; }

        public virtual ICollection<EmpresaTerceiroContratada> EmpresaTerceiroContratada { get; set; }
    }
}