// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.StatusContatoContext.Data;
using Oi.Juridico.Contextos.V2.StatusContatoContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.StatusContatoContext.Data.Configurations
{
    public partial class StatusContatoConfiguration : IEntityTypeConfiguration<StatusContato>
    {
        public void Configure(EntityTypeBuilder<StatusContato> entity)
        {
            entity.HasKey(e => e.CodStatusContato);

            entity.ToTable("STATUS_CONTATO");

            entity.Property(e => e.CodStatusContato)
                .HasPrecision(4)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_STATUS_CONTATO");

            entity.Property(e => e.DscStatusContato)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("DSC_STATUS_CONTATO");

            entity.Property(e => e.IndAcordoRealizado)
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("IND_ACORDO_REALIZADO")
                .IsFixedLength();

            entity.Property(e => e.IndAtivo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("IND_ATIVO")
                .IsFixedLength();

            entity.Property(e => e.IndContatoRealizado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("IND_CONTATO_REALIZADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusContato> entity);
    }
}
