// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.RelatoriosContingenciaTrabalhistaContext.Entities
{
    public partial class ItemFechProvisaoPossiveis
    {
        public decimal Id { get; set; }
        public decimal IfptrIdItemFechProvTrab { get; set; }
        public short PedCodPedido { get; set; }
        public string NomePedido { get; set; }
        public decimal PercPerdaProvavel { get; set; }
        public decimal PercPerdaPossivel { get; set; }
        public decimal QtePedidosPossivelP { get; set; }
        public decimal QtePedidosProvavel { get; set; }
        public decimal QtePedidosRemoto { get; set; }
        public decimal ValorMedioDesemJurosPr { get; set; }
        public decimal ValorMedioDesemPrincipalPr { get; set; }
        public decimal? ValProvContJurosP { get; set; }
        public decimal? ValProvContPrincipalP { get; set; }
        public decimal PerResponsOi { get; set; }
        public decimal QtePedidosPossivelH { get; set; }
        public decimal? QteExpectativaPerdaH { get; set; }
        public decimal? ValProvContJurosH { get; set; }
        public decimal? ValProvContPrincipalH { get; set; }
        public decimal? ValProvContJuros { get; set; }
        public decimal? ValProvContPrincipal { get; set; }

        public virtual ItemFechamentoProvisaoTrab IfptrIdItemFechProvTrabNavigation { get; set; }
    }
}