// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Oi.Juridico.Contextos.RelatoriosContingenciaTrabalhistaContext.Entities
{
    public partial class ItemFechamentoProvisaoTrab
    {
        public ItemFechamentoProvisaoTrab()
        {
            ItemFechProvisaoPossiveis = new HashSet<ItemFechProvisaoPossiveis>();
            ItemFechProvisaoProvaveis = new HashSet<ItemFechProvisaoProvaveis>();
        }

        public decimal Id { get; set; }
        public decimal FptrIdFechProvisaoTrab { get; set; }
        public short EmpceCodEmpCentralizadora { get; set; }
        public string NomeEmpresaCentralizadora { get; set; }
        public long ParCodEmpresaGrupo { get; set; }
        public string NomeEmpresaGrupo { get; set; }
        public string IndProprioTerceiro { get; set; }
        public string CodRiscoPerda { get; set; }
        public decimal QtePedidosP { get; set; }
        public decimal ValorProvisaoJurosP { get; set; }
        public decimal ValorProvisaoPrincipalP { get; set; }
        public decimal ValTotalExpectativaPerdaP { get; set; }
        public decimal ValorTotalJurosPossivelP { get; set; }
        public decimal ValTotalPrincipalPossivelP { get; set; }
        public decimal ValorTotalJurosProvavelP { get; set; }
        public decimal ValTotalPrincipalProvavelP { get; set; }
        public decimal QteTotalPedidosPrP { get; set; }
        public decimal QteTotalPedidosPoP { get; set; }
        public decimal QteTotalPedidosReP { get; set; }
        public decimal QtePedidosH { get; set; }
        public decimal ValorProvisaoJurosH { get; set; }
        public decimal ValorProvisaoPrincipalH { get; set; }
        public decimal ValTotalExpectativaPerdaH { get; set; }
        public decimal ValorTotalJurosPossivelH { get; set; }
        public decimal ValTotalPrincipalPossivelH { get; set; }
        public decimal ValorTotalJurosProvavelH { get; set; }
        public decimal ValTotalPrincipalProvavelH { get; set; }
        public decimal QteTotalPedidosPrH { get; set; }
        public decimal QteTotalPedidosPoH { get; set; }
        public decimal QteTotalPedidosReH { get; set; }
        public decimal? QtePedidos { get; set; }
        public decimal? ValorProvisaoJuros { get; set; }
        public decimal? ValorProvisaoPrincipal { get; set; }
        public decimal? ValorTotalExpectativaPerda { get; set; }
        public decimal? ValorTotalJurosPossivel { get; set; }
        public decimal? ValorTotalPrincipalPossivel { get; set; }
        public decimal? ValorTotalJurosProvavel { get; set; }
        public decimal? ValorTotalPrincipalProvavel { get; set; }
        public decimal? QteTotalPedidosPr { get; set; }
        public decimal? QteTotalPedidosPo { get; set; }
        public decimal? QteTotalPedidosRe { get; set; }

        public virtual FechamentosProvisoesTrab FptrIdFechProvisaoTrabNavigation { get; set; }
        public virtual ICollection<ItemFechProvisaoPossiveis> ItemFechProvisaoPossiveis { get; set; }
        public virtual ICollection<ItemFechProvisaoProvaveis> ItemFechProvisaoProvaveis { get; set; }
    }
}