// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Oi.Juridico.Contextos.AtmJecContext.Data;
using Oi.Juridico.Contextos.AtmJecContext.Entities;
using System;


namespace Oi.Juridico.Contextos.AtmJecContext.Data.Configurations
{
    public partial class AcaUsuarioConfiguration : IEntityTypeConfiguration<AcaUsuario>
    {
        public void Configure(EntityTypeBuilder<AcaUsuario> entity)
        {
            entity.ToTable("ACA_USUARIO")
                .HasKey(e => e.CodUsuario);

            //entity.HasIndex(e => e.Perfil, "USR_IX_01");

            //entity.HasIndex(e => e.IndPerfilWeb, "USR_IX_02");

            //entity.HasIndex(e => new { e.IndAtivo, e.IndPerfilWeb }, "USR_IX_03");

            //entity.HasIndex(e => new { e.IndAtivo, e.CodSituacaoUsuario, e.CodUsuario, e.NomeUsuario }, "USR_IX_04");

            entity.Property(e => e.CodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO");

            entity.Property(e => e.AreaCodAreaJec)
                //.HasPrecision(4)
                .HasColumnName("AREA_COD_AREA_JEC");

            entity.Property(e => e.CodGestorDefault)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_GESTOR_DEFAULT");

            entity.Property(e => e.CodOrigemUsuario)
                .HasColumnType("NUMBER")
                .HasColumnName("COD_ORIGEM_USUARIO");

            entity.Property(e => e.CodPrioridadeExecRel)
                //.HasPrecision(2)
                .HasColumnName("COD_PRIORIDADE_EXEC_REL")
                .HasDefaultValueSql("5 ");

            entity.Property(e => e.CodSituacaoUsuario)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_SITUACAO_USUARIO")
                .IsFixedLength(true);

            entity.Property(e => e.CodTipoUsuarioPerfil)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("COD_TIPO_USUARIO_PERFIL")
                .IsFixedLength(true);

            entity.Property(e => e.CodUsuarioResponsavel)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_RESPONSAVEL");

            entity.Property(e => e.DatValidadeSenha)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VALIDADE_SENHA");

            entity.Property(e => e.DataDesativacao)
                .HasColumnType("DATE")
                .HasColumnName("DATA_DESATIVACAO")
                .HasDefaultValueSql("SYSDATE ");

            entity.Property(e => e.DscEmail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_EMAIL");

            entity.Property(e => e.IdBo)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_BO");

            entity.Property(e => e.IndAdmAprovadorAcessos)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ADM_APROVADOR_ACESSOS")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndAtivo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndAutorizaServProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_AUTORIZA_SERV_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndAutorizaServico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_AUTORIZA_SERVICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndBloqueado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_BLOQUEADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndCivel)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndCivelAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndCivelEstrategico)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CIVEL_ESTRATEGICO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndControladoria)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CONTROLADORIA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndCriminalAdm)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_ADM")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndCriminalJudicial)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_CRIMINAL_JUDICIAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndGestorAprovadorAcessos)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_GESTOR_APROVADOR_ACESSOS")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndInativacaoAutomatica)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_INATIVACAO_AUTOMATICA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndInativacaoManual)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_INATIVACAO_MANUAL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndJuizado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_JUIZADO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndMudarSenha)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_MUDAR_SENHA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndOperadorCadastro)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_OPERADOR_CADASTRO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndOperadorValidacaoCcons)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_OPERADOR_VALIDACAO_CCONS")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndOperadorValidacaoJec)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_OPERADOR_VALIDACAO_JEC")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndPerfilWeb)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PERFIL_WEB")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndPex)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PEX")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndPreposto)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PREPOSTO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndProcon)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_PROCON")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndRegulatorio)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_REGULATORIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndRestrito)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_RESTRITO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndTrabalhista)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRABALHISTA")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndTributario)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_TRIBUTARIO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndUsuarioEstrangeiro)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_USUARIO_ESTRANGEIRO")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.IndUsuarioInternet)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_USUARIO_INTERNET")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.NomeUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOME_USUARIO");

            entity.Property(e => e.NumCpf)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("NUM_CPF")
                .IsFixedLength(true);

            entity.Property(e => e.ObsUsuario)
                .IsUnicode(false)
                .HasColumnName("OBS_USUARIO");

            entity.Property(e => e.Perfil)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("PERFIL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength(true);

            entity.Property(e => e.Senha)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SENHA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AcaUsuario> entity);
    }
}
