// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacaoTrabalhistaContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioMovimentacaoTrabalhistaContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacaoTrabalhistaContext.Data.Configurations
{
    public partial class AcaUsuarioConfiguration : IEntityTypeConfiguration<AcaUsuario>
    {
        public void Configure(EntityTypeBuilder<AcaUsuario> entity)
        {
            entity.HasKey(e => e.CodUsuario);

            entity.ToTable("ACA_USUARIO");

            entity.Property(e => e.CodUsuario)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO");

            entity.Property(e => e.AreaCodAreaJec)
                .HasPrecision(4)
                .ValueGeneratedOnAdd()
                .HasColumnName("AREA_COD_AREA_JEC");

            entity.Property(e => e.CodOrigemUsuario)
                .HasColumnType("NUMBER")                
                .HasColumnName("COD_ORIGEM_USUARIO");

            entity.Property(e => e.IdBo)
                .HasColumnType("NUMBER")                
                .HasColumnName("ID_BO");

            entity.Property(e => e.NomeUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)                
                .HasColumnName("NOME_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AcaUsuario> entity);
    }
}
