// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data.Configurations
{
    public partial class EscritorioEstadoConfiguration : IEntityTypeConfiguration<EscritorioEstado>
    {
        public void Configure(EntityTypeBuilder<EscritorioEstado> entity)
        {
            entity.HasKey(e => new { e.CodProfissional, e.CodEstado, e.CodTipoProcesso })
                .HasName("ESCREST_PK");

            entity.ToTable("ESCRITORIO_ESTADO");

            entity.Property(e => e.CodProfissional)
                .HasPrecision(6)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_PROFISSIONAL");

            entity.Property(e => e.CodEstado)
                .HasMaxLength(3)
                .IsUnicode(false)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_ESTADO");

            entity.Property(e => e.CodTipoProcesso)
                .HasPrecision(2)
                .ValueGeneratedOnAdd()
                .HasColumnName("COD_TIPO_PROCESSO");

            entity.HasOne(d => d.CodProfissionalNavigation)
                .WithMany(p => p.EscritorioEstado)
                .HasForeignKey(d => d.CodProfissional)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROF_ESCREST");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EscritorioEstado> entity);
    }
}
