// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data.Configurations
{
    public partial class FornecedorConfiguration : IEntityTypeConfiguration<Fornecedor>
    {
        public void Configure(EntityTypeBuilder<Fornecedor> entity)
        {
            entity.HasKey(e => e.CodFornecedor)
                .HasName("PK_FORNECEDOR_SAP");

            entity.ToTable("FORNECEDOR");

            entity.HasIndex(e => e.CodFornecedorSap, "FOR_IX_01");

            entity.HasIndex(e => e.NumCnpj, "FOR_IX_02");

            entity.HasIndex(e => e.CodFornecedorSapR2, "FOR_IX_03");

            entity.HasIndex(e => e.CodEscritorio, "IDX_FORNECEDOR_01");

            entity.HasIndex(e => e.CodProfissional, "IDX_FORNECEDOR_02");

            entity.HasIndex(e => e.CodBanco, "IDX_FORNECEDOR_03");

            entity.Property(e => e.CodFornecedor)
                .HasPrecision(8)
                .ValueGeneratedNever()
                .HasColumnName("COD_FORNECEDOR");

            entity.Property(e => e.CodBanco)
                .HasPrecision(3)
                .HasColumnName("COD_BANCO");

            entity.Property(e => e.CodEscritorio)
                .HasPrecision(6)
                .HasColumnName("COD_ESCRITORIO");

            entity.Property(e => e.CodFornecedorSap)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("COD_FORNECEDOR_SAP");

            entity.Property(e => e.CodFornecedorSapR2)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("COD_FORNECEDOR_SAP_R2");

            entity.Property(e => e.CodProfissional)
                .HasPrecision(6)
                .HasColumnName("COD_PROFISSIONAL");

            entity.Property(e => e.CodTipoFornecedor)
                .HasPrecision(2)
                .HasColumnName("COD_TIPO_FORNECEDOR");

            entity.Property(e => e.DataAtuManualIndAtivo)
                .HasColumnType("DATE")
                .HasColumnName("DATA_ATU_MANUAL_IND_ATIVO");

            entity.Property(e => e.DataCartaFianca)
                .HasColumnType("DATE")
                .HasColumnName("DATA_CARTA_FIANCA");

            entity.Property(e => e.IndAtivoSap)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_ATIVO_SAP")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.NomFornecedor)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_FORNECEDOR");

            entity.Property(e => e.NumCnpj)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("NUM_CNPJ");

            entity.Property(e => e.UsuCodUsuAtuManuIndAtivo)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USU_COD_USU_ATU_MANU_IND_ATIVO");

            entity.Property(e => e.ValorCartaFianca)
                .HasColumnType("NUMBER(13,2)")
                .HasColumnName("VALOR_CARTA_FIANCA")
                .HasDefaultValueSql("0   ");

            entity.HasOne(d => d.CodEscritorioNavigation)
                .WithMany(p => p.FornecedorCodEscritorioNavigation)
                .HasForeignKey(d => d.CodEscritorio)
                .HasConstraintName("FK_ESCRITORIO_FORNECEDOR");

            entity.HasOne(d => d.CodProfissionalNavigation)
                .WithMany(p => p.FornecedorCodProfissionalNavigation)
                .HasForeignKey(d => d.CodProfissional)
                .HasConstraintName("FK_PROFISSIONAL_FORNECEDOR");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Fornecedor> entity);
    }
}
