// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data;
using Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.ManutencaoEscritorioContext.Data.Configurations
{
    public partial class ParamDistribEscritorioConfiguration : IEntityTypeConfiguration<ParamDistribEscritorio>
    {
        public void Configure(EntityTypeBuilder<ParamDistribEscritorio> entity)
        {
            entity.HasKey(e => e.CodParamDistribEscrit);

            entity.ToTable("PARAM_DISTRIB_ESCRITORIO");

            entity.HasIndex(e => new { e.CodParamDistribuicao, e.CodProfissional }, "KEY_PARAM_DISTRIB_ESCRITORIO")
                .IsUnique();

            entity.Property(e => e.CodParamDistribEscrit)
                .HasPrecision(15)
                .HasColumnName("COD_PARAM_DISTRIB_ESCRIT");

            entity.Property(e => e.CodParamDistribuicao)
                .HasPrecision(8)
                .HasColumnName("COD_PARAM_DISTRIBUICAO");

            entity.Property(e => e.CodProfissional)
                .HasPrecision(6)
                .HasColumnName("COD_PROFISSIONAL");

            entity.Property(e => e.CodSolicitante)
                .HasPrecision(8)
                .HasColumnName("COD_SOLICITANTE");

            entity.Property(e => e.DatVigenciaFinal)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VIGENCIA_FINAL");

            entity.Property(e => e.DatVigenciaInicial)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VIGENCIA_INICIAL");

            entity.Property(e => e.PorcentagemProcessos)
                .HasColumnType("NUMBER(5,2)")
                .HasColumnName("PORCENTAGEM_PROCESSOS");

            entity.Property(e => e.Prioridade)
                .HasPrecision(5)
                .HasColumnName("PRIORIDADE");

            entity.HasOne(d => d.CodParamDistribuicaoNavigation)
                .WithMany(p => p.ParamDistribEscritorio)
                .HasForeignKey(d => d.CodParamDistribuicao)
                .HasConstraintName("FK_PARAM_DISTRIB_ESCRITORIO_C2");

            entity.HasOne(d => d.CodProfissionalNavigation)
                .WithMany(p => p.ParamDistribEscritorio)
                .HasForeignKey(d => d.CodProfissional)
                .HasConstraintName("FK_PARAM_DISTRIB_ESCRITORIO_CO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParamDistribEscritorio> entity);
    }
}
