// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacaoTrabalhistaContext.Entities
{
    public partial class AcaUsuario
    {
        public AcaUsuario()
        {
            AgendMovimentacaoTrab = new HashSet<AgendMovimentacaoTrab>();
        }

        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public short? AreaCodAreaJec { get; set; }
        public decimal? IdBo { get; set; }
        public decimal? CodOrigemUsuario { get; set; }

        public virtual ICollection<AgendMovimentacaoTrab> AgendMovimentacaoTrab { get; set; }
    }
}