// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioMovimentacaoTrabalhistaContext.Entities
{
    public partial class VSoliFechMovRelTrab
    {
        public DateTime DataFechamento { get; set; }
        public DateTime? DataExecucao { get; set; }
        public short NumeroMeses { get; set; }
        public string IndFechamentoMensal { get; set; }
        public string EmpresasGrupo { get; set; }
        public bool? IndFechamentoParcial { get; set; }
        public byte CodTipoOutlier { get; set; }
        public decimal? ValOutlier { get; set; }
    }
}