// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities
{
    public partial class AgPexRelSolicStatus
    {
        public decimal Id { get; set; }
        public decimal AgPexRelSolicId { get; set; }
        public decimal CodStaRelSolic { get; set; }
        public string NomStaRelSolic { get; set; }

        public virtual AgPexRelSolic AgPexRelSolic { get; set; }
    }
}