// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities
{
    public partial class AgPexRelSolicResultado
    {
        public decimal Id { get; set; }
        public decimal AgPexRelSolicId { get; set; }
        public int? CodSolicLancamento { get; set; }
        public int? CodProcesso { get; set; }
        public byte? CodTipoSolicitacao { get; set; }
        public string DescTipoSolicitacao { get; set; }
        public decimal? CodStatusSolicitacao { get; set; }
        public string StatusSolicitacao { get; set; }
        public DateTime? DatCriacao { get; set; }
        public string UsrCodUsuarioCriacao { get; set; }
        public DateTime? DatEnvioOi { get; set; }
        public string CodUsuarioRespAtual { get; set; }
        public string UsrCodUsuarioEnvio { get; set; }
        public string NumProcesso { get; set; }
        public string UfComarca { get; set; }
        public decimal? CodComarca { get; set; }
        public string NomComarca { get; set; }
        public decimal? CodTipoVara { get; set; }
        public string NomTipoVara { get; set; }
        public string NomTese { get; set; }
        public string NomAutor { get; set; }
        public decimal? CodSolicLancProcesso { get; set; }
        public string IndTipoLancamento { get; set; }
        public string TipoLancamento { get; set; }
        public DateTime? DatLancamento { get; set; }
        public decimal? CodCatPagamento { get; set; }
        public string DscCatPagamento { get; set; }
        public decimal? BcoCodBancoDep { get; set; }
        public decimal? ValDeposito { get; set; }
        public decimal? ValSaldoGarantia { get; set; }
        public decimal? ValPrincipalPag { get; set; }
        public decimal? ValJurosPag { get; set; }
        public decimal? ValCorrecaoPag { get; set; }
        public decimal? ValIrPag { get; set; }
        public decimal? ValPrincipalRec { get; set; }
        public decimal? ValJurosRec { get; set; }
        public decimal? ValCorrecaoRec { get; set; }
        public decimal? ValIrRec { get; set; }
        public decimal? ValLevRec { get; set; }
        public decimal? ValTarifaRec { get; set; }
        public decimal? ValHonorarioRec { get; set; }
        public decimal? ValReembolsoRec { get; set; }
        public string NumeroAlvara { get; set; }
        public DateTime? DataEmissaoAlvara { get; set; }
        public decimal? ValMulta { get; set; }
        public string DscTipoResgate { get; set; }
        public string TipoTransferencia { get; set; }
        public decimal? ValTotalKit { get; set; }
        public decimal? ValTarifaTotal { get; set; }
        public decimal? CodBanco { get; set; }
        public short? NumAgencia { get; set; }
        public string NumConta { get; set; }
        public string NumContaChequeOi { get; set; }
        public DateTime? DatChequeTed { get; set; }
        public decimal? QtdContrato { get; set; }
        public string DscFormaPagamento { get; set; }
        public string NomFornecedor { get; set; }
        public string DscCentroCusto { get; set; }
        public DateTime? DatVencimentoDoc { get; set; }
        public string IndMalote { get; set; }
        public string ComentarioBo { get; set; }
        public string ComentarioEscritorio { get; set; }
        public string DscHistorico { get; set; }
        public string MotivoRejeicao { get; set; }
        public string IndEncerrarProcJuridico { get; set; }
        public string IndEfetivadoParcial { get; set; }
        public string IndCancelado { get; set; }
        public string MotivoCancelProcesso { get; set; }
        public string CreditoConfirmado { get; set; }
        public DateTime? DatLocalizacaoCred { get; set; }
        public string ValRetificado { get; set; }

        public virtual AgPexRelSolic AgPexRelSolic { get; set; }
    }
}