// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities
{
    public partial class ColunasPexRelSolic
    {
        public decimal IdColRelSolic { get; set; }
        public string NomColRelSolic { get; set; }
        public string CampoAtivoRelSolic { get; set; }
    }
}