// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class AgPexRelSolicUfConfiguration : IEntityTypeConfiguration<AgPexRelSolicUf>
    {
        public void Configure(EntityTypeBuilder<AgPexRelSolicUf> entity)
        {
            entity.ToTable("AG_PEX_REL_SOLIC_UF");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.AgPexRelSolicId)
                .HasColumnType("NUMBER")
                .HasColumnName("AG_PEX_REL_SOLIC_ID");

            entity.Property(e => e.CodUfRelSolic)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("COD_UF_REL_SOLIC")
                .IsFixedLength();

            entity.Property(e => e.NomUfRelSolic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("NOM_UF_REL_SOLIC");

            entity.HasOne(d => d.AgPexRelSolic)
                .WithMany(p => p.AgPexRelSolicUf)
                .HasForeignKey(d => d.AgPexRelSolicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_APRSU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgPexRelSolicUf> entity);
    }
}
