// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class AgPexRelSolicDataConfiguration : IEntityTypeConfiguration<AgPexRelSolicData>
    {
        public void Configure(EntityTypeBuilder<AgPexRelSolicData> entity)
        {
            entity.ToTable("AG_PEX_REL_SOLIC_DATA");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.AgPexRelSolicId)
                .HasColumnType("NUMBER")
                .HasColumnName("AG_PEX_REL_SOLIC_ID");

            entity.Property(e => e.DatSolicFim)
                .HasColumnType("DATE")
                .HasColumnName("DAT_SOLIC_FIM");

            entity.Property(e => e.DatSolicIni)
                .HasColumnType("DATE")
                .HasColumnName("DAT_SOLIC_INI");

            entity.Property(e => e.DatVencimentoFim)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VENCIMENTO_FIM");

            entity.Property(e => e.DatVencimentoIni)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VENCIMENTO_INI");

            entity.HasOne(d => d.AgPexRelSolic)
                .WithMany(p => p.AgPexRelSolicData)
                .HasForeignKey(d => d.AgPexRelSolicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_APRSDATA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgPexRelSolicData> entity);
    }
}
