// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class AgPexRelSolicConfiguration : IEntityTypeConfiguration<AgPexRelSolic>
    {
        public void Configure(EntityTypeBuilder<AgPexRelSolic> entity)
        {
            entity.ToTable("AG_PEX_REL_SOLIC");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            entity.Property(e => e.DatAgendamentoFim)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO_FIM");

            entity.Property(e => e.DatAgendamentoIni)
                .HasColumnType("DATE")
                .HasColumnName("DAT_AGENDAMENTO_INI");

            entity.Property(e => e.DatCriacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CRIACAO");

            entity.Property(e => e.DatFimExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_FIM_EXECUCAO");

            entity.Property(e => e.DatInicioExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_INICIO_EXECUCAO");

            entity.Property(e => e.DatUltAlteracao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULT_ALTERACAO");

            entity.Property(e => e.DatUltExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ULT_EXECUCAO");

            entity.Property(e => e.DataProxExecucao)
                .HasColumnType("DATE")
                .HasColumnName("DATA_PROX_EXECUCAO");

            entity.Property(e => e.DscAgendamento)
                .IsUnicode(false)
                .HasColumnName("DSC_AGENDAMENTO");

            entity.Property(e => e.IndExecutarDiaUtil)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("IND_EXECUTAR_DIA_UTIL")
                .HasDefaultValueSql("'N' ")
                .IsFixedLength();

            entity.Property(e => e.MsgErro)
                .HasColumnType("CLOB")
                .HasColumnName("MSG_ERRO");

            entity.Property(e => e.NomAgendamento)
                .IsUnicode(false)
                .HasColumnName("NOM_AGENDAMENTO");

            entity.Property(e => e.NomArqGerado)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NOM_ARQ_GERADO");

            entity.Property(e => e.NumDiaAgendamento)
                .HasPrecision(2)
                .HasColumnName("NUM_DIA_AGENDAMENTO");

            entity.Property(e => e.NumMesAgendamento)
                .HasPrecision(2)
                .HasColumnName("NUM_MES_AGENDAMENTO");

            entity.Property(e => e.NumSemanaAgendamento)
                .HasPrecision(1)
                .HasColumnName("NUM_SEMANA_AGENDAMENTO");

            entity.Property(e => e.StatusExecucao)
                .HasPrecision(2)
                .HasColumnName("STATUS_EXECUCAO");

            entity.Property(e => e.TipAgendamento)
                .HasPrecision(3)
                .HasColumnName("TIP_AGENDAMENTO");

            entity.Property(e => e.UsrCodUsuario)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO");

            entity.HasOne(d => d.UsrCodUsuarioNavigation)
                .WithMany(p => p.AgPexRelSolic)
                .HasForeignKey(d => d.UsrCodUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AG_PEX_REL_SOLIC_USUARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgPexRelSolic> entity);
    }
}
