// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class AgPexRelSolicResultadoConfiguration : IEntityTypeConfiguration<AgPexRelSolicResultado>
    {
        public void Configure(EntityTypeBuilder<AgPexRelSolicResultado> entity)
        {
            entity.ToTable("AG_PEX_REL_SOLIC_RESULTADO");

            entity.Property(e => e.Id)
                .HasColumnType("NUMBER")
                .HasColumnName("ID");

            entity.Property(e => e.AgPexRelSolicId)
                .HasColumnType("NUMBER")
                .HasColumnName("AG_PEX_REL_SOLIC_ID");

            entity.Property(e => e.BcoCodBancoDep)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("BCO_COD_BANCO_DEP");

            entity.Property(e => e.CodBanco)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_BANCO");

            entity.Property(e => e.CodCatPagamento)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_CAT_PAGAMENTO");

            entity.Property(e => e.CodComarca)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_COMARCA");

            entity.Property(e => e.CodProcesso)
                .HasPrecision(8)
                .HasColumnName("COD_PROCESSO");

            entity.Property(e => e.CodSolicLancProcesso)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_SOLIC_LANC_PROCESSO");

            entity.Property(e => e.CodSolicLancamento)
                .HasPrecision(8)
                .HasColumnName("COD_SOLIC_LANCAMENTO");

            entity.Property(e => e.CodStatusSolicitacao)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_STATUS_SOLICITACAO");

            entity.Property(e => e.CodTipoSolicitacao)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_SOLICITACAO");

            entity.Property(e => e.CodTipoVara)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("COD_TIPO_VARA");

            entity.Property(e => e.CodUsuarioRespAtual)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("COD_USUARIO_RESP_ATUAL");

            entity.Property(e => e.ComentarioBo)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO_BO");

            entity.Property(e => e.ComentarioEscritorio)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO_ESCRITORIO");

            entity.Property(e => e.CreditoConfirmado)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("CREDITO_CONFIRMADO");

            entity.Property(e => e.DatChequeTed)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CHEQUE_TED");

            entity.Property(e => e.DatCriacao)
                .HasColumnType("DATE")
                .HasColumnName("DAT_CRIACAO");

            entity.Property(e => e.DatEnvioOi)
                .HasColumnType("DATE")
                .HasColumnName("DAT_ENVIO_OI");

            entity.Property(e => e.DatLancamento)
                .HasColumnType("DATE")
                .HasColumnName("DAT_LANCAMENTO");

            entity.Property(e => e.DatLocalizacaoCred)
                .HasColumnType("DATE")
                .HasColumnName("DAT_LOCALIZACAO_CRED");

            entity.Property(e => e.DatVencimentoDoc)
                .HasColumnType("DATE")
                .HasColumnName("DAT_VENCIMENTO_DOC");

            entity.Property(e => e.DataEmissaoAlvara)
                .HasColumnType("DATE")
                .HasColumnName("DATA_EMISSAO_ALVARA");

            entity.Property(e => e.DescTipoSolicitacao)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("DESC_TIPO_SOLICITACAO");

            entity.Property(e => e.DscCatPagamento)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_CAT_PAGAMENTO");

            entity.Property(e => e.DscCentroCusto)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_CENTRO_CUSTO");

            entity.Property(e => e.DscFormaPagamento)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_FORMA_PAGAMENTO");

            entity.Property(e => e.DscHistorico)
                .IsUnicode(false)
                .HasColumnName("DSC_HISTORICO");

            entity.Property(e => e.DscTipoResgate)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DSC_TIPO_RESGATE");

            entity.Property(e => e.IndCancelado)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("IND_CANCELADO")
                .IsFixedLength();

            entity.Property(e => e.IndEfetivadoParcial)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("IND_EFETIVADO_PARCIAL")
                .IsFixedLength();

            entity.Property(e => e.IndEncerrarProcJuridico)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("IND_ENCERRAR_PROC_JURIDICO")
                .IsFixedLength();

            entity.Property(e => e.IndMalote)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("IND_MALOTE")
                .IsFixedLength();

            entity.Property(e => e.IndTipoLancamento)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IND_TIPO_LANCAMENTO");

            entity.Property(e => e.MotivoCancelProcesso)
                .IsUnicode(false)
                .HasColumnName("MOTIVO_CANCEL_PROCESSO");

            entity.Property(e => e.MotivoRejeicao)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("MOTIVO_REJEICAO");

            entity.Property(e => e.NomAutor)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_AUTOR");

            entity.Property(e => e.NomComarca)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_COMARCA");

            entity.Property(e => e.NomFornecedor)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_FORNECEDOR");

            entity.Property(e => e.NomTese)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_TESE");

            entity.Property(e => e.NomTipoVara)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NOM_TIPO_VARA");

            entity.Property(e => e.NumAgencia)
                .HasPrecision(5)
                .HasColumnName("NUM_AGENCIA");

            entity.Property(e => e.NumConta)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NUM_CONTA");

            entity.Property(e => e.NumContaChequeOi)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NUM_CONTA_CHEQUE_OI");

            entity.Property(e => e.NumProcesso)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NUM_PROCESSO");

            entity.Property(e => e.NumeroAlvara)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NUMERO_ALVARA");

            entity.Property(e => e.QtdContrato)
                .HasColumnType("NUMBER(22)")
                .HasColumnName("QTD_CONTRATO");

            entity.Property(e => e.StatusSolicitacao)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("STATUS_SOLICITACAO");

            entity.Property(e => e.TipoLancamento)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("TIPO_LANCAMENTO");

            entity.Property(e => e.TipoTransferencia)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("TIPO_TRANSFERENCIA");

            entity.Property(e => e.UfComarca)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("UF_COMARCA");

            entity.Property(e => e.UsrCodUsuarioCriacao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_CRIACAO");

            entity.Property(e => e.UsrCodUsuarioEnvio)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("USR_COD_USUARIO_ENVIO");

            entity.Property(e => e.ValCorrecaoPag)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_CORRECAO_PAG");

            entity.Property(e => e.ValCorrecaoRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_CORRECAO_REC");

            entity.Property(e => e.ValDeposito)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_DEPOSITO");

            entity.Property(e => e.ValHonorarioRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_HONORARIO_REC");

            entity.Property(e => e.ValIrPag)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_IR_PAG");

            entity.Property(e => e.ValIrRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_IR_REC");

            entity.Property(e => e.ValJurosPag)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_JUROS_PAG");

            entity.Property(e => e.ValJurosRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_JUROS_REC");

            entity.Property(e => e.ValLevRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_LEV_REC");

            entity.Property(e => e.ValMulta)
                .HasColumnType("NUMBER(22,2)")
                .HasColumnName("VAL_MULTA");

            entity.Property(e => e.ValPrincipalPag)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_PRINCIPAL_PAG");

            entity.Property(e => e.ValPrincipalRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_PRINCIPAL_REC");

            entity.Property(e => e.ValReembolsoRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_REEMBOLSO_REC");

            entity.Property(e => e.ValRetificado)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("VAL_RETIFICADO")
                .IsFixedLength();

            entity.Property(e => e.ValSaldoGarantia)
                .HasColumnType("NUMBER(22,2)")
                .HasColumnName("VAL_SALDO_GARANTIA");

            entity.Property(e => e.ValTarifaRec)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_TARIFA_REC");

            entity.Property(e => e.ValTarifaTotal)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_TARIFA_TOTAL");

            entity.Property(e => e.ValTotalKit)
                .HasColumnType("NUMBER(22,5)")
                .HasColumnName("VAL_TOTAL_KIT");

            entity.HasOne(d => d.AgPexRelSolic)
                .WithMany(p => p.AgPexRelSolicResultado)
                .HasForeignKey(d => d.AgPexRelSolicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_APRSREL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AgPexRelSolicResultado> entity);
    }
}
