// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class ColunasPexRelSolicConfiguration : IEntityTypeConfiguration<ColunasPexRelSolic>
    {
        public void Configure(EntityTypeBuilder<ColunasPexRelSolic> entity)
        {
            entity.HasKey(e => e.IdColRelSolic)
                .HasName("CRS_PK");

            entity.ToTable("COLUNAS_PEX_REL_SOLIC");

            entity.Property(e => e.IdColRelSolic)
                .HasColumnType("NUMBER")
                .HasColumnName("ID_COL_REL_SOLIC");

            entity.Property(e => e.CampoAtivoRelSolic)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("CAMPO_ATIVO_REL_SOLIC")
                .HasDefaultValueSql("'S'\n")
                .IsFixedLength();

            entity.Property(e => e.NomColRelSolic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("NOM_COL_REL_SOLIC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ColunasPexRelSolic> entity);
    }
}
