// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data;
using Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Entities;
using System;
using System.Collections.Generic;

namespace Oi.Juridico.Contextos.V2.RelatorioSolicitacaoLancamentoPexContext.Data.Configurations
{
    public partial class TipoLancamentoConfiguration : IEntityTypeConfiguration<TipoLancamento>
    {
        public void Configure(EntityTypeBuilder<TipoLancamento> entity)
        {
            entity.HasKey(e => e.CodTipoLancamento);

            entity.ToTable("TIPO_LANCAMENTO");

            entity.Property(e => e.CodTipoLancamento)
                .HasPrecision(4)
                .HasColumnName("COD_TIPO_LANCAMENTO");

            entity.Property(e => e.DscTipoLancamento)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DSC_TIPO_LANCAMENTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoLancamento> entity);
    }
}
